### PR TITLE
[Piepline Tool] Upgrade Eto

### PR DESCRIPTION
**Pull request by cra0zy**
**NEEDS:** https://github.com/MonoGame/MonoGame.Dependencies/pull/118

This PR just upgrades Eto code for 2.4.1. Most notable stuff are:
- Eto Forms now supports drag and drop, so goodbye Xwt treeview
  - This does not implement drag and drop functionality since I am reworking part of its logic so that we can support linking, I just need this upgrade so I don't have to write Xwt code
- Eto is using my own fork of GtkSharp which requires no native glue libraries and does not use dllmaps for calling native assemblies, this means that the Linux installer now has 1 less dependency to worry about
  - This also allows me to ditch a lot of the wrapper code for Gtk stuff

### CODE REVIEW

**Comment by tomspilman** [comment]
@cra0zy - I merged the dependencies.

**Comment by cra0zy** [comment]
@tomspilman @dellis1972 Ok, so there are 2 ways to fix the build:
- downgrade Linux Pipeline Tool to use .NET Framework 4.6.1 and add the stub references (there are 96 stub references, they total to less than 3 MB so its not a big deal): https://www.nuget.org/packages/NETStandard.Library.NETFramework/2.0.0-preview1-25305-02
- upgrade mono on Mac build bot to the current stable (current stable is 5.8, the build bot is using 5.4.1)

**Comment by tomspilman** [comment]
> upgrade mono on Mac build bot to the current stable

I just upgraded the Mac build bot 2 nights ago.  I did an update in Xamarin studio which downloaded the latest stable for me and installed it.  Also installed VS for Mac as @dellis1972 requested.

Is there something else i need to upgrade?

**Comment by cra0zy** [comment]
@tomspilman Should be just a straightforward install of: http://www.mono-project.com/download/stable/#download-mac

Tho I don't mind downgrading the required .NET Framework version of Pipeline Tool for Linux, this bumped it up to 4.7.1 to avoid usage of those stub references.

**Comment by tomspilman** [comment]
> Should be just a straightforward install

So that is a Mono update and not a Xamarin Studio update (although i would have expected XS to update Mono).

Is there any danger of updating Mono separate from XS?  If not i'll update it as soon as i;m in the office today.

**Comment by cra0zy** [comment]
> Is there any danger of updating Mono separate from XS? If not i'll update it as soon as i;m in the office today.

No sure how mono stuff gets packaged on Mac, so I don't know. I guess we need @dellis1972 for this.

**Comment by tomspilman** [comment]
We can wait for @dellis1972 then.

We got a new Mac build box that i need to setup anyway.  It should make our Mac builds as fast if not faster than the Windows builds.

**Comment by cra0zy** [comment]
I would still like the mac build bot upgraded, but for now, https://github.com/MonoGame/MonoGame.Dependencies/pull/119

**Comment by dellis1972** [comment]
We should be able to safely update mono to 5.8 as well as both Xamarin.iOS
and Xamarin.Android.
I'm surprised that didn't happen? Usually when you update via Xamarin
Studio or Visual Studio for Mac update manager it
upgrades everything to the latest stable.

**Comment by tomspilman** [comment]
@cra0zy - The mac build box now has Mono 5.8 installed.

**Comment by cra0zy** [comment]
`
/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1140,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found.
`

Well that is.. strange...

**Comment by tomspilman** [comment]
Nothing can be simple on Mac or Linux. :)

**Comment by cra0zy** [comment]
May I take the easy way out? (https://github.com/MonoGame/MonoGame.Dependencies/pull/119)

**Comment by tomspilman** [comment]
> May I take the easy way out?

I'll let @dellis1972 decide on that.  I don't know what the implications are and hate to see us throw more stuff into the dependencies for temp fixes.

**Comment by cra0zy** [comment]
@dellis1972 Ping, waiting on you in here.

**Comment by dellis1972** [comment]
v4.7.1 looks like its shipping with Mono 5.10 :( Personally I'd rather wait for 4.7.1 and bump the Pipeline tool, having to pull in a ton of assemblies is a bit of a pain.. but I guess we don't have a choice since Mono 5.10 is going to be a while. I'll merge the Dependencies PR so we can at least get a Build here for me to test on Mac.

**Comment by cra0zy** [comment]
> v4.7.1 looks like its shipping with Mono 5.10 :( Personally I'd rather wait for 4.7.1 and bump the Pipeline tool, having to pull in a ton of assemblies is a bit of a pain.. but I guess we don't have a choice since Mono 5.10 is going to be a while.

It got released 2 days ago

**Comment by dellis1972** [comment]
> It got released 2 days ago
On which channel? Alpha I assume..its still 5.4 on stable here. I'm not sure we should be using Alpha on our bots. I know how many times things are broken at runtime between alpha and stable ;). Anyway I merged the dependencies, so if you bump in your PR we should get a build.

**Comment by cra0zy** [comment]
On stable actually: http://www.mono-project.com/download/stable/#download-mac

#### The latest Stable Mono release is: 5.10.0 Stable (5.10.0.140)

**Comment by dellis1972** [comment]
Hmm. not appearing for me in VSForMac

**Comment by cra0zy** [comment]
This is good to go.

**Comment by dellis1972** [comment]
OK merging on the provision that once 5.10 is available on stable we upgrade to 4.7.1 and remove those reference libraries from Dependencies. :)

**Comment by cra0zy** [comment]
> OK merging on the provision that once 5.10 is available on stable we upgrade to 4.7.1 and remove those reference libraries from Dependencies. :)

They in total take less than 3 MB so they shouldn't create any problems from downloading perspective.

**Pull request merged**
