### PR TITLE
Monogame did not respect Android screen orientation lock by user, fixed.

### PR DESCRIPTION
**Pull request by roponator**
Added check if user locked screen orientation. If he did lock it, then screen orientation is not changed anymore.

### CODE REVIEW

**Comment by jakepoz** [comment]
Just tested this, it's almost correct, but will fail with the following steps (Testing on Kindle Fire tablet)

1. On your device's main app launcher page, hold the device in portrait mode, and enable the Rotation lock in Portrait mode.
2. Hold your device in landscape mode, the rotation remains locked into portrait because of the Rotation lock setting.
3. Launch a Monogame project that supports both Portrait and Landscape mode.
4. The game will launch in Landscape mode, and be stuck in that setting, even though it should have locked itself into Portrait mode.

**Comment by roponator** [comment]
Could check what your ScreenOrientation is set to in the Android Activity.cs file (Activity1.cs in my case).

It is supposed to be ScreenOrientation = ScreenOrientation.FullUser, can (did) you test with this value?

**Comment by jakepoz** [comment]
Indeed, I have ScreenOrientation.Sensor, will try shortly with FullUser.

**Comment by roponator** [comment]
There is another strange rotation bug, the rotation seems to be offseted by 90 degrees, checking it out now...

**Comment by roponator** [comment]
I think I found the real reason for this issue, the previous fix was more of a workaround and is not needed anymore.

This fix just removes one line: that line overrode the FullUser (or some other) sensor mode.

**Comment by roponator** [comment]
So if you can please test this one now Jake :)

**Comment by jakepoz** [comment]
Hey, the latest fix while also setting the rotation mode to FullUser worked for me in a sample project, will test it in a real game shortly.

**Comment by jakepoz** [comment]
Sweet, just confirmed this does fully fix the problem for us in a live game we have on the Google Play and Amazon stores.

@KonajuGames Can you please consider merging this change into the main develop branch?

**Comment by KonajuGames** [comment]
Android has a confusing range of screen orientation options, and they keep adding more to it.  So should `ScreenOrientation.FullUser` be the default now?

**Comment by jakepoz** [comment]
Yeah, I think FullUser should be the new default, but it will only work right with the rest of this change.

**Comment by KonajuGames** [comment]
In that case, could we also get these lines changed as part of this PR.

https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/VisualStudio2010/Android/Activity1.cs#L14
https://github.com/MonoGame/MonoGame/blob/develop/IDE/MonoDevelop/MonoDevelop.MonoGame.Android/templates/Android/Activity1.cs#L20

This will fix new projects created from the templates.

**Comment by roponator** [comment]
Hm... So if we change the default to FullSensor we may break some existing apps when they will update their monogame code if they rely on the default values for orientation, that why I'd suggest we leave it as it is. 

@KonajuGames why would you like to change this: LaunchMode=LaunchMode.SingleInstance ?

**Comment by KonajuGames** [comment]
> why would you like to change this: LaunchMode=LaunchMode.SingleInstance ?

Not change that specific line.  The ScreenOrientation setting is missing from that template.

> Hm... So if we change the default to FullSensor we may break some existing apps when they will update their monogame code if they rely on the default values for orientation, that why I'd suggest we leave it as it is.

If they generated their project from the Visual Studio template, it will have a ScreenOrientation setting in the Activity already.  I don't think many projects have been generated from the MonoDevelop template, but if the developer was smart they would have added a ScreenOrientation setting anyway.

Changing these templates only affects new projects moving forward.  It does not retroactively change existing projects.

**Comment by roponator** [comment]
Ok if it's in the template then it's ok.

I pushed the changes propsed by @KonajuGames (was logged in as different user when commited though).

**Comment by jakepoz** [comment]
@KonajuGames Hey, any chance we can merge this in?

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
