### PR TITLE
Wiki to doc edit2

### PR DESCRIPTION
**Pull request by ralfjansson**
Copied text about migrating OpenTK 1.0 from old wiki to new documentation, Platform specific notes/android

### CODE REVIEW

**Comment by ralfjansson** [comment]
This text refers to Android, but also to ios. Perhaps we should add a new page for IOS under platform specific notes?

**Comment by tomspilman** [comment]
This info still valid @dellis1972 ?

**Comment by dellis1972** [comment]
Looks like the MonoGame Framework has been upgraded already to OpenTK-1.0 but the templates were not. We should fix that asap.

**Comment by dellis1972** [comment]
Fixed as part of #4509

**Comment by ralfjansson** [comment]
So were are we now. Do we merge my changes or drop them?

**Comment by tomspilman** [comment]
Info on OpenTK isn't importaint anymore.  Closing.

**Pull request closed without merging**
