### PR TITLE
Updated console references

### PR DESCRIPTION
**Pull request by mrhelmut**
Hello there,

I'm currently working on upgrading all console repositories to the latest ```develop``` structure.

I'd like to propose these changes which are more flexible to deal with specific situations.

@Jjagg @harry-cpp @tomspilman

### CODE REVIEW

**Review by Jjagg — APPROVED** [review]
No harm in doing this and if the flexibility helps, that's great :)

**Comment by tomspilman** [comment]
This is great!  Go for it!

**Comment by mrhelmut** [comment]
Before merging, I've updated this PR with a workaround for #7417. The idea is to have a target to use for platforms where ```System.Numerics.Vectors``` doesn't work.

What do you think?

**Comment by vpenades** [comment]
@mrhelmut I understand that adding the source code directly is just a temporary fix, until the consoles cross compiler is able to deal with the system.numerics.vectors, am I right?

**Comment by mrhelmut** [comment]
> @mrhelmut I understand that adding the source code directly is just a temporary fix, until the consoles cross compiler is able to deal with the system.numerics.vectors, am I right?

Yes, it's a quick workaround while we wait for console runtimes to support intrinsics.

**Comment by Jjagg** [comment]
Great, thanks @mrhelmut! Merging :)

**Pull request merged**
