### PR TITLE
Track GamePad packet number and general optimizations (fixes #5971)

### LINKED ISSUE #5971: GamePadState.PacketNumber stays 0 even when input is working.
Only issue I could find that might pertain is [https://github.com/MonoGame/MonoGame/issues/4002](#4002)

I've set up breakpoints on GamePadState.GetButtonPressed(Buttons.A) and it returns true but PacketNumber never updates.

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
- Replaced `if` with `switch` statement
- Added translation dictionary that translates from SDLs instanceId to our index
- Added Gamepad `PacketNumber` tracking

### CODE REVIEW

**Comment by Jjagg** [comment]
Nothing changed functionally with this in SDLGamePlatform, right?

**Comment by cra0zy** [comment]
Thee only change is:
```
case Sdl.EventType.ControllerButtonUp:
case Sdl.EventType.ControllerButtonDown:
case Sdl.EventType.ControllerAxisMotion:
    GamePad.UpdatePacketInfo(ev.ControllerDevice.Which, ev.ControllerDevice.TimeStamp);
    break;
```

**Comment by Jjagg** [comment]
@cra0zy I should have merged this before, there are conflicts now. If you can rebase, I'll merge it in :)

**Comment by cra0zy** [comment]
I was just about to fix it, I guess there is no longer a need :)

**Comment by nkast** [comment]
>> Nothing changed functionally with this in SDLGamePlatform, right?

I don't know if it's significant but I found two changes in WindowEvent.
-The EventId.FocusLost is no longer checked,  IsActive is never set to false.
-Previously the code would check if  (WindowID == _view.Id) before doing any changes.

**Comment by Jjagg** [comment]
You're right, both of those are important and need to be fixed.

**Comment by cra0zy** [comment]
Window id check technically is neither important nor needed.

**Comment by Jjagg** [comment]
It was implemented to fix #6432. It's a small effort to re-add the check.

**Comment by cra0zy** [comment]
What was needed is:
```
else if (ev.Window.EventID == Sdl.Window.EventId.Close)
```

Checking window id on every event is redundant, if anybody wanted to add a custom SDL window they will need to modify MG source to add custom event handling either way.

**Comment by Jjagg** [comment]
Oops, yes you're right. Nevermind the window id check then. That leaves us with handling the FocusLost event.

**Pull request merged**
