### PR TITLE
Upgrade Mac Editor to net8.0-macos. Upgrade Eto.Forms

### PR DESCRIPTION
**Pull request by dellis1972**
Fixes https://github.com/MonoGame/MonoGame/discussions/8469

Upgrade Eto.Forms to the latest stable version.
Switch to using `net8.0-macos` for the mac editor so we can support both x64 and arm64 architectures.
Upgrade AssimpNet to 5.0.x
Switch over to using MonoGame.Library.Assimp to get macOS arm64 support.

### CODE REVIEW

**Comment by mrhelmut** [comment]
Just a side note: we really need to get the content pipeline dependencies sorted out because things like reference AssimpNet while excluding parts of it to replace it with our own native build feels really backward. If we provide a native lib, we should provide our own minimal C# wrapper because replacing 1 nuget with 2 frankenstien nugets sounds like more problems than we're trying to solve.

**Comment by dellis1972** [comment]
> Just a side note: we really need to get the content pipeline dependencies sorted out because things like reference AssimpNet while excluding parts of it to replace it with our own native build feels really backward. If we provide a native lib, we should provide our own minimal C# wrapper because replacing 1 nuget with 2 frankenstien nugets sounds like more problems than we're trying to solve.

I agree, however if we want to meet the next release this will have to do for now. I don't have time to write a C# wrapper for assimp when I have bigger problems to solve like how to install these `dotnet tools`.

**Review by SimonDarksideJ — APPROVED** [review]

**Comment by zapoutix** [comment]
Hello, 
just tested on M3 with Sequoia 15.1 and dotnet 8.0.402 arm64 version

image

**Comment by mrhelmut** [comment]
@dellis1972 Could you elaborate on the reference of ```SixLabors.ImageSharp```?

**Comment by dellis1972** [comment]
> @dellis1972 Could you elaborate on the reference of `SixLabors.ImageSharp`?

Its a dependency of BCnEncoder.Net.ImageSharp. https://www.nuget.org/packages/BCnEncoder.Net.ImageSharp#dependencies-body-tab. 

I had to add an explicit PackageReference to stop the mac app from crashing on startup.

**Comment by mrhelmut** [comment]
Pfeww, we really need to sort the content pipeline dependencies out.

Good to go to me.

**Comment by DanielBeeck** [comment]
@zapoutix can you please explain how you got it running?
im going crazy trying to get it running.
I have a M2

**Pull request merged**
