### PR TITLE
Added support for arbitrary defines (i.e. LIGHTS=3) passed to the Effect compiler

### PR DESCRIPTION
**Pull request by rds1983**

### CODE REVIEW

**Comment by tomspilman** [comment]
This seems reasonable...  we will look at it soon and likely merge it.

**Comment by tomspilman** [comment]
Actually @rds1983 .

If you could add this feature to the unit test here:

https://github.com/MonoGame/MonoGame/blob/develop/Test/ContentPipeline/EffectProcessorTests.cs#L83

By adding something like this into `ParserTest.fx`:
```
#if MACRO_DEFINE_TEST != 3
This is a syntax error
#endif
```

**Comment by rds1983** [comment]
I've updated TestDefines()/DefinesTest.fx

**Comment by tomspilman** [comment]
That is great!  Thanks @rds1983 !

**Pull request merged**
