### PR TITLE
Update SpriteEffect.cs to honor the Viewport settings

### PR DESCRIPTION
**Pull request by stromkos**
Added position and min/max depth values from the GraphicsDevice.Viewport.
See #8074

### CODE REVIEW

**Comment by mrhelmut** [comment]
This seems correct, though it'd be best to wait for graphical unit tests to come back online before we merge just to make sure.

**Comment by Mindfulplays** [comment]
Are we sure this is correct? `glViewport` (or any platform Viewport call such as Metal/DX) should apply `vp.X/Y` etc already. And hence, the original code is correct. Note that the backbuffer that the sprite effect renders onto has the correct width/height within the viewport (not the screen). So the shader correctly multiplies normalized coords with the matrix W/H.

(Viewport X/Y is generally 0,0 so it's hard to test this. But, on Android, `GraphicsDevice::ResetClientBounds` explicitly sets viewport with a x/y offset due to safe-area/cutouts - which is a common enough use case so you can verify this quickly) 

I recommend not touching position.

**Comment by SimonDarksideJ** [comment]
Responses to feedback @stromkos ?

**Comment by mrhelmut** [comment]
We really need to test this.

**Comment by stromkos** [comment]
>I recommend not touching position.

For all current applications the defaults are fine and respected in this PR. 

This PR only **allows** changes to be reflected. Not that they would be needed for most use cases.  

The fixed values passed are from initial implementations and do not follow XNA documentation. This PR corrects that fixed-value test condition.

**Comment by Peru-S** [comment]
There are two things here: Viewport position and depth. Your PR touches both. I reckon not touching the viewport position as if it ain't broke, don't fix it (and I reckon it will actually break in subtle ways - I am not sure if you tested all the corner cases esp. Android).

Passing depth seems fine. 

Perhaps move the position part into a separate PR if you feel strongly and have tested it?

**Comment by stromkos** [comment]
@Peru-S 
Thank you for making me take a closer look. What should have been consistent and standardized across implementations was not at all.

The entire ViewPort implementation is completely messed up. For most purposes the value should be read-only since it is   either ignored or overwritten at seemingly random times. Yes, the events/calls can be determined at runtime...

The Width and Height values are set to the presentation parameters' values sometimes.

Game wide:

Any use of render targets ignores all values.  
To/from full screen sets defaults.


IOS ignores X,Y for all operations and sets height and width to the screen:

https://github.com/MonoGame/MonoGame/blob/ca3b1de568462654098b8a4da55fe68f23cdf79c/MonoGame.Framework/Platform/iOS/iOSGameView.cs#L195

and again here:
 
https://github.com/MonoGame/MonoGame/blob/ca3b1de568462654098b8a4da55fe68f23cdf79c/MonoGame.Framework/Platform/iOS/iOSGameView.cs#L225-L228

DirectX works with X,Y:

https://github.com/MonoGame/MonoGame/blob/ca3b1de568462654098b8a4da55fe68f23cdf79c/MonoGame.Framework/Platform/Graphics/GraphicsDevice.DirectX.cs#L570-L577

The base OpenGL is different( Y is inverted ): 

https://github.com/MonoGame/MonoGame/blob/ca3b1de568462654098b8a4da55fe68f23cdf79c/MonoGame.Framework/Platform/Graphics/GraphicsDevice.OpenGL.cs#L560

**Comment by Peru-S** [comment]
> The entire ViewPort implementation is completely messed up. For most purposes the value should be read-only since it is either ignored or overwritten at seemingly random times. Yes, the events/calls can be determined at runtime...

I don't think it's 'messed up' - MonoGame has evolved to support a wide variety of platforms while still maintaining API compatibility. For some platforms such as Android/iOS the concept of a viewport/`Window` are often blurry as it's really not the same as in DesktopGL/DX. 

So I think it's actually a strength of MG that these calls are plumbed without much workarounds for these platforms.

**Comment by stromkos** [comment]
@Peru-S 
Yes, I agree.  I just would have liked a consistent approach when possible, and in this case it was possible just not done.

Take textures  as an example, we can use whatever format we like, but it will be converted to an array of `Color`s then a byte array of the components, the the final conversion takes place. `Alpha8` becomes `R8` on GL platforms.

>So I think it's actually a strength of MG that these calls are plumbed without much workarounds for these platforms.

There is much less platform parity than you think. Yes these are minor things that add up. Where are Emojis??

**Pull request closed without merging**
