### PR TITLE
Refactoring AL entry points loading

### PR DESCRIPTION
**Pull request by mrhelmut**
This is a first pass at addressing #6515. It refactors the entry points so that ```DllNotFoundException``` and ```NoAudioHardwareException``` are correctly thrown upon OpenAL initialization failures.

cc @cra0zy @Jjagg 

If this gets merged, I'll work on another PR to make the ```Audio``` namespace optional.

### CODE REVIEW

**Comment by cra0zy** [comment]
> This is a first pass at addressing #6515. It refactors the entry points so that `DllNotFoundException` and `NoAudioHardwareException` are correctly thrown upon OpenAL initialization failures.

We are trying to do the opposite, no exception should be thrown if audio stuff is missing and instead everything should continue as normal.

**Comment by mrhelmut** [comment]
That's what I did here: https://github.com/MonoGame/MonoGame/pull/6516/files#diff-8c76ca43b718d6fa4dfb764513677375R200

I moved every static initialization to make sure that nothing gets statically initialized and throw an exception outside of the try/catch loop.

**Comment by cra0zy** [comment]
> I moved every static initialization to make sure that nothing gets statically initialized and throw an exception outside of the try/catch loop.

It never throws an exception... If it does not get initialized, the default value is set, the only thing that could throw an exception at that point is actually trying to call the delegate.

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/FuncLoader.Desktop.cs#L48

**Comment by mrhelmut** [comment]
> It never throws an exception... If it does not get initialized, the default value is set, the only thing that could throw an exception at that point is actually trying to call the delegate.

Oh ok! Though we still need to get them out of the static initializer so that we are sure that the native library pointer gets loaded before the delegates.

> On one console if MonoGame initialized the audio system itself and you happen to use FMOD it would not work correctly. In that project i had to hack the MG audio system to not initialize on startup to avoid the problem.

That's what I figured looking at the consoles. This should be workable.

**Comment by cra0zy** [comment]
> Oh ok! Though we still need to get them out of the static initializer so that we are sure that the native library pointer gets loaded before the delegates.

It always does as `NativeLibrary` is getting set on its declaration: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenAL.cs#L194

You don't need to move any initialization code.

**Comment by mrhelmut** [comment]
We do, if we want to make sure that ```DllNotFoundException``` and ```NoAudioHardwareException``` are correctly thrown. With static initialization it can get initialized anywhere and most importantly, outside the scope of these statements: 

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenALSoundController.cs#L152

https://github.com/MonoGame/MonoGame/blob/6f34eb393aa0ac005888d74c5c4c6ab5615fdc8c/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L245

Which makes those try/catch blocks useless, because any exception is uncatchable due to its static ctor nature (and a missing library is currently not a silent error), which makes the detection of an audio initialization failures impossible (or at least, not consistent at all).

We need to make sure that things are done in an ordered and timed manner. We also need to have a control over whether or not the library is getting loaded if we want to avoid it be loaded while using third party audio engines.

**Comment by tomspilman** [comment]
> We need to make sure that things are done in an ordered and timed manner. We also need to have a control over whether or not the library is getting loaded if we want to avoid it be loaded while using third party audio engines.

100% agree.

**Comment by cra0zy** [comment]
@mrhelmut you can just ask if the `NativeLibrary` is `IntPtr.Zero` at any time to know if it got loaded.

**Comment by tdeeb** [comment]
Have there been any updates regarding this?

**Comment by Jjagg** [comment]
@tdeeb Anything that happens is public. If it's not here it hasn't happened.

**Comment by mrhelmut** [comment]
I've been off to other stuff, but I'm planning to go back to this and make audio optional. But since there are multiple audio backend to deal with, it's most probably going to take some time before anything gets merged.

**Comment by cra0zy** [comment]
@mrhelmut Not sure if you got what changes I requested, anyway want me to make a new PR with those changes?

**Comment by mrhelmut** [comment]
@cra0zy I'm going to revamp this PR later, but feel free if they are changes you'd like to make, I'll branch from there.

**Pull request closed without merging**
