### PR TITLE
Expose TexelWidth/TexelHeight properties in Texture2D

### PR DESCRIPTION
**Pull request by nkast**
#5484 , 
https://github.com/MonoGame/MonoGame/pull/5267#issuecomment-257422132

### CODE REVIEW

**Comment by willmotil** [comment]
oh i just tried to do this it said sync failed, i suck with github.

**Comment by nkast** [comment]
It took me some time to get along with git and still use it to do just the basic stuff.
Sorry about that I didn't knew you were working too on a PR.

**Comment by tomspilman** [comment]
So the thing that makes me hesitate on this is https://github.com/MonoGame/MonoGame/issues/5111.

I have a first implementation I wrote for a PSVita port.  The pipeline reduces the texture sizes at build time and stores the original texture size in XNB (no change to the format).  Then at runtime when the XNB is loaded we store them in a new property `Texture2D.OriginalWidth/Height`.  Internal to `SpriteBatch` we use these to scale the texture cords back up to the correct range.  This makes like 90% of the work of rescaling assets automatic.

Maybe we just work that out later.  Just wanted to avoid adding an API to then remove it or change it again.

Still we should wait until after 3.6 which we plan to release in a week or so.

**Comment by nkast** [comment]
That's fine, let's see how this goes. Meanwhile a solution with reflection & c# extensions could work to get the internal properties.
Should I close this PR? We can see what is needed for #5484 after 3.6.

**Comment by tomspilman** [comment]
> Should I close this PR?

No it is fine... we'll merge this after 3.6 is all.

**Comment by willmotil** [comment]
Cool no rush its a ascetic nicety mostly. 

I wasn't really working on it i just thought no one had time, so i tried to do a quick submit but i screwed it up github said i failed to sync it whatever that means.

**Pull request closed without merging**
