### PR TITLE
Some updates to documentation

### PR DESCRIPTION
**Pull request by Jjagg**
I updated and clarified some sections of the documentation. I also wanted to update the images of the Pipeline Tool, but the inspector is not working on develop. @cra0zy 

image

### CODE REVIEW

**Comment by Jjagg** [comment]
Crap, didn't see #4559 :( :(

**Comment by Jjagg** [comment]
I'll revert the last four commits so only the pipeline updates stay, the rest is done by @cra0zy in #4559

**Comment by Jjagg** [comment]
After reading http://community.monogame.net/t/how-should-i-use-the-monogame-pipeline-tool/8013/2 I think this needs to be more detailed and include more pictures to be clearer. More specifically, I'll explain what the Pipeline Tool does and does not do, give more detail on the MonoGameContentReference build action, explain what exactly is needed to access content at run time, what mgcb is and how it's used and give some examples of scenarios that work and do not work.

**Comment by Jjagg** [comment]
@tomspilman If you're happy with this, it can be merged. At least MGContentReference will be mentioned in the docs, I think that will help people.
If I do more work on this I'll just start a new PR.

**Comment by dellis1972** [comment]
looks ok to me

**Comment by tomspilman** [comment]
Thanks @Jjagg ... merging.

**Comment by tomspilman** [comment]
Leave a comment

**Comment by Jjagg** [comment]
@tomspilman Looks like the documentation on the website hasn't been updated yet.

**Comment by tomspilman** [comment]
@Jjagg - I'm investigating...  the last artifact transfer to the website failed for some reason.  So forcing a rebuild which will try to update the docs again.

**Comment by tomspilman** [comment]
@Jjagg - Looks like it is fixed now.

**Pull request merged**
