### PR TITLE
PR to remove WindowsPhone (8.0) platform for 3.6

### PR DESCRIPTION
**Pull request by DDReaper**
Replaces #5321
Removed build references to Windows Phone
Class files untouched for now (although several could be removed)
Only removed actions from Nant file, definitions still exist to not break build server.

### CODE REVIEW

**Comment by tomspilman** [comment]
Looks ok at first glance... @KonajuGames ?

> update the build server and remove the WindowsPhone Build action.

We will do that in a few weeks after merging this PR giving time for other PRs to update or be merged.

**Comment by DDReaper** [comment]
Any update @tomspilman can we close this down now for 3.6?

**Comment by KonajuGames** [comment]
I missed this.  Yes, this looks good to me.  I'm happy to merge this.

**Comment by DDReaper** [comment]
Thanks @KonajuGames 
The .NET #5091 if moving ahead will need to refresh based on this update.

**Pull request merged**
