### PR TITLE
Use FuncLoader for OpenAL

### PR DESCRIPTION
**Pull request by cra0zy**
This could use a bit of testing on Android/iOS.

CC. @mrhelmut @dellis1972

### CODE REVIEW

**Comment by mrhelmut** [comment]
Awesome. I can't test this on mobile, but I'll give this a shot on Windows.

**Comment by dellis1972** [comment]
@cra0zy interestingly I was in Redmond last week and I was told they are adding support for `dllmap` to .net core (apparently). I've yet to find the appropriate commit though.

**Comment by cra0zy** [comment]
> @cra0zy interestingly I was in Redmond last week and I was told they are adding support for dllmap to .net core (apparently). I've yet to find the appropriate commit though.

I guess possible support in .NET Core 3.0 at the earliest, for now this allows us to properly support .NET Core 2.0.

**Comment by tomspilman** [comment]
Anyone get a chance to test this on iOS or Android yet?  @dellis1972 ?

**Comment by mrhelmut** [comment]
All good for me on Windows, Mac OS, and Linux.

The only issue I have with this is with MonoKickstart dll discovery. It works fine, but let's say that I have the Steamworks API there, MonoKickstart will still look for those libraries in the ```lib``` and ```lib64``` folders, not the ```x86``` and ```x64``` ones (so for any external libraries, you end up with two different dll path that are both required).

Good thing is that the ```MonoGame.Framework.dll.config``` map is indeed useless now.

It's no big deal, but it'd cool to have either MonoKickstart fixed or Linux/Mac OS path (though it'd be different from Windows, so I'd vote for MonoKickstart).

**Comment by cra0zy** [comment]
Actually the code of this PR right now first tries to load `x86` and `x64` folders, however if it does not find any libraries in them in falls back to trying to load them from the system specified location, and MonoKickstart is overriding the PATH variable so it will use the ones from MonoKickstart.

In other words you can choose where you want the libs to be, you don't need 2 copies, it checks both locations.

**Comment by cra0zy** [comment]
(also you could have just fixed the .dll.config file with the previous versions to use same paths as kickstart, or modified the kickstart start script to use same locations as stable MG, its pretty straightforward)

**Comment by mrhelmut** [comment]
I'll figure this out within MonoKickstart, it's no big deal.

Good to go for me! Thank you!

**Comment by cra0zy** [comment]
@tomspilman @dellis1972 Can this get merged?

**Comment by tomspilman** [comment]
Ok... lets give it a try.  Worst case we get a bug report we broke Android.

**Pull request merged**
