### PR TITLE
Make MonoGame content builder work from one source on all the platforms

### PR DESCRIPTION
**Pull request by cra0zy**
**WIP Changes**

Stuff done:
 - Removed a bunch of #if in MG.Framework.Content.Pipeline
 - Make it so Windows, Linux and Mac content builder stuff are using the exact same files

Why do this?
 - All part of the master plan: #5262

CC. @DDReaper

### CODE REVIEW

**Comment by DDReaper** [comment]
I'm liking this new
```
if (CurrentPlatform.OS == OS.Windows)
```
path a LOT. Will make the Multi-Platform building of solutions a lot easier as well.

**Comment by dellis1972** [comment]
@tomspilman @KonajuGames thoughts?

**Comment by KonajuGames** [comment]
This makes sense.  Would need to be rebased before merging.

**Comment by cra0zy** [comment]
@dellis1972 I'm guessing you wanted to ask thoughts on #3252, to be precise, https://github.com/MonoGame/MonoGame/issues/3252#issuecomment-298385909

**Pull request closed without merging**
