### PR TITLE
Fix BoundinBox.Contains(Vector3) to match XNA

### LINKED ISSUE #5245: BoundingBox.Contains(Vector3) returns incorrect ContainmentType
The code of BoundingBox.Contains(Vector3) method checks if any of the points is on the edge of the bounding box and immediately returns `ContainmentType.Interjects` even if the given Vector3 is completely inside it.

The method should return `ContainmentType.Contains` if all of the points are inside and `ContainmentType.Interjects` if any of them are inside.

### PR DESCRIPTION
**Pull request by Jjagg**
Fixes #5245. XNA returns Contains when a vector is on one of the boxes faces/edges so MG should too.

### CODE REVIEW

**Comment by james0x0A** [comment]
This matches my testing

**Comment by tomspilman** [comment]
@Jjagg - You ran these unit tests on XNA too?

**Comment by Jjagg** [comment]
Yes sir

**Comment by KonajuGames** [comment]
The unit tests are good, but I think they miss some coverage.  There are no tests that use a vector component of 1.0.  The min bounds of the box are tested, but no tests cover the max bounds of the box.

**Comment by Jjagg** [comment]
I'll add those tomorrow :)

**Comment by Jjagg** [comment]
Whatever that means in an international context

**Comment by tomspilman** [comment]
Thanks @Jjagg & @hifi !

**Pull request merged**
