### PR TITLE
Allow a Texture to have multiple outputs.

### PR DESCRIPTION
**Pull request by dellis1972**
On [Android](https://developer.android.com/guide/playcore/asset-delivery/texture-compression.) there is a requirement to support multiple Texture compression formats.
With this one change we will not longer ignore items which have a different output file. This will allow use to do things like this.

```
/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/config:
/profile:Reach
/compress:False
/processorParam:TextureFormat=Compressed
/build:ContentFont.spritefont

/importer:TextureImporter
/processor:TextureProcessor
/processorParam:TextureFormat=Compressed
/build:../../Textures/LogoOnly_64px.png;Textures/LogoOnly_64px

$if platform=Android
/processorParam:TextureFormat=Pvrtc
/build:../../Textures/LogoOnly_64px.png;Textures#tcf_pvrtc/LogoOnly_64px

/processorParam:TextureFormat=Astc
/build:../../Textures/LogoOnly_64px.png;Textures#tcf_astc/LogoOnly_64px

/processorParam:TextureFormat=Dxt
/build:../../Textures/LogoOnly_64px.png;Textures#tcf_s3tc/LogoOnly_64px
```

Note the output files are in different sub directories.

Update the editor to allow users to do this. 
Fix a bug in the editor where if you add a directory , hidden files were included. (e.g .DS_Store on mac).

### CODE REVIEW

**Comment by tomspilman** [comment]
What is this part:

/build:../../Textures/LogoOnly_64px.png;**Textures#**tcf_astc/LogoOnly_64px

I don't remember this syntax?  Or is that just part of the name of the folder?

**Comment by dellis1972** [comment]
> What is this `Textures#` part of:
> 
> ```
> /build:../../Textures/LogoOnly_64px.png;Textures#tcf_astc/LogoOnly_64px
> ```
> 
> I don't remember this syntax? Or is that just part of the name of the folder?

Its part of the Android Texture compression structure. See https://developer.android.com/guide/playcore/asset-delivery/texture-compression. This is just an example. But its part of the target folder name.

so in that example the output would be `Textures#tcf_astc\LogoOnly_64px.xnb`. 

But you could use other subfolders its not tied to Android.

**Comment by dellis1972** [comment]
The main difference is that Android will load from these "subfolders" behind the scenes without any need for us to do anything in the Framework.

**Comment by tomspilman** [comment]
> Its part of the Android Texture compression structure. 

Ah so not a MG feature at all... just a Android file system thing.

This fix just lets the same source file have multiple output files which is ok IMO.

**Review by tomspilman — APPROVED** [review]

**Review by harry-cpp — APPROVED** [review]

**Pull request merged**
