### PR TITLE
[MGCB] Fix flags not beeing processed

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by dellis1972** [comment]
@cra0zy do you have an example of what isn't working in this instance? It would help in the future if we need to look back at the history. 
My team lead always says "Write a commit comment like you are the one who is going too maintain it in the future.. but you've lost your memory" :)

**Comment by cra0zy** [comment]
Flags that do not have arguments weren't being processed at all, ie:
```
mgcb -r
mgcb \r
mgcb -rc
```

etc.

**Comment by tomspilman** [comment]
@cra0zy - So you are saying that `/rebuild` does not work right now?

Was it https://github.com/MonoGame/MonoGame/pull/5980 that broke this?

**Comment by cra0zy** [comment]
> @cra0zy - So you are saying that /rebuild does not work right now?
> 
> Was it #5980 that broke this?

No, `/r` does not work, `/rebuild` works fine.

**Comment by tomspilman** [comment]
Thanks @cra0zy .

**Comment by cra0zy** [comment]
Feel free to merge this, this is a PR after all :P

**Pull request merged**
