### PR TITLE
Support 24-bit DDS images

### LINKED ISSUE #5345: Texture DDS 24 bit - content build fail - Unsupported RGB exception
24 bit RGB DDS textures don't build.

Here's the link to one of our 24 bit DDS textures for testing:
https://www.dropbox.com/s/n835ojlc8ej1zgo/Stadium_60001_Atlas0.rar?dl=0

### PR DESCRIPTION
**Pull request by KonajuGames**
Add support for reading 24-bit DDS images, setting the alpha channel to opaque.

Fixes #5345

### CODE REVIEW

**Comment by tomspilman** [comment]
@KonajuGames - Can we get an image into the unit tests to verify this one?

**Comment by KonajuGames** [comment]
I'll have to work out how to create a small 24-bit DDS image for it.  The test image provided was several megabytes.

**Comment by tomspilman** [comment]
Bump!

**Comment by KonajuGames** [comment]
Added tests for R8G8B8 and X8R8G8B8, and added support for actual 24-bit and expanding it to 32-bit.

**Comment by tomspilman** [comment]
This is great... thanks @KonajuGames !

**Pull request merged**
