### PR TITLE
Use SharpDX and NVorbis from Nuget

### PR DESCRIPTION
**Pull request by rejurime**
Based on #7089 and #6144 I made changes to use SharpDX and NVorbis with Nuget.

### CODE REVIEW

**Comment by damian-666** [comment]
The lastest sharpDX is in nuget is 4.2 not 4.01..  i'm confused because the compiler told in vs2022  preview warned me i should use sharpDX.xinput 4.2 at some point, building my own app.. ( i cant remember when or why,  analyser or warning)  its  a net6.windows with  wpf,     i'm not using the develpbranch, usng the MG nuget release 3.8.1.   i'm using wpfinterop and it works now..  

 I do the same thing to my net6.0 app.. add nuget refs to the EXE  provject that update to 4.2... for all the parts xaudio2, xinput, mediafoundaton, dxgi, direct3d11, direct2d1.... then it  will replace the mg dependencies with those versions, and in the output folder.. mabye there is a roll forward way to do this...

image

**Comment by rejurime** [comment]
Hi @damian-666, Although the latest version of Sharpdx is 4.2.0, what I did in this specific PR was to replace the way of using it in the project (by using Nuget). I didn't want to update the Sharpdx version to the last one since that would imply doing more tests. I also checked which were the versions that the project is currently using (as you can see here https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/MonoGame.Framework.WindowsDX.csproj#L74). My idea is to update all the dependencies that MG already has from SharpDX to its latest version in a second PR, so I can test it better.

**Comment by damian-666** [comment]
Good idea. Honestly I don't remember why it gave me a warning that went away when I put the latest reference. ..the wpf interop from craftwork works either way , for me now ,with  unmerged PR sources.  But I'm not testing w Xbox sdk.   Right now it's fine  either way..but there's an older netstandard dependency  in the referenced version might be an issue..

**Comment by rejurime** [comment]
Hi! I want to check if I need to change something in this PR or if there are any feedback. Regards.

**Comment by rejurime** [comment]
Hi! Is there anything blocking this being merged? @mrhelmut can you help me? thanks!

**Comment by mrhelmut** [comment]
I am not maintaining MG lately and am taking some distance. I'd gladly leave my seat to someone with fresh ideas but it is not my call to make.

**Review by rbwhitaker — COMMENTED** [review]
In the OggStream file, what's the difference between the old `DecodedTime` and the new `TimePosition`? Why the change? They look like they might be conceptually the same thing, but I assumed the switch to NuGet would have put us on a version that matched what we had before, which should have the same API, and wouldn't have needed changes like this. (But I'm only asking for my own edification. I don't think this represents an actual problem.)

**Comment by TechPizzaDev** [comment]
The name change of the DecodedTime property was just arbitrary cleanup.
And it is recommended to use up-to-date NVorbis because old versions are quite buggy when it comes to seeking.

**Comment by rejurime** [comment]
I didn't know @mrhelmut sorry 😞.
Hi @rbwhitaker I made the change based on https://github.com/NVorbis/NVorbis/blob/519d4e2aae7d6a4d5bab552ec5c1e517e9c78855/NVorbis/VorbisReader.cs#L195.
@TechPizzaDev I also think that is best to upgrade versions, but I wanted the PR to be small and without many changes, just to switch from Dll to Nuget dependencies. My idea is to upgrade both the version of SharpDX and NVorbis in future contributions.

**Comment by harry-cpp** [comment]
This looks good to me, many thanks @rejurime, merging!

**Pull request merged**
