### PR TITLE
Move the DesktopGL platform over to use the GraphicsAdapter partial class [dont merge]

### PR DESCRIPTION
**Pull request by dellis1972**
In the continuing effort to update/remote old code in favour of
partial classes, this commit adds a GraphicsAdapter.SDL for the
DesktopGL platform.

### CODE REVIEW

**Comment by dellis1972** [comment]
@cra0zy I think this will need testing on a multi monitor setup. I'm not sure what the behaviour is supposed to be.. the old code we used to always grab the CurrentDisplayMode for the current window regardless of if that was on the current adapter. But then again we only ever had one adapter..

**Comment by dellis1972** [comment]
@tomspilman regarding my previous comment, it would be useful to know what the expected behaviour should be regarding GraphicsAdapter.CurrentDisplayMode in a multi monitor environment. and what happens when you move the screen from one to the other.

**Comment by tomspilman** [comment]
> it would be useful to know what the expected behaviour should be regarding GraphicsAdapter.CurrentDisplayMode in a multi monitor environment

I have a three monitor setup here... what tests do you think I should run under XNA?

My guess is that `CurrentDisplayMode` returns the information on the primary monitor only.

**Comment by KonajuGames** [comment]
The doc for GraphicsDeviceManager.FindBestDevice talks about a "current
adapter". I'm assuming that is the primary adapter since there is no other
concept of a current adapter anywhere else in the API.

**Comment by dellis1972** [comment]
@tomspilman I guess the test would be to run up and XNA app on one monitor, then move it to another monitor and see if any of the Adapter settings change.

**Comment by tomspilman** [comment]
@dellis1972 - So my findings.  I have a single ATI card with 3 monitors hooked up.  

After the game starts the `GraphicsAdapter.DefaultAdapter` does not change at all no matter where i move the game window.

I noticed that the default adapter is always whatever the "main display" is as defined in the Windows display settings.   Also the game Window always opens on that default display.

And even if i changed the default display in the Windows display settings while the game is running, the `GraphicsAdapter.DefaultAdapter` was always the one picked at game startup.  It never changes after start.

Hope this helps.

**Comment by KonajuGames** [comment]
I can do a test here soon with XNA, but my guess is that
GraphicsAdapter.DefaultAdapter won't change when you move the window from
one screen to another. The GraphicsDevice.Adapter value might though.

**Comment by willmotil** [comment]
I suggest you run those tests in full screen and change the display modes. Current adapter ussually matches the default adapter however you can list all the available adapters in xna.

**Pull request closed without merging**
