### PR TITLE
Added type deconstruction

### PR DESCRIPTION
**Pull request by Juhlinus**
As per #6094.

I don't know if this is something that has been considered at all, but I figured I'd add it either way if someone is interested. 😃

### CODE REVIEW

**Comment by KonajuGames** [comment]
I had no idea this was a new feature of C# and we had to implement support for it. The spelling error in the filename would need to be fixed first.

**Comment by Juhlinus** [comment]
@KonajuGames Tuple deconstruction is not really something you need to implement support, but if you want it for custom types then you need to implement support like it.

I renamed the file.

**Comment by Jjagg** [comment]
Yeah, this would be nice to add :) Thanks @Juhlinus!

Some comments:
- Can you add a License header (check any other classfile)
- This should go in the MonoGame namespace IMO.
- Could do with an r, g, b, a deconstructor for Color
- An entry should be added to the .definition file that Protobuild uses so this classfile is included in the generated projects. [here](https://github.com/MonoGame/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition#L319)'s an example entry. The new entry would be `<Compile Include="Utilities\TupleDeconstruction.cs" />` to add it for all platforms.

**Comment by Juhlinus** [comment]
@Jjagg I updated with the things you mentioned. 👍

**Comment by Jjagg** [comment]
Great! 

> Maybe the file shouldn't be called "TupleDeconstruction"?

I'd go with `Deconstructions.cs` and call the class `Deconstructions` as well.

**Comment by Juhlinus** [comment]
Sigh, I'm way too quick with for my own good. 😞

**Comment by cra0zy** [comment]
Wouldn't it be better for deconstructors to live next to their structs instead of a being in a separate file?

**Comment by Juhlinus** [comment]
It would eliminate the need for adding an extra using directive to your game in the case of wanting to use destructors. Other than that I don't think as a developer you'll notice much of a difference. I guess it boils down to how you guys want it to be implemented.

**Comment by cra0zy** [comment]
> It would eliminate the need for adding an extra using directive to your game in the case of wanting to use destructors.

Actually it would have no difference since you can just add separate namespace if you wanted.

Side note, you are using the wrong namespace, MonoGame still uses `Microsoft.Xna.Framework` as the default, not `MonoGame.Framework`.

**Comment by Juhlinus** [comment]
So, should I move the extensions to their respective files? (And update the namespace)

**Comment by cra0zy** [comment]
> So, should I move the extensions to their respective files? (And update the namespace)

I vote for yes, then again I am the one who suggested it so... @Jjagg you agree?

**Comment by Jjagg** [comment]
It does make sense to have the deconstruction methods in the Xna namespace so users don't need an extra using, so I'm fine with that. I think it's nice to have the deconstruction methods in a separate file, but I don't really mind either way. Sorry for the confusion @Juhlinus :p

**Comment by cra0zy** [comment]
@Jjagg Since I think you didn't notice, deconstruct methods don't need to be extension methods, they can (and should) be just extra methods in the struct, example:
```c#
class Point
{
    public int X { get; }
    public int Y { get; }
 
    public Point(int x, int y)
    {
        X = x;
        Y = y;
    }
 
    public void Deconstruct(out int x, out int y)
    {
        x = X;
        y = Y;
    }
}
```

**Comment by KonajuGames** [comment]
> deconstruct methods don't need to be extension methods

This is a very valid point.  They should only be extension methods for types that you do not own.  In this case, we own the types, so the Deconstruct methods should be in the types they are for.

**Comment by Jjagg** [comment]
> Since I think you didn't notice, deconstruct methods don't need to be extension methods

I did know this. I just think it'd be nice to have this specific functionality implemented in one place. But I really don't have a strong opinion on this.

**Comment by Juhlinus** [comment]
Should I add the methods to the "Public methods" region of each file, should I make a new region for just Deconstructors, or should I just put it at the bottom without any region?

**Comment by cra0zy** [comment]
> Should I add the methods to the "Public methods" region of each file, should I make a new region for just Deconstructors, or should I just put it at the bottom without any region?

Add them to the public region.

**Comment by Juhlinus** [comment]
There we go! Anything else while I'm at it? 😉

**Comment by Juhlinus** [comment]
It looks like it's failing because the version isn't C# on the build server (?). I tried to fix it with the packages.config, as you can see. I'm not very experienced with build servers, so it was basically a shot in the dark.

**Comment by Jjagg** [comment]
The build server uses C#5, so you can't use tuple syntax. You could test the Deconstruct methods by calling them directly e.g. `vec2.Deconstruct(out x, out y)`. That way people can still build MG with an older version of VS, but we ensure that tuple deconstruction will work too. You won't need the ValueTuple package either this way.

**Comment by Juhlinus** [comment]
There we go, build succeed.

**Comment by Jjagg** [comment]
For Ray it makes more sense to me to have position first, then direction. Not sure if that's a universal thing :p 

The tests aren't great, because they use a lot of duplicate values, so the order isn't checked. Though I don't think this really needs tests. It's easy to tell from the implementation that everything is correct :)

**Comment by tomspilman** [comment]
@KonajuGames  @dellis1972 @Juhlinus - This good to merge now?

**Comment by nkast** [comment]
@Jjagg 
>> For Ray it makes more sense to me to have position first, then direction. Not sure if that's a universal thing :p

I agree. It should match the order of the Constructor when possible.
`public Ray(Vector3 position, Vector3 direction)`

**Comment by KonajuGames** [comment]
It may be pedantic, but I agree that `Ray` should have the same parameter order as the constructor.

**Comment by tomspilman** [comment]
@nkast @KonajuGames - If i go ahead and merge this can one of you go back and fix `Ray`?

Don't want to leave this hanging longer if @Juhlinus isn't around.

**Comment by KonajuGames** [comment]
I'll merge it now and fix that `Ray` type.

**Comment by KonajuGames** [comment]
PR #6198 added.

**Pull request merged**
