### PR TITLE
Add Subscription section with Donate link to ReadMe.md

### PR DESCRIPTION
**Pull request by CartBlanche**
The updated button, now has options for 3 default amounts as well as a 4th for custom donation value as well as text to encourage a monthly subscription.

Once this is merged, I'll then create an appropriate tweet to promote it and the new sponsor button.

### CODE REVIEW

**Comment by Jjagg** [comment]
image

Is it possible to get rid of this?

**Comment by tomspilman** [comment]
@CartBlanche - Is there a way to embed the Paypal into a page?  Wondering if it would feel more official if it was embedded on to a page on the MG site.

**Comment by CartBlanche** [comment]
@Jjagg, @tomspilman What we should be using is this form - 
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick" />
<input type="hidden" name="hosted_button_id" value="CQ84R4FE7W69G" />
<input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />

</form>

But I couldn't find a way to make it a mark-down.

**Comment by Jjagg** [comment]
We can have arbitrary HTML on the website, even if the source files are markdown you can just write inline HTML. We already have the donate page that's linked to in the footer of the website: http://www.monogame.net/donate/

**Comment by tomspilman** [comment]
Yeah i can embed this into the donation page.  Is there a form we can embed for a one time donation too?

**Comment by CartBlanche** [comment]
@Jjagg I tried inlining that form into the ReadME.md, but it render correctly. Does the HTML need to be escaped in a special way for that to work?

**Comment by CartBlanche** [comment]
@tomspilman The one off donate form, with some pre-configs, looks like this

> <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
> <input type="hidden" name="cmd" value="_s-xclick" />
> <input type="hidden" name="hosted_button_id" value="XHSP3K7VTENNW" />
> <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
> 
> </form>

**Comment by Jjagg** [comment]
No GitHub markdown supports a limited set of HTML, so we can't embed it here.

**Comment by CartBlanche** [comment]
@Jjagg OK at least I wasn't going mad trying to get it to work. 
OK since we can't embed the subscribe form, my suggestions is that we update the donation page to have the new subscribe form and the proper donation form. I'll now change both the ReadMe.md and the yml to point to MG/donate. That way there is only ever 1 way to subscribe or donate and only 1 place for use to maintain/update.

**Comment by tomspilman** [comment]
@CartBlanche - The website is updated...

http://www.monogame.net/donate/
image

Sucks the subscription one doesn't at least mention MG:

image

Note the non-subscription link also lets you make a subscription:

image

**Comment by CartBlanche** [comment]
@tomspilman Let me see if that can be tweaked.

**Comment by CartBlanche** [comment]
@tomspilman  Please update the Subscription form to this, which updates the text to "MonoGame Subscription Options"
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="ARF7AP68BRT9W">
<table>
<tr><td><input type="hidden" name="on0" value="MonoGame Subscription Options">MonoGame Subscription Options</td></tr><tr><td><select name="os0">
	<option value="Bronze - Monthly">Bronze - Monthly : $5.00 USD - monthly</option>
	<option value="Silver - Monthly">Silver - Monthly : $10.00 USD - monthly</option>
	<option value="Gold - Monthly">Gold - Monthly : $25.00 USD - monthly</option>
	<option value="Platinum - Monthly">Platinum - Monthly : $50.00 USD - monthly</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
```

I've also changed the business name to **MonoGame Team**, so it is clearer where the money is going.

**Comment by CartBlanche** [comment]
@Jjagg @tomspilman I've also update the Donate link to not show subscription options. So it it purely for 1 off donations now. Everything consistently says MonoGame Team now.

**Comment by tomspilman** [comment]
@CartBlanche  Fixed

**Comment by CartBlanche** [comment]
Awesome! Tweet will go out in 5 minutes.

**Comment by cra0zy** [comment]
@tomspilman check the Maintainers Gitter channel, we need Mac build bot fixed so we can continue with Protobuild removal

**Pull request merged**
