### PR TITLE
Increasing code coverage for Model.

### PR DESCRIPTION
**Pull request by siudeks**
Work in progress for issue #4699

### CODE REVIEW

**Comment by tomspilman** [comment]
This is great @siudeks !

**Comment by siudeks** [comment]
Goood :) I'll finish the rest of requested unit tests in my spare time. Feel free to reject / comment in any case of doubts

**Comment by Jjagg** [comment]
@siudeks Could you add the ModelTest.cs file to the Protobuild definitions? That will make Protobuild include the file in the generated project files (.csproj) when it generates them. See how the others are added here: https://github.com/MonoGame/MonoGame/blob/develop/Build/Projects/MonoGame.Tests.definition#L143

It would also be nice if you could include ModelTest.cs in the XNA test project file (which is not generated by Protobuild). If you have XNA installed you can run the tests in that project file to check for XNA compatibility which is nice for more intricate stuff.

**Comment by siudeks** [comment]
Will investigate this issues and do till the end of week.

**Comment by siudeks** [comment]
Hey. I investigated scope of changes requested by @Jjagg. Updating Protobuild definition files is a very simple task and I see the point. More interesing is updating MonoGame.Tests.XNA with new tests.

Original XNA Model class doesn't have public constructor but MG Model class contains it. I use the ctor in my tests.  In the clash of XNA vs MG implementation I see that the best approach is to rewrite my tests to make them compatible with both: XNA and MG, so - in that particular case - means to avoid public Model constructors.

Any thougths? @Jjagg ? @tomspilman ? Did you notice this kind of compatibility issue in project? what is preferred approach?

**Comment by Jjagg** [comment]
You can use preprocessor directives to ignore code that does not compile for XNA if you think it's worth testing in MonoGame. If you can write tests so they work for both xna and MG that's a plus because it tests compatibility.

#if !XNA
... // test goes here
#endif

**Comment by siudeks** [comment]
Sadly speaking, for Model test(s) seems better to use !XNA because - at the first look - XNA supports loading models only from predefined assets what is far from pure unit tests ...

**Pull request merged**
