### PR TITLE
Fixed the Scissor rect calculation on DesktopGL and OpenGL platforms

### PR DESCRIPTION
**Pull request by dellis1972**
Fixes https://github.com/MonoGame/MonoGame/issues/5947

Scissor rectangle seems to be calculated always from the window, not from the current viewport.

### CODE REVIEW

**Comment by tomspilman** [comment]
@vchelaru - This looks correct to you?  Does it fix your bug?

**Comment by vchelaru** [comment]
Yes, the code and test look good. I don't know if I'll get to test it anytime soon though, because I've implemented a temporary workaround and moved on to a different project. 

I'll add a todo for myself in my trello board to check it out, but if it passes the test I say 👍

**Comment by tomspilman** [comment]
Thanks @dellis1972 and @vchelaru !

**Comment by vchelaru** [comment]
Apologies for the late reply but I ran tests on my end and it seems to have fixed the problem for me too.

**Pull request merged**
