### PR TITLE
Remove PNG Utility Classes

### LINKED ISSUE #6870: Remove png classes
We're now using StbImageSharp for all public platforms.
If closed platforms do not use the [png classes](https://github.com/MonoGame/MonoGame/tree/develop/MonoGame.Framework/Utilities/Png) we have or if they can be migrated to StbImageSharp, we should remove the `MonoGame.Framework/Utilities/Png` folder.

@tomspilman

### PR DESCRIPTION
**Pull request by 06needhamt**
Closes #6870

This pull request is still a work in progress. I am just creating it so I can see the CI Test results as I am having issues testing on my own machine.

Sorry I messed up the last one

### CODE REVIEW

**Comment by cra0zy** [comment]
Build bot is currently not working properly so don't worry about failing builds for now.

**Comment by 06needhamt** [comment]
@cra0zy OK, so how can I check that my changes haven't broken anything on the platforms I am unable to build such as Mac and iOS?

**Comment by cra0zy** [comment]
I'll pine everyone once its back online, waiting for @tomspilman on that one.

**Comment by harry-cpp** [comment]
Build bot is working, just pull/rebase from develop.

**Comment by 06needhamt** [comment]
@harry-cpp Done. Is there anything else that needs to be done to get this merged?

**Comment by harry-cpp** [comment]
We need to wait for @tomspilman to check with him on close platform usage of this.

Alternatively @mrhelmut could help.

**Comment by tomspilman** [comment]
@harry-cpp - We don't use this on the console builds.  So we should be fine.

**Comment by harry-cpp** [comment]
Great, thanks @06needhamt , merging!

**Pull request merged**
