### PR TITLE
[DesktopGL] Use wglGetProcAddress on Windows for loading OpenGL functions

### PR DESCRIPTION
**Pull request by cra0zy**
I'll have time to test this out later, however if one of you has the time, comment the results bellow.

Fixes: #6386

### CODE REVIEW

**Comment by james0x0A** [comment]
Looks like this doesn't quite work.  I think a call to `wglMakeCurrent` may be necessary after the context is created so that the appropriate extensions are enabled when when wglGetProcAddress is called.

**Comment by james0x0A** [comment]
I've done some testing and `wglMakeCurrent` is not absolutely necessary to get running, so I am not sure why SDL calls it that way. The problem seems to be the way wglGetProcAddress  is loaded.  Using `Windows.GetProcAddress` and marshalling a delegate works.

**Comment by cra0zy** [comment]
Yea, I found something fishy about what SDL is doing as well, for DesktopGL under Windows we'll have the `SDL_GetProcAddress` to load up the opengl functions.

Loading OpenGL on Unix platforms is so much easier.

**Comment by cra0zy** [comment]
This has been moved to: #6389

**Pull request closed without merging**
