### PR TITLE
Update the UWP Template to use the Latest SDK

### PR DESCRIPTION
**Pull request by dellis1972**

### CODE REVIEW

**Comment by dellis1972** [comment]
@DDReaper does this look right to you?

**Comment by DDReaper** [comment]
That looks fine and solves the annoying NetCore update. Although I suspect the template still needs a little love, as creating a new MG game using 15603 (or higher) crashes the project creation.  Currently you need to select no higher than 14393 and then upgrade.  Sadly I just don't have the time atm to look at it.

**Comment by DDReaper** [comment]
Did you need any extra help testing / validating this @dellis1972 ?

**Comment by dellis1972** [comment]
Any help would be appreciated :)

**Comment by tomspilman** [comment]
@dellis1972 @DDReaper any progress on this?  Is it good to go?

**Comment by DDReaper** [comment]
Let me re-test following this latest round of merges. 2 ticks

**Comment by DDReaper** [comment]
Yup, looks good to me and doesn't cause any issues as far as I can see.  Merge it @tomspilman ! :D

**Pull request merged**
