### PR TITLE
Add Windows 8.1 project generation to Protobuild definitions.

### PR DESCRIPTION
**Pull request by kjpou1**
This will create project and solutions for Windows 8.1 version of MonoGame so that it can be loaded in Visual Studio 2015.

### CODE REVIEW

**Comment by kjpou1** [comment]
Woops. That should have read "This will now load in Visual Studio 2015"

**Comment by nkast** [comment]
What's the status of this PR? 

Every time I generate the projects from `MonoGame.Framework.definition` I have to retarget Windows8 to Windows8.1. Should this be fix by this PR? 
Windows8.0 is no longer supported by MG, isn't that right?

**Comment by nkast** [comment]
@hach-que 
Protobuild doesn't seem to support Windows81.
How can we force the &gt;TargetPlatformVersion&lt;8.1&gt;/TargetPlatformVersion&lt; tag in the `MonoGame.Framework.Windows8.csproj` ?

**Comment by hach-que** [comment]
Is this different to the `WindowsUniversal` platform?

**Comment by nkast** [comment]
Yes, it has to be similar to WindowsPhone81

https://github.com/Protobuild/Protobuild/blob/1d096deb50efeb8138d5a251f75a19620faca55c/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L123-L132

**Comment by hach-que** [comment]
My suggestion would be to submit a pull request to add support for Windows81.  It sounds a bit weird to target Windows 8.1 specifically though (and not Windows 10 or Windows 8).

**Comment by tomspilman** [comment]
We no longer support WinRT for 8.0/8.1 and https://github.com/MonoGame/MonoGame/issues/6207.

**Pull request closed without merging**
