### PR TITLE
Updated and added links to latest MonoGame 3.8 content in tutorials.md

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
Refresh the YT links from my site to the latest MonoGame 3.8 content into the tutorials.md docs

### CODE REVIEW

**Comment by tomspilman** [comment]
@Jjagg you mentioned DocFX has some thing to detect bad links right?  Maybe we can make it fail the build in that case?

**Comment by SimonDarksideJ** [comment]
I believe it showed up in the build logs.  But I thought I checked all the other links when last I reviewed this list.

I'll double-check.

**Comment by SimonDarksideJ** [comment]
Nope @tomspilman , just tested all the links on that page. Working fine.

Some are probably not relevant anymore, but that is another matter entirely :D

**Comment by Jjagg** [comment]
Docfx checks internal references, but it does not ping web URLs.

**Comment by tomspilman** [comment]
I bet we could knock up some C# using a regex we could write inline to the Cake script to check urls and report errors.

**Pull request merged**
