### PR TITLE
Reduce WinForms garbage.

### PR DESCRIPTION
**Pull request by nkast**
reducewinformsgarbage

Those are ~400 WM_MOUSE messages. `Application.DoEvents()` allocates about 5 times more memory than `Application.Run()` on each Message.
*(25).vsp* = Application.DoEvents()
*(23).vsp* = Application.Run()

### CODE REVIEW

**Comment by nkast** [comment]
Interesting! Test Mac failed. 
does Mac platform use `WinFormsGameWindow.cs`?

**Comment by Jjagg** [comment]
The NUnit test runner crashed. cc @tomspilman

**Comment by tomspilman** [comment]
@nkast - Is your branch updated to the latest develop changes?

**Comment by tomspilman** [comment]
Yeah looks like you have not updated since Feb.  There were fixes and changes for unit tests to work correctly.

**Comment by nkast** [comment]
>Yeah looks like you have not updated since Feb. 

very true. 
I am on it.

**Comment by tomspilman** [comment]
@dellis1972 - Do you think it matters if we support Mono on Windows?

@Jjagg - Also this might in some way help with https://github.com/MonoGame/MonoGame/issues/5656 ?

**Comment by cra0zy** [comment]
> @dellis1972 - Do you think it matters if we support Mono on Windows?

I don't think we should, especially since .NET Core is a thing.

**Comment by Jjagg** [comment]
> Also this might in some way help with #5656 ?

I looked at the code and also thought it might fix that issue. @nkast does this branch call the update method while dragging the window?

**Comment by nkast** [comment]
Unfortunately no, the #5656 is default behavior of Windows.

**Comment by MichaelDePiazzi** [comment]
FYI - I've been testing this change with my game for a week or so now, and all seems to be working as expected. And I've just released an experimental build to my users to test it further. I don't expect any problems though, it seems pretty solid.

**Comment by MichaelDePiazzi** [comment]
FYI - After about a month of testing this in an experimental branch of my game, I have not come across any problems with this. I've also recently taken my game update out of of experimental and released it to everyone else.

**Comment by Jjagg** [comment]
That's good enough for me! :) 
Thanks @nkast!

**Pull request merged**
