### PR TITLE
Applied the suggested changes for #6728.

### PR DESCRIPTION
**Pull request by itsBuggingMe**
Just added the suggested changes for #6728.

### CODE REVIEW

**Comment by mrhelmut** [comment]
This seems fine to me, but requesting a second review since it's a workaround.

@itsBuggingMe would you mind rebasing your PR to resolve the merge conflict?

**Comment by SimonDarksideJ** [comment]
Looks like there are merge conflicts, can you resolve @itsBuggingMe ?

**Comment by dellis1972** [comment]
Looks like the rebase did not go as planned, I'm pretty sure this should not be 140 commits.

**Comment by SimonDarksideJ** [comment]
If you have the time @itsBuggingMe , might I suggest you recreate this PR on a fresh clone of MonoGame (just clone and then copy over the changed files from here).

Shouldn't take long and will be far easier that trying to get this PR aligned :D

**Comment by itsBuggingMe** [comment]
Alright, I will do that. Easier than figuring out git for me XD. I will close this PR now.

**Pull request closed without merging**
