### PR TITLE
RPC curves are now updated before Cue is played

### PR DESCRIPTION
**Pull request by tomspilman**
This PR fixes XAct to ensure RPC curve values are updated before a cue us played.

### CODE REVIEW

**Comment by KonajuGames** [comment]
Looks good. Merging.

**Comment by DDReaper** [comment]
SO do we support Xact fully now through the content pipeline or is there still work to do?

**Comment by tomspilman** [comment]
@DDReaper 

> SO do we support Xact fully now through the content pipeline or is there still work to do?

There is still work to do.

I outlined exactly what needs to happen a few years ago, but no one as taken the project on.  See https://github.com/MonoGame/MonoGame/issues/2661.

The flip side is FMOD works great with MonoGame and is a "professional" solution that works really well on desktops and consoles.

Someone has to jump in here if they want to keep XACT alive as a viable free alternative.

**Comment by DDReaper** [comment]
Is the FMOD solution documented anywhere?  First I've heard/seen of it

**Pull request merged**
