### PR TITLE
Fix for #1880. Added a couple overloads for a garbage-less BoundingBox.CreateFromPoints()

### PR DESCRIPTION
**Pull request by YTN0**
See issue #1880

### CODE REVIEW

**Comment by YTN0** [comment]
@cra0zy  Done!

**Comment by cra0zy** [comment]
I meant doing the following:
```
public static BoundingBox CreateFromPoints(List<Vector3> points, int index = 0, int count = -1)
{
    if ( count == -1)
        count = points.Count;

    // Add code here
}
```

**Comment by cra0zy** [comment]
(feel free to do it for the existing CreateFromPoints method as well)

**Comment by YTN0** [comment]
@cra0zy  Done... again!

I didn't modify the original / existing API since it takes an IEnumerable<Vector3> and would require keeping a counter in the loop and skipping iterations until you hit the index and then counting from there. 

I'd rather not mess with the original API too much.

**Comment by cra0zy** [comment]
> I'd rather not mess with the original API too much.

Definitely agree with that, didn't remember what the original API was using.

**Comment by cra0zy** [comment]
This looks great, thanks @YTN0, merging!

**Pull request merged**
