### PR TITLE
[DesktopGL] Don't call sizechanged when changing size from code

### PR DESCRIPTION
**Pull request by cra0zy**
@dellis1972 This should fix your test in #5587

### CODE REVIEW

**Comment by dellis1972** [comment]
This looks ok. I would like to test it on a game to make sure though. It does indeed fix the unit test though :)

**Comment by dellis1972** [comment]
@cra0zy slight problem with this, when starting a game in fullscreen it looks like the viewport (or client size) is not set correctly (probably because we don't raise the event).. 

I'll try to knock up a demo.

**Comment by Jjagg** [comment]
That's not related to the event. That must have been an issue before the changes here too.

**Comment by dellis1972** [comment]
This looks good

@mrhelmut any objections? 

@tomspilman I can hold off merging this unit 3.6.1 is done.

**Comment by mrhelmut** [comment]
This is fine! Sorry for the late reply, I was off the grid.

**Pull request merged**
