### PR TITLE
Fixed XML deserialization of Curve type

### PR DESCRIPTION
**Pull request by zigzag312**
Fixes issue #5492.

- Changed order of properties inside Curve class so that order in serialization/deserialization matches XNA's
- Added CurveKeyCollectionSerializer that serializes/deserializes CurveKey collection packed like XNA
- Added unit tests

### CODE REVIEW

**Comment by KonajuGames** [comment]
Changing the order of fields is not reliable because the C# compiler can re-order fields and properties if it needs to. The is an attribute to prevent re-ordering, but if the XNA class didn't have it then we shouldn't.

**Comment by KonajuGames** [comment]
New source files need to be added to the Protobuild definition files in the Build directory.

**Comment by zigzag312** [comment]
> New source files need to be added to the Protobuild definition files in the Build directory.
New *cs files that I added to the project?

**Comment by zigzag312** [comment]
> Changing the order of fields is not reliable because the C# compiler can re-order fields and properties if it needs to. The is an attribute to prevent re-ordering, but if the XNA class didn't have it then we shouldn't.

I tried to change order of elements in xml and open it with XNA Curve Editor tool and it fails to open it. So XNA depends on order of elements inside xml. I can't find any serializer specific for Curve class inside XNA so I have no idea how they do it then.

**Comment by tomspilman** [comment]
Thanks @zigzag312 ... merging!

**Pull request merged**
