### PR TITLE
Add RollForward directive, so that if user has newer version of dotnet…

### PR DESCRIPTION
**Pull request by CartBlanche**
… installed it will still work.

More info available here - https://natemcmaster.com/blog/2019/01/09/netcore-primitives-3/

### CODE REVIEW

**Comment by mrhelmut** [comment]
We should likely have a rollforward directive on all of the projects. Does it still apply to net6 and future releases?

**Comment by CartBlanche** [comment]
@mrhelmut I've personally not had the opportunity to test if it is still required for .NET 6+, but would think/hope that MS would continue to allow it to work with newer versions.

**Comment by mrhelmut** [comment]
I took a look at the documentation and this seems valid with net6 and net7 as well.
I hope that you don't mind, I applied your suggestion to all the repository with #7789 while doing other stuff, so I'll be closing this one.

**Comment by CartBlanche** [comment]
As long as it proved useful in some way, I'm happy with that.

**Pull request closed without merging**
