### PR TITLE
[Pipeline Tool] Added message on MGCB Compiler process end

### PR DESCRIPTION
**Pull request by cra0zy**
Fixes: #3960

### CODE REVIEW

**Comment by tomspilman** [comment]
This isn't a fix.  The fix is finding why the MGCB.exe process is leaving without reporting error/success.

**Comment by cra0zy** [comment]
> This isn't a fix. The fix is finding why the MGCB.exe process is leaving without reporting error/success.

MGCB crashes with Native Stacktrace... I have a fbx model that does it, but it's not the only thing that can cause this type of crash. There isn't just one thing that can cause it.

Anyway we do need this because in case that something like this does happen, it would be useful to let people know that compiler process has ended.

Tho it doesn't really fix the main issues.

**Comment by tomspilman** [comment]
> MGCB crashes with Native Stacktrace

Sounds like we are just missing a final `catch (Exception ex)` here:

https://github.com/mono/MonoGame/blob/develop/Tools/MGCB/BuildContent.cs#L307

Specifically that shouldn't happen and we should report it as an unexpected exception.

> I have a fbx model that does it

Sounds like maybe FBX processing is then maybe missing some protection specifically against native code throwing exceptions.

**Comment by cra0zy** [comment]
> Sounds like we are just missing a final catch (Exception ex) here:
> 
> https://github.com/mono/MonoGame/blob/develop/Tools/MGCB/BuildContent.cs#L307
> 
> Specifically that shouldn't happen and we should report it as an unexpected exception.

Doesn't help :\, just tried it.

**Comment by tomspilman** [comment]
> Doesn't help :\, just tried it.

So this is an uncatchable exception?  I forgot these were possible in C#.

So doesn't MGCB.exe return an error code at least to the pipeline tool?

**Comment by cra0zy** [comment]
> So doesn't MGCB.exe return an error code at least to the pipeline tool?

Kind of.

It returns it to the debugger so it writes it out inside Pipeline Tool debugger window.

**Pull request closed without merging**
