### PR TITLE
[SDL] Remove unneeded hacks and update SDL to 2.0.5

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
 - SDL update for 2.0.5
 - Remove unneeded hacks

Notes:
 - Resolves #5273 in a proper manner

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 @mrhelmut - This should get a good test against your own projects.

**Comment by mrhelmut** [comment]
I will asap. Definitely one of the last stepping stone to get DesktopGL shiny and new.

**Comment by mrhelmut** [comment]
Tested on Windows and MacOS. Everything is working fine (inc. resizing, borderless, etc.). Glad to see those hacks out.

**Comment by mrhelmut** [comment]
Should we summon the @tomspilman ?

**Comment by tomspilman** [comment]
Sorry... been a busy week.  Merging!

**Pull request merged**
