### PR TITLE
Fixes #4277 and allows GraphicsManager.ApplyChanges() to work on Mac

### LINKED ISSUE #4277: (Mac) Changing any GraphicsDeviceManager settings and calling ApplyChanges results in silent crash
The following code is an example that will trigger the crash:

```
_graphicsManager.PreferredBackBufferWidth = width;
_graphicsManager.PreferredBackBufferHeight = height;
_graphicsManager.IsFullScreen = isFullScreen;
_graphicsManager.ApplyChanges();
```

The ApplyChanges line is what causes it. There is no stack trace at all and no logs that I can find anywhere. Changing anything and calling ApplyChanges is all it takes to repro.

### PR DESCRIPTION
**Pull request by prime31**

### CODE REVIEW

**Comment by prime31** [comment]
@tomspilman I've got a quick question with regard to the workflow you use when dealing with source. My initial thought was to just do the following:

- branch off develop
- add a fresh MonoMac project to the solution for test code
- replace the NuGet packages with a reference to the MonoGame.Framework.MacOS project

While this compiles just fine even with just the template project it throws an InvalidFramebufferOperationExt at launch while doing PlatformClear (log below). Swapping back to the NuGet packages clears up the error even when branching from a clean vanilla master pull. I must be missing something simple and I can't find any docs that detail work from source.

I imagine you have a rock-solid workflow by now so I was wondering if you can let me know what it is so that I can get some bug fixes pushed back to master.

```
Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned InvalidFramebufferOperationExt
  at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError () [0x00024] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsExtensions.cs:883
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformClear (ClearOptions options, Vector4 color, Single depth, Int32 stencil) [0x0010a] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs:314
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear (Color color) [0x00020] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsDevice.cs:417
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyRenderTargets (Microsoft.Xna.Framework.Graphics.RenderTargetBinding[] renderTargets) [0x000c1] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsDevice.cs:722
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize () [0x000b9] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsDevice.cs:277
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor (Microsoft.Xna.Framework.Graphics.GraphicsAdapter adapter, GraphicsProfile graphicsProfile, Microsoft.Xna.Framework.Graphics.PresentationParameters presentationParameters) [0x00122] in /Users/desaro/Desktop/MG/MonoGame.Framework/Graphics/GraphicsDevice.cs:200
  at Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize () [0x00089] in /Users/desaro/Desktop/MG/MonoGame.Framework/GraphicsDeviceManager.cs:385
  at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice () [0x00002] in /Users/desaro/Desktop/MG/MonoGame.Framework/GraphicsDeviceManager.cs:90
  at Microsoft.Xna.Framework.GamePlatform.BeforeInitialize () [0x0003a] in /Users/desaro/Desktop/MG/MonoGame.Framework/GamePlatform.cs:207
  at Microsoft.Xna.Framework.Game.DoInitialize () [0x0000d] in /Users/desaro/Desktop/MG/MonoGame.Framework/Game.cs:678
  at Microsoft.Xna.Framework.Game.Run (GameRunBehavior runBehavior) [0x0003b] in /Users/desaro/Desktop/MG/MonoGame.Framework/Game.cs:384
  at Microsoft.Xna.Framework.Game.Run () [0x0000d] in /Users/desaro/Desktop/MG/MonoGame.Framework/Game.cs:370
  at TesterProject.AppDelegate.FinishedLaunching (MonoMac.Foundation.NSObject notification) [0x00037] in /Users/desaro/Desktop/MG/TesterProject/Main.cs:49
  at at (wrapper dynamic-method) System.Object:[TesterProject.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at at (wrapper native-to-managed) System.Object:[TesterProject.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at at (wrapper managed-to-native) MonoMac.AppKit.NSApplication:NSApplicationMain (int,string[])
  at MonoMac.AppKit.NSApplication.Main (System.String[] args) [0x0003d] in <filename unknown>:0
  at TesterProject.Program.Main (System.String[] args) [0x0001d] in /Users/desaro/Desktop/MG/TesterProject/Main.cs:26
```

**Comment by KonajuGames** [comment]
That would be a fine way to test changes.  Not sure why it should throw an error on Clear.

**Comment by prime31** [comment]
@konajugames I haven't found a solution for it besides using release builds to hide the GL error. A fresh pull of master run in debug mode on a Mac results in that error every time.

**Comment by LithiumToast** [comment]
`Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned InvalidFramebufferOperationExt` is issued in #3581

**Comment by ambs** [comment]
How is this going? ApplyChanges to allow window resizing on Mac is VERY VERY VERY welcome.

**Comment by tomspilman** [comment]
@dellis1972  @cra0zy - Should we merge this or close it?  With the upcoming SDL2 changes is this moot?

**Comment by cra0zy** [comment]
This is going to Xamarin.Mac/MonoMac, so it's better to wait for #4693

**Pull request closed without merging**
