### PR TITLE
Move IGraphicsContext and IWindowInfo and restrict them to OpenGLGraphics

### PR DESCRIPTION
**Pull request by nkast**

### CODE REVIEW

**Comment by Jjagg** [comment]
Could you also include these files in the OpenGL.targets file at MonoGame.Framework/Platform/OpenGL.targets?

**Comment by nkast** [comment]
Is that ok? Does the build server verify/build those?

**Comment by cra0zy** [comment]
Not yet, still waiting for Tom to come online so we can tell him to install .NET Core and update mono of the build bots.

You can test it yourself by running `build.ps1` powershell script tho.

**Comment by nkast** [comment]
ok, looks like it's working.

**Comment by cra0zy** [comment]
@nkast You've got ~~mail!~~ merge conflicts!

**Comment by nkast** [comment]
Note: IWindowInfo is used only by SDL. other platforms (Android,iOS) ignore it. It was not possible to clean the code any further.
But i do like the idea of wrapping the context in IGraphicsContext in general, I think DX need to do that too. (actual I had a PR to do that some years ago)

**Comment by nkast** [comment]
also also ... github's online merge conflict tool did not like whitespaces.

**Comment by nkast** [comment]
Never let webbrowser do WinMerge's job

**Comment by Jjagg** [comment]
This is good to go now, right?

**Comment by nkast** [comment]
Yes, it good to go.

**Comment by Jjagg** [comment]
Thanks @nkast!

**Pull request merged**
