### PR TITLE
Fix 6424, do not swap color channels for BGR image formats

### PR DESCRIPTION
**Pull request by roy-t**
This fixes issue https://github.com/MonoGame/MonoGame/issues/6424

I've changed the importing of both `FIT_RGB16` and `FIT_RGBF` images to respect that in this case the red and blue color channels are already in the correct order. 

I've based the correct order on the FreeImage source code, extensive tests with PNG images, and the fact that `FIT_RGBA16` and `FIT_RGBAF` images were already imported without the color channel swapping.

This PR includes tests for 24, 32, 48, and 64 bit PNG images to verify that both BGR and RGB images are imported correctly.

Unfortunately I couldn't add a test case for 96 and 128 bit floating point images. It seems FreeImage.net is not able to read or save 96/128bit TIFFs and PPM. It could also not load these images when they are created with ImageMagick or ShaderMap4. It seems this is a know issue. (See the comments in the `ImportImageWithBadContent` test).

_By submitting this PR I agree to distribute this work under the MonoGame license and copyright._

### CODE REVIEW

**Comment by Jjagg** [comment]
This is great @roy-t! Thanks! It seems the build not didn't run, but if it passes this is good to go :) 

@tomspilman Seems like build bot issues.

**Comment by CartBlanche** [comment]
Love it!! It has been a while since I've looked at an MG PR. Great to see one of this quality.

**Comment by roy-t** [comment]
@Jjag anything I can do to trigger a build? 

Thanks for the kind words everyone 😁

**Comment by Jjagg** [comment]
@roy-t Nope, nothing you can do! Build bots are down apparently.

**Comment by Jjagg** [comment]
Thanks @roy-t! Merging :)

**Pull request merged**
