### PR TITLE
Implement GraphicsAdapter.QueryRenderTargetFormat()

### PR DESCRIPTION
**Pull request by nkast**
Fallback of unsuported and profile depended SurfaceFormat. (Dxt, Single, drBlendable, ...)

Not implemeneted: 
Optional/Device depended formats. (566, 4444, ...)
Depth Formats.
MultiSampleCount.

### CODE REVIEW

**Comment by dellis1972** [comment]
This works on GL based systems too right?

**Comment by nkast** [comment]
Yes, this works on all platforms in a way compatible with XNA. So far I doesn't depend on the device.

After it's merged we can use it to fix #6036 and also pass the tests of https://github.com/MonoGame/MonoGame/pull/5451/commits/b26f9270aa21745576ac8f0ab0d5c0fee33476b9.

**Comment by nkast** [comment]
If we are going to use this QueryRenderTargetFormat() in the RenderTarget/Texture construction it will change the behavior depending on the Profile.  For example, `HdrBlendable` will become `Color` under `Reach` profile. I think I should move some of this code in #5451.

The way this is going work on the Texture construction:  
```
bool isSupported = device.adapter.QueryRenderTargetFormat(device.Profile, prefferedSurfaceFormat, out surfaceFormat);
if(!isSupported)
{
if(this is IRenderTarget)
 surfaceFormat = prefferedSurfaceFormat;
else
 throw new Exception(device.Profile + "does not support surface "+ prefferedSurfaceFormat);
}
```
That won't be a good error message because some formats (DXT, NormalizedByte2) are not supported as RenderTargets in any profile. 
So I think I will post a fix for #6036 that does not really on QueryRenderTargetFormat() but does some checks inline and throws a better error.

**Comment by nkast** [comment]
Ok, I have a new PR #6170 that deals with #6036 without the Profile fallback.

**Comment by nkast** [comment]
#6170 is merged. I moved the rest to #5451

**Pull request closed without merging**
