### PR TITLE
Flaky sound (some sounds don't play, are just skipped).

### PR DESCRIPTION
**Pull request by roponator**
#5418 

It seems as if the AL.Listener position is wrong. 

This bug can be reproduced if you just spam the audio code with dummy Debug.WriteLine("bla") calls.

Jake, if this fix doesn't work try uncommenting the calls that set velocity and orientation also.

### CODE REVIEW

**Comment by Jjagg** [comment]
@roponator You probably didn't mean to open this PR here. :p

**Comment by jakepoz** [comment]
Roponator is my friend and I asked him to look at this issue: https://github.com/MonoGame/MonoGame/issues/5387

Sadly, this doesn't fit the problem for me on Google Pixel. I'm also getting random crashes with my sample project, even if I comment out the proposed change. I'm not sure if this is some artifact or if the latest builds all have this problem. Will investigate and get back shortly.

```01-29 23:03:35.134 I/MonoDroid(30084): UNHANDLED EXCEPTION:
01-29 23:03:35.155 I/MonoDroid(30084): System.InvalidOperationException: Failed to set source pan. (Reason: Invalid Value)
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Audio.ALHelper.CheckError (System.String message, System.Object[] args) [0x00028] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Audio\OpenALSoundController.cs:52 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.PlatformPlay () [0x00104] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Audio\SoundEffectInstance.OpenAL.cs:145 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play () [0x00072] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Audio\SoundEffectInstance.cs:164 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Audio.SoundEffect.Play () [0x00015] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Audio\SoundEffect.cs:269 
01-29 23:03:35.155 I/MonoDroid(30084):   at MonoGameAndroidAudioTest.Game1.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x0006b] in C:\Users\jakep\Downloads\MonoGameAndroidAudioTest\MonoGameAndroidAudioTest\Game1.cs:99 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Game.DoUpdate (Microsoft.Xna.Framework.GameTime gameTime) [0x0001f] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Game.cs:656 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.Game.Tick () [0x00105] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Game.cs:465 
01-29 23:03:35.155 I/MonoDroid(30084):   at Microsoft.Xna.Framework.AndroidGameWindow.OnUpdateFrame (System.Object sender, OpenTK.FrameEventArgs frameEventArgs) [0x0006a] in C:\Users\jakep\Projects\MonoGame - PR\MonoGame.Framework\Android\AndroidGameWindow.cs:78 
01-29 23:03:35.155 I/MonoDroid(30084):   at OpenTK.GameViewBase.OnUpdateFrame (OpenTK.FrameEventArgs e) [0x00014] in /Users/builder/data/lanes/3511/501e63ce/source/opentk/Source/OpenTK/Platform/Android/GameViewBase.cs:312 
01-29 23:03:35.155 I/MonoDroid(30084):   at OpenTK.Platform.Android.AndroidGameView.UpdateFrameInternal (OpenTK.FrameEventArgs e) [0x00013] in /Users/builder/data/lanes/3511/501e63ce/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:348 
01-29 23:03:35.156 I/MonoDroid(30084):   at OpenTK.Platform.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x00096] in /Users/builder/data/lanes/3511/501e63ce/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:568 
01-29 23:03:35.156 I/MonoDroid(30084):   at OpenTK.Platform.Android.AndroidGameView+<StartThread>c__AnonStorey0.<>m__0 (System.Object _) [0x0000d] in /Users/builder/data/lanes/3511/501e63ce/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:458 
01-29 23:03:35.156 I/MonoDroid(30084):   at Android.App.SyncContext+<Send>c__AnonStorey1.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:32 
01-29 23:03:35.156 I/MonoDroid(30084):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
01-29 23:03:35.156 I/MonoDroid(30084):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
01-29 23:03:35.156 I/MonoDroid(30084):   at (wrapper dynamic-method) System.Object:8532a31d-18d8-4f6b-8d3d-56d0fee5e896 (intptr,intptr)
01-29 23:03:35.191 W/art     (30084): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
01-29 23:03:35.198 D/Mono    (30084): DllImport searching in: '__Internal' ('(null)').
01-29 23:03:35.198 D/Mono    (30084): Searching for 'java_interop_jnienv_throw'.
01-29 23:03:35.198 D/Mono    (30084): Probing 'java_interop_jnienv_throw'.
01-29 23:03:35.199 D/Mono    (30084): Found as 'java_interop_jnienv_throw'.

**Comment by jakepoz** [comment]
@roponator Hey, can you please send a prebuilt Monogame.Framework.dll with this change for Android so I can confirm a test here?

**Comment by jakepoz** [comment]
I was just able to check this pull request, it's very interesting. My test project works for me when I build in Release mode, but in Debug it still misses numbers. This is on a Google Pixel.

I was able to resolve the crashes on "Failed to set source pan." by doing a full rebuild of the project.

**Comment by roponator** [comment]
So I put in debug printing of all AL source and listener settings before sound gets played.

It correctly identified that position was not set before my current fix 
(Position: (0.1, 7.561471E+28, 1.401298E-45)).

So I assume there may be some other corrupt  values, so if you  can check it out and when it fails to play a sound go through logs to see if you have any corrupt values.

**Comment by jakepoz** [comment]
There is still something really strange going on:

```
[0:] ------------------------------------------------------------
[0:] NEW SOUND---------------------------------------------------
[0:] ------------------------------------------------------------
[0:] Listener -- 
[0:] Gain: 1
[0:] EfxMetersPerUnit: 1
01-31 15:26:09.046 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.046 D/Mono    (18696): Searching for 'alGetListener3f'.
[0:] Position: (0, -271.1943, -271.1929)
[0:] Velocity: (0, 0, 0)
[0:] Source -- 
01-31 15:26:09.055 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.055 D/Mono    (18696): Searching for 'alGetSourcei'.
[0:] Buffer: 33
[0:] SourceState: 4113
[0:] BuffersQueued: 1
[0:] BuffersProcessed: 0
[0:] SampleOffset: 0
[0:] ByteOffset: 0
[0:] SourceType: 4136
01-31 15:26:09.067 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.067 D/Mono    (18696): Searching for 'alGetSource3f'.
[0:] Position: (0.1, 1.943244, 2.858716E-21)
[0:] Direction: (0, 0, 0)
[0:] Velocity: (0, 0, 0)
[0:] SourceRelative: False
[0:] Looping: False
[0:] EfxDirectFilterGainHighFrequencyAuto: True
[0:] EfxAuxiliarySendFilterGainAuto: True
[0:] EfxAuxiliarySendFilterGainHighFrequencyAuto: True
01-31 15:26:09.084 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.084 D/Mono    (18696): Searching for 'alGetSourcef'.
[0:] ConeInnerAngle: 360
[0:] ConeOuterAngle: 360
[0:] Pitch: 1
[0:] Gain: 1
[0:] MinGain: 0
[0:] MaxGain: 1
[0:] ReferenceDistance: 1
[0:] RolloffFactor: 1
[0:] ConeOuterGain: 0
[0:] MaxDistance: 3.402823E+38
[0:] SecOffset: 0
[0:] EfxAirAbsorptionFactor: 0
[0:] EfxRoomRolloffFactor: 0
[0:] EfxConeOuterGainHighFrequency: 1
01-31 15:26:09.108 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.108 D/Mono    (18696): Searching for 'alSourcePlay'.
01-31 15:26:09.953 D/Mono    (18696): DllImport searching in: 'openal32.dll' ('./libopenal32.so').
01-31 15:26:09.953 D/Mono    (18696): Searching for 'alGetString'.
```

At the end of it, I get a crash as follows:
```Unhandled Exception:
System.InvalidOperationException: Failed to bind buffer to source. (Reason: Invalid Value)
```

It's clear that even the position variable is corrupted somehow, even though its being reset to zeros right before.

**Comment by roponator** [comment]
After some more digging this is what is causing the problem: the issues is passing C# paramters to C++ (from the OpenTK C# library to the OpenAL C++ lib).

The signature for the C++ function, which is called from C#, is like this:

void foo(int, float, float ,float).

What happens is that only the int and the first of the three floats get passed in correctly, the last two floats are corrupted. I have not been able to find out the reason why (tried all calling conventions, ... nothing works).

The funny thing is if we have a function signature like void foo(int, int, int ,int) all parameters are passed correctly, as if only floats passed by value get corrupted.

I then changed the function signature to foo(int, float*, float*, float*) and the c# one to foo(int, ref float, ref float, ref float) and it started working. So it seems as if passing multiple floats by value corrupts them on certain phone, but passing by reference works.

Right now I'm gonna try digging between the C# OpenTK interop call and the C++ code (if that is even possible) to try and find out what is the problem.

If I'm unable to find it, the solution seems to be to replace or pass-by-values with references/pointers.

**Comment by jakepoz** [comment]
@roponator Have you seen the changes by @dellis1972 in this pull request?

https://github.com/MonoGame/MonoGame/pull/5410

I was just doing some research and it sounds like we should just get rid of OpenTK once and for all?

**Comment by Jjagg** [comment]
Yes, OpenTK is getting dropped in favor of direct OpenGL/GL ES bindings. DesktopGL is now using SDL, it's only mobile that still needs to make the switch (and MonoMac needs to be dropped).

**Comment by roponator** [comment]
@Jjagg any eta when it's gonna be merged with master?

**Comment by Jjagg** [comment]
It needs a lot of testing and most likely some bugfixing, so not sure.

**Comment by jakepoz** [comment]
@Jjagg ok, we can start testing it here we have a large codebase of published Android games we can verify against.

**Comment by dellis1972** [comment]
@Jjagg turns out of we want to support the embedding route on Mac we need the native Mac bits. As SDL 2 does not support embedding.

**Comment by Jjagg** [comment]
> ok, we can start testing it here we have a large codebase of published Android games we can verify against.

Please do! We could use the help :)

> turns out of we want to support the embedding route on Mac

Oh, that makes sense. We should still drop MonoMac in favor of Xamarin.Mac though, right?

**Comment by jakepoz** [comment]
I assume we are closing this until OpenTK is nicely removed yes?

**Comment by roponator** [comment]
Yes, the real issues is still a mystery, would most likely have to compile Mono/Xamarin. 

The workaround we did was to modify the OpenTK library: we replaced the calls to the C++ lib in OpenTK that has more than on float parameters passed by value with a function that passes a pointer to a float array. This fixes the issues of corrupt floats. 

In case anyone wants to use this fix, clone this repo, build the OpenTKA.dll and use that on instead as a reference in your project.
https://github.com/roponator/opentk/tree/flaky_android_sound_fix
(use the flaky_android_sound_fix branch).

**Comment by dellis1972** [comment]
@roponator you know the Android OpenTK is up on mono/OpenTK. You can probably put a PR up there and I'm sure they will happily accept it. I work on the Xamarin.Android team so I will be happy to point the right guy to the PR once its up :)

**Comment by roponator** [comment]
@dellis1972 nice :)

Opened the PR there: https://github.com/mono/opentk/pull/15

**Pull request closed without merging**
