### PR TITLE
[XAudio] bugfix: read adpcm blockAlign as int16

### PR DESCRIPTION
**Pull request by nkast**
https://msdn.microsoft.com/en-us/library/windows/desktop/dd757713(v=vs.85).aspx

https://github.com/MonoGame/MonoGame/blob/3713daf5e632395a1837f681e2d56299eb0e99b4/MonoGame.Framework/Content/ContentReaders/SoundEffectReader.cs#L24-L33

### CODE REVIEW

**Comment by nkast** [comment]
Still this didn't fix the problem with adpcm sounds. 
The pipeline always write blockAlign=0 in XNBs and sharpdx fails at https://github.com/MonoGame/MonoGame/blob/13209fb0fcf7adeabd6a1317ffd695143764a7d2/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L287
https://github.com/MonoGame/MonoGame/issues/4446

Probably we have to peak the blockalign from the generated file header from ffmpeg.
@KonajuGames ?

**Comment by nkast** [comment]
For WUP apps, the SourceVoice seems to cast the value back to int16 and throws an exception. Sometimes I got dividebyZero instead of SharpDXException. 
for Desktop app it looked like SharpDX/XAudio2 was happy what whatever crazy value (0x00040000) we got. Now the desktop pltform fails as well with same error.

**Comment by KonajuGames** [comment]
This is interesting that XAudio2 uses a customized version of ADPCM.
https://msdn.microsoft.com/en-us/library/windows/desktop/ee415711(v=vs.85).aspx

Looking at [other sources](https://github.com/naudio/NAudio/blob/master/NAudio/Wave/WaveFormats/AdpcmWaveFormat.cs), the blockAlign field should be the same as the SamplesPerBlock in that linked documentation.

**Comment by tomspilman** [comment]
Thanks @nkast ...  even if this doesn't fix your current bug, this was a bug.  Block alignment is 2 bytes in a WAVE header.

**Pull request merged**
