### PR TITLE
Removed explicit global usings

### PR DESCRIPTION
**Pull request by vpenades**
From #7848

Removed explicit global usings to let developers choose whether to use them or not, and prevent type collisions with third party libraries.

Motivation: Developers should be able to choose when and how Global Usings are defined, and not set explicitly by the library. 

Usings management is a key feature required to prevent type collisions when using third party libraries that have types with the same names. (Color, Vector3, Matrix, Rectangle, Curve, Plane, Point, Ray, etc)

Setting global usings explicitly forces developers to fully qualify the names of the types of the third party libraries project wide. Or disable global usings completely, which cannot be disabled selectively on explicit monogame globals.

### CODE REVIEW

**Comment by mrhelmut** [comment]
Thanks! This is welcome. Would you mind also updating the templates? They make heavy use of implicit usings and have ```ImplicitUsings``` enabled in their csproj as well.

**Comment by vpenades** [comment]
@mrhelmut sure, I can copy the global usings to the csprojs of the templates

**Comment by mrhelmut** [comment]
Either this, or removing them entirely. Up to you, both work. I don't have an opinion on which is best for newcomers.

**Comment by vpenades** [comment]
> Either this, or removing them entirely. Up to you, both work. I don't have an opinion on which is best for newcomers.

I think templates are going to be used to newcomers, so it's not a bad idea to make it easy for them with the global usings

But as they progress, they should have the ability to edit/remove global usings if they require it

**Comment by mrhelmut** [comment]
Your call! I'll double-down on it.

**Comment by harry-cpp** [comment]
The Using directives are only used if `ImplicitUsings` tag is set to true, you can also modify which usings can included with it in the .csproj, so don't remove the lines in the .targets file.

The templates have `ImplicitUsings` set to true, I thought it would be nicer for new users.

**Comment by vpenades** [comment]
> 

I use global using in my projects, but I use them for other libraries, not for MonoGame.

If the solution is to disable _all_ global usings, then it prevents developers to use global usings the way they want.

Making it easy for newcomers is not a bad idea, it's just that the global usings should go in the templates, not in the nugets. Making it easy for newcomers must not come at the cost of making it more difficult for advanced developers

**Comment by harry-cpp** [comment]
> If the solution is to disable _all_ global usings, then it prevents developers to use global usings the way they want.

You have `Using Remove=` if you want to not include specific implicit usings that come with nugets.

**Comment by vpenades** [comment]
@harry-cpp From my perspective, templates are going to be used mostly by newcomers, so it makes sense that all helping bits go into the templates.

Experienced users might reference nugets directly, from visual studio nuget package manager, or directly editing the csproj. Usually into projects that combine other dependencies.

When I added the new nuget packages to some of the projects and help libraries I have, I got conflicts with:

OpenCVSharp
MathNet.Numerics
BepuPhysics
System.Numerics.Vectors
System.Drawing.Common
System.Drawing.Primitives
SkiaSharp
WPF's System.Windows.Imaging
SixLabors.ImageSharp
MAUI

(most imaging libraries have their own Color, Point and Rectangle types)

So I have to add the "Remove=" on all the projects where I have monogame and any of these libraries.

Back to helping newcomers, in order to build a new complete project, you rarely use MonoGame _alone_ , so the moment a newcomer references one of the aforementioned libraries, it's probably easier for him to figure out that he has to remove the global using in _his_ csproj.... than to figure out the global usings are hidden in the nuget package, and he has to apply a "Remove=" because he cannot edit the targets in the nuget.

Personally, I believe having the global usings in the templates is the best of both worlds, so I leave this PR here to choose whether to merge it or not.

**Comment by mrhelmut** [comment]
From my perspective, I'm thinking about "customer support", and I personally wouldn't want to have to explain this every time someone drops by with a type collision (because who read the documentation these days?) arguing that MonoGame doesn't work.

I'd vouch for removing global usings entirely from both the targets and the templates. As convenient as they are, the support cost implied is too high.

**Comment by harry-cpp** [comment]
Maybe we make a seperate nuget `MonoGame.ImplicitUsings` for quick implicit usings?

@mrhelmut I don't have any strong feelings for one way over the other, leaving it up to you on what we should do.

**Comment by vpenades** [comment]
I'll be awaiting for the decision, let me know if I leave the PR as is, or I remove the global usings, and re-introduce standard usings into the templates.

**Comment by mrhelmut** [comment]
> I'll be awaiting for the decision, let me know if I leave the PR as is, or I remove the global usings, and re-introduce standard usings into the templates.

If that's not too much asking, I'd like to validate the removal of global usings and restoring usings in the templates.

**Comment by mrhelmut** [comment]
Ah, while you're at it, would you mind changing ```Microsoft.NET.Sdk.WindowsDesktop``` to ```Microsoft.NET.Sdk``` in the DirectX template?

**Comment by vpenades** [comment]
> Ah, while you're at it, would you mind changing `Microsoft.NET.Sdk.WindowsDesktop` to `Microsoft.NET.Sdk` in the DirectX template?

What about a new PR that fixes that, and also adds the Embedded sources to the PDB?

**Comment by mrhelmut** [comment]
> Embedded sources to the PDB

I'm ok with this being in another PR, though I'd like the template fix to be merged quickly to publish a 3.8.1 hotfix.
The embedded source can likely wait 3.8.2.

**Comment by vpenades** [comment]
> > Embedded sources to the PDB
> 
> I'm ok with this being in another PR, though I'd like the template fix to be merged quickly to publish a 3.8.1 hotfix. The embedded source can likely wait 3.8.2 (this needs a bit more testing).

I've also noticed WindowsUniversal uses Windows.SDK.Extras instead of Microsoft.NET.Sdk ... should I change that one too?  I think extras is no longer needed.

**Comment by vpenades** [comment]
I've pushed the Windows.NET.Sdk change a moment ago.... I've left the SDK.Extras out because I think it needs further investigation

**Comment by mrhelmut** [comment]
> > > Embedded sources to the PDB
> > 
> > 
> > I'm ok with this being in another PR, though I'd like the template fix to be merged quickly to publish a 3.8.1 hotfix. The embedded source can likely wait 3.8.2 (this needs a bit more testing).
> 
> I've also noticed WindowsUniversal uses Windows.SDK.Extras instead of Microsoft.NET.Sdk ... should I change that one too? I think extras is no longer needed.

Sorry, I meant from the templates, not the library projects (I would feel safer to not change that for ConsoleCheck and UWP libraries for the time being).

**Comment by vpenades** [comment]
I've been following the evolution of the SDKs, and that's more or less the history:

1- In NetCore3.1 if you wanted a project to use WindowsForms or WPF, you used `Windows.NET.Sdk.WindowsDesktop`

2- When Net5.0 was introduced, `.WindowsDesktop` was no longer needed, and in order to use WindowsForms or WPF you just use `<UseWindowsForms>true</UseWindowsForms>` or `<UseWPF>true</UseWPF>`

All this is explained here:  https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/sdk-and-target-framework-change

So as I understand it, .WindowsDesktop has been deprecated and is no longer needed.

**Comment by mrhelmut** [comment]
This I understand, I'd just like to avoid doing too many things (and touching more than the templates) in the PR but I concede that I did bring the topic first. Up to you but please test the libraries if they run and not just build.

We really need to get rid of the global usings in the templates, some of them simply don't build at all even on empty projects.

**Comment by vpenades** [comment]
> This I understand, I'd just like to avoid doing too many things (and touching more than the templates) in the PR but I concede that I did bring the topic first. Up to you but please test the libraries if they run and not just build.
> 
> We really need to get rid of the global usings in the templates, some of them simply don't build at all even on empty projects.

OK, I'm going to revert the SDK changes and focus on fixing the global using issues on the templates ASAP... I'll leave the SDK changes for another PR for later today

**Comment by vpenades** [comment]
So far, all the templates compile for me.
I was also able to run the desktop/UWP templates
I couldn't test the iOS one because I don't have the hardware.

In order to compile and run the templates directly I had to do these local changes (NOT in the PR):
- uninstall mgcb global tools from 3.8.0
- remove linux and mac packages from the dotnet-tools.json, because it complains about not being able to install them
- restore, exit visual studio, and compile again (this is not related to monogame, from time to time it happens with our own tools too)

**Comment by mrhelmut** [comment]
Would you mind removing the ```<ImplicitUsings>true</ImplicitUsings>``` lines from the template csproj as well? We'll be good after that!

**Comment by vpenades** [comment]
> Would you mind removing the `<ImplicitUsings>true</ImplicitUsings>` lines from the template csproj as well? We'll be good after that!

done

**Comment by mrhelmut** [comment]
Great, thanks!

**Pull request merged**
