### PR TITLE
System.Drawing does not exist on android

### PR DESCRIPTION
**Pull request by cobalthex**
Not sure why this ever worked

### CODE REVIEW

**Comment by mrhelmut** [comment]
```Mono.Android``` and ```Mono.iOS``` implement a few of the ```System.Drawing``` features, such as basic types like ```Point```.

This proposed change is actually a breaking change because it is part of the public API. If games use the ```View``` service (```Game.Services.GetSevice(typeof(View))```), which is very likely on Android, the expected type for ```Size``` would change.

Beside harmonizing types within the codebase, would there be any other motivation?

**Comment by mrhelmut** [comment]
Building the repository should just take a ```dotnet cake``` from the repository's folder. Though building Android individually with ```dotnet build ./MonoGame.Framework/MonoGame.Framework.Android.csproj``` should just work too.

Make sure that you have the Android workload installed (```dotnet workload install android```).

**Comment by cobalthex** [comment]
building android was fine, but when trying to use 3.8.0 (public release) on a netcore6-android project, I got an assembly load failure for System.Drawing.Core v4.0.0

**Comment by mrhelmut** [comment]
3.8.0 is not compatible with ```net6-android``` targets, it requires the "Xamarin" style of projects (likely Xamarin.Android 11 with VS 2019).

3.8.1 supports ```net6-android``` only.

**Comment by cobalthex** [comment]
fyi, this code still exists in 3.8.1

**Comment by mrhelmut** [comment]
> `Mono.Android` and `Mono.iOS` implement a few of the `System.Drawing` features, such as basic types like `Point`.
> 
> This proposed change is actually a breaking change because it is part of the public API. If games use the `View` service (`Game.Services.GetSevice(typeof(View))`), which is very likely on Android, the expected type for `Size` would change.
> 
> Beside harmonizing types within the codebase, would there be any other motivation?

Since it breaks the virtual property inherited from ```SurfaceView```, I don't think this is desired change.

You issue likely comes from somewhere else.

**Pull request closed without merging**
