### PR TITLE
[Pipeline Tool] Updated Icons

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
 - updates all icons in the Pipeline Tool with VS 2015 icons
 - adds icons for some menu stuff (Rename, Delete, Open Item, etc.)
 - Windows and Mac are using bundled icons, Linux is loading icons from the system icon theme

Screenshot:
piptool

### CODE REVIEW

**Comment by cra0zy** [comment]
@tomspilman I think something is wrong with the build server.

**Comment by tomspilman** [comment]
Yea...  it is an audio issue with the build server. I'll have it fixed later tonight.

**Comment by tomspilman** [comment]
Ok... things should be fixed now.  I'm re-running the tests.

One of the guys in my office was looking for speakers, saw some on a server and thought it wasn't important and snatched them.  I'm labeling them now to keep it from happening again.

**Comment by tomspilman** [comment]
Thanks @cra0zy ... this looks great.  Merging!

**Pull request merged**
