### PR TITLE
[Pipeline Tool] General Improvements

### LINKED ISSUE #5210: Improve References display in Pipeline tool
Originally mentioned in https://github.com/MonoGame/MonoGame/issues/4457.

image

The 'Collection' text here is completely unhelpful to the user.

 - The 'References' property value should show a  ;  separated string of assembly names.

This makes it more similar to how VS shows lists of files/folders/macros:

image

image

The display could just be the assembly names and not the full path in order to show the most useful information.  The content could be read only and require the use of the editor to make changes to it.

### LINKED ISSUE #5211: Remove/Rename 'Pads' Menu in Pipeline Tool
We should remove or rename the 'Pads' menu item from the Pipeline Tool:

image

It is a duplication of information already available in other areas so it would be fine to remove it.

If we want to keep it we should name it "View" which is more common name for options relating to the different display panels within an application.

### LINKED ISSUE #5215: Pipeline Tool TextureProcessor.ColorKeyColor Broken
It seems like the `TextureProcessor.ColorKeyColor` is broken in the Pipeline Tool.

image

When i open the editor it looks like this:

image

Looking at the code the default is clearly not `#00000000`:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs#L23

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
 - Better reference editor, fixes #5210
 - Renamed "Pads" menu to "View" menu, fixes #5211 
 - Fix default value of properties, fixes #5215

### CODE REVIEW

**Comment by tomspilman** [comment]
I looks pretty good, but it seems the text size estimate is a little off on Windows:

image

See how the bottom of the `P`s are cut off?

**Comment by cra0zy** [comment]
Actually all the text is shifted a bit down, there is probably an error in Eto.Forms font line height calculations on Windows.

**Comment by cra0zy** [comment]
Yup, I was right: #574

**Comment by nkast** [comment]
@cra0zy 

Can we make error messages red? I think it looked good.
pipelineparserexception

**Comment by cra0zy** [comment]
> Can we make error messages red? I think it looked good.

There is no easy way to do it AFAIK.

**Comment by nkast** [comment]
Ok. Cool. 

Also, Do we need to prefix filenames with "Building ", "Cleaning ", etc?
The filtered view feels interactive with the icons representing the current state (processing, failed, succeed). The icons are more that enough IMO.

**Comment by tomspilman** [comment]
@cra0zy -  I guess we can merge this as is and hope ETO is fixed in the future?

**Comment by cra0zy** [comment]
> Also, Do we need to prefix filenames with "Building ", "Cleaning ", etc?

We do, for people who are running the tool for the first time that text is more useful than trying to guess what is happening from the icon.

> @cra0zy - I guess we can merge this as is and hope ETO is fixed in the future?

Yes, I'll try to do the fix for Eto Forms tomorrow.

**Comment by cra0zy** [comment]
Good news, finally had some free time so I got the bug fixed: https://github.com/picoe/Eto/pull/581

**Comment by cra0zy** [comment]
This should be good for merging now.

**Pull request merged**
