### PR TITLE
Updated SDK versions in universal project and universal templates

### LINKED ISSUE #7220: Update MonoGame UWP SDK target
On Visual Studio 2019, Windows SDK 18362 is the default that is installed by the Visual Studio Installer. MonoGame is still targeting Windows SDK 17763 though... Is there any specific reason for that?

image

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1365

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsUWP

### PR DESCRIPTION
**Pull request by BMarques**
Update both the csproj for the Universal project and the templates. Fixes #7220.

### CODE REVIEW

**Comment by BMarques** [comment]
Thanks

**Comment by mrhelmut** [comment]
Could you please also set ```TargetPlatformMinVersion``` to ```10.0.16299.0``` (Windows 10 build 1709)? It is the most compatible and safest while still covering 98.3% of the Win 10 install base.

**Comment by BMarques** [comment]
@mrhelmut Yes, I'll do so later today.

**Comment by BMarques** [comment]
I was wondering if it would be a good idea to update the **Microsoft.NETCore.UniversalWindowsPlatform** nuget package from 6.2.9 to 6.2.10?

In advance, I tried but it's blocked by project
image

It's not very clear what I need to update to get the newest version, since it should work with both minimum and target versions I've set on the project...

**Comment by Jjagg** [comment]
Thanks @BMarques!

**Pull request merged**
