### PR TITLE
Update NuGet packages

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
 - Fixed author, owner, copyright, description, summary and licenseUrl properties
 - Included .targets file for each platform to supply MonoGamePlatform property
 - Removed readme.txt file
 - Some code formating (my text editor had done it automatically... forgot to disable it...)

### CODE REVIEW

**Comment by DDReaper** [comment]
Woah @cra0zy  Why have you removed the readme?
It's simply good practice with NuGet to provide starting documentation with any package.

I believe there was a separate thread to UPDATE the info, not remove it completely?

**Comment by cra0zy** [comment]
> It's simply good practice with NuGet to provide starting documentation with any package.

Who does that? MonoGame is the only NuGet package that I know of that does it... :/

That being said I am fine with providing a link to the documentation in the description, but using a readme.txt seems very ugly to me.

> I believe there was a separate thread to UPDATE the info, not remove it completely?

Let's see what README offered:
 - Description - NuGet package description already offered you that
 - Supported platforms - Useless info for the NuGet package
 - Installation instructions - I think people already know how NuGet functions...
 - Using Content Pipeline - This is the only part of readme that I would actually keep but...
   - It's unrelated to the actual NuGet package
   - 1/3 of it is already automated
   - Actually putting this info inside MGCB NuGet package would make a lot more sense
 - Release notes - Useless info for the NuGet readme, there is a position in the NuGet package where we could add release notes if we wanted.
 - Known issues - Is it ever gonna be anything but None?

Smaller side note, I am waiting for #5548 to be merged so I can fix #5528 (mostly rebase and resolve ffmpeg conflict) and wait for that to be merged, so I can submit MonoGame.Framework.Content.Pipeline and MGCB NuGet packages.

**Comment by tomspilman** [comment]
> It's simply good practice with NuGet to provide starting documentation with any package.

I'd rather see us keep our NuGet packages simple and redirect people to our actual documentation for details.  Adding something to this affect to the `<description>` tag wouldn't be a bad idea.

**Comment by cra0zy** [comment]
@tomspilman Can this PR get merged? Are there any changes that you want me to make? Want me to add a link to somewhere in the package description for documentation?

**Comment by DDReaper** [comment]
Sorry, just logging in to TeamCity and testing the NuGet's now.

**Comment by DDReaper** [comment]
This needs rebasing with the latest changes as the DesktopGL NuSpec are not in this commit.

Also not sure about all the .Targets references but I've built a few manually (as it's been a while and they aren't on the NuGet dev box anymore) and they build fine.

Also, changing MonoGameTeam -> MonoGame Team ??

Can you either rebase or resubmit this against the the latest develop branch @cra0zy

**Comment by cra0zy** [comment]
Need sleep, quick answers.

> This needs rebasing with the latest changes as the DesktopGL NuSpec are not in this commit.

It did not need rebasing because no merge conflicts.

> Also not sure about all the .Targets references but I've built a few manually (as it's been a while and they aren't on the NuGet dev box anymore) and they build fine.

Needed so that we don't keep the platform in .csproj, especially important if we want to provide MGCB nuget or rename platforms.

> Also, changing MonoGameTeam -> MonoGame Team ??

MonoGameTeam is not a word...

> Can you either rebase or resubmit this against the the latest develop branch @cra0zy

Rebased.

**Comment by cra0zy** [comment]
Something is really messed up with github, its pushed but its not updating this PR... moving to #5714

**Pull request closed without merging**
