### PR TITLE
MonoGame Gtk Platform

### PR DESCRIPTION
**Pull request by harry-cpp**
Gtk is a GUI toolkit, most commonly used on Linux, however it works on Windows and Mac as well.

This PR provides support for MonoGame to use Gtk GLArea widget for drawing.

Notes:
- This does not use SDL, but does use the rest of DesktopGL backend

Try templates:
```
dotnet new -i MonoGame.Template.Gtk.CSharp

dotnet new mggtk
dotnet run
```

### CODE REVIEW

**Comment by mrhelmut** [comment]
How is this different from DesktopGL? Would this allow to use Gtk widgets on top of it to build cross-platform tools?

**Comment by cra0zy** [comment]
> How is this different from DesktopGL? Would this allow to use Gtk widgets on top of it to build cross-platform tools?

This is meant to be used for cross platform tools, this does provide an easy to use Gtk widget that can be embedded into a Gtk application, DesktopGL can't be embedded into Gtk properly.

**Comment by mrhelmut** [comment]
Sounds cool! I'll try this out, thanks!

**Comment by cra0zy** [comment]
@mrhelmut if you really wanna try it out, message me on discord and I'll explain it to you how it works.

**Comment by sourceskyboxer** [comment]
Where is example? Please show me!

**Comment by pchan3** [comment]
I am also interested in this. May I have some documentation on how to use it?

**Comment by cra0zy** [comment]
@pchan3 Important question, do you want to try it from Linux or other OS?

**Comment by pchan3** [comment]
@cra0zy I'm running Ubuntu. I was hoping this would solve my issues for building tooling, I'd rather keep away from Windows.

**Comment by cra0zy** [comment]
Perfect, because right now this only works on Linux, anyway join MG Discoed server and we'll talk there: https://discord.gg/UmhhJHm

I'll be able to explain everything in about 3h.

**Comment by SimonDarksideJ** [comment]
Do you have a more up to date Discord link @cra0zy ? the last one has expired

**Comment by cra0zy** [comment]
Of course: https://discord.gg/ct7GQgW

For a moment there I was happy thinking someone wanted to use the Gtk version 😭

**Comment by harry-cpp** [comment]
Gonna close the PR, but I'll continue maintaining this on my fork.

**Pull request closed without merging**
