### PR TITLE
Remove Windows 8.1 and Windows Phone 8.1 support

### PR DESCRIPTION
**Pull request by Jjagg**
As per #5807 :) 

I checked installers, NuGets, templates and Protobuild files and removed files that are not used by other platforms. I still need to check preprocessor directives. Anything else?

### CODE REVIEW

**Comment by Jjagg** [comment]
This is really fun to do :D

**Comment by Jjagg** [comment]
> [08:44:57][NAnt output] Target 'build_windows8' does not exist in this project.

@tomspilman The NAnt script on the build bot should be updated to not build (or do anything else) with the Win8/WP projects.

**Comment by Jjagg** [comment]
I guess open issues related to WP/Win 8/8.1 can be closed now with a comment saying they are not fixed, but platform support was dropped. Would be nice if someone with more knowledge of the Windows ecosystem can confirm that these are no longer relevant. Maybe @DDReaper or @nkast? 

## Issues related to Windows Phone 8/8.1

#1051
#1352
#1396
#1487
#1646
#1692
#1970*
#2074*
#2076*
#2081
#2103*
#2231*
#2361
#2565*
#2612
#2774*
#2728*
#2976
#3048
#3172
#4402*
#4768
#5131*

## Issues related to Windows 8/8.1

#933
#1006*
#1039
#1360*
#1394
#1492
#1647
#2003
#2325
#3033
#3621
#3727

*: Possibly still relevant for UWP. Most of these are touch related. Possibly some of these are fixed by #5520

**Comment by DDReaper** [comment]
You beat me to it @Jjagg 
You know how much I love destroying platforms :P 

I'll see if I can start going through those issues tonight to check there is anything we need to be concerned about.

**Comment by DDReaper** [comment]
Most of those issues are over a year (most 2 years) old, so I think it's fair to close them as MG has moved on a lot since then.
A fair few have fix PR's against them but were not cleaned up.

@tomspilman / @KonajuGames , if you want to give me issue admin rights on Github, I'll go through and clean them up.

**Comment by cra0zy** [comment]
> @tomspilman / @KonajuGames , if you want to give me issue admin rights on Github, I'll go through and clean them up.

Actually you can't get only issue closing rights on GitHub, I know, I've asked a similar question several months ago :(

**Comment by KonajuGames** [comment]
Will be merged after 3.7 is out.

**Comment by nkast** [comment]
> Will be merged after 3.7 is out.

In that case, is it possible to review/merge the following PRs ?

#5613, fix for issue #5612. CoreApplication project stays forever in IsActive=false, gameloop freeze.
#5569, fix for issue #5555. Backbuffer is distorted when app starts with ClientWidth< ClientHeight.
#5815, MouseState might be corrupted doe to a race condition between game / input threads.
#5521, Upgrade path for W8.1 to move from SwapChainBackgroundPanel to SwapChainPanel.
#5615, Adds CoreApplication project targeting W10, something MG had for W8.1 but is missing  for W10. This will allow devs who used W8/CoreApplication projects to upgrade to W10 (if they chose to start from a fresh project).

**Comment by DDReaper** [comment]
> Will be merged after 3.7 is out.

Sorry to be brash @cra0zy but why?

After every release recently, MonoGame get's hit with crazy errors on some platforms and there is absolutely no reason to continue to support those platforms for 3.7.  Even MS is removing it now from their other OS releases.

like other platforms, if they still want Win 8.1 / WP8.1 support then users can stay on 3.6.  I personally see no value in keeping it on for another release.

UWP is still broken from 3.6 with hints at a point release and with Dream Build Play hitting our doors, users are still struggling getting new projects running on 2017, all fixed in source and dev releases (which is where I generally send them)

/Rant

**Comment by cra0zy** [comment]
> Sorry to be brash @cra0zy but why?

Wrong person there buddy :)

**Comment by DDReaper** [comment]
Darn it, sorry @cra0zy.

Same point / rant to you @konajugames

Why 3.7? This makes no sense.

**Comment by dellis1972** [comment]
@Jjagg do you have time to rebase this?

**Comment by Jjagg** [comment]
Yeah, will do

**Comment by DDReaper** [comment]
@Jjagg you still rebasing this PR, or if you've run out of time, do you want me to just resubmit it?

**Comment by Jjagg** [comment]
It's rebased, but the build fails because of `Target 'build_windows8' does not exist in this project`. I'm not sure where that's still coming from.

**Comment by tomspilman** [comment]
> but the build fails because of Target `build_windows8` does not exist in this project

That is set on the server.  For now leave the old `build_windows8` target, but leave it empty.

I will follow up with a PRs fixing this once and for all.

**Comment by DDReaper** [comment]
Go on @Jjagg , make my B'Day and try and get this read to merge today.
Had the same issue when I removed the base Win8.  Just add back in the Build target in the build headers. But leave off any actions.

**Comment by KakCAT** [comment]
probably unrelated to this PR (I don't know if the site webpage is also in github or not) but it'd would be nice to have in the monogame website's downloads section the list of each dying platform and the last release that supported it, just in case somebody needs to grab it.

**Comment by KonajuGames** [comment]
Pulling the trigger on this one.  Thanks @Jjagg

**Comment by DDReaper** [comment]
Now that this is merged @tomspilman @KonajuGames we do need to clean up the issues log of all the outstanding Win8/WP8 issues (like the ones mentioned in this PR)

**Comment by tomspilman** [comment]
@DDReaper - I'll go thru it now.

**Comment by tomspilman** [comment]
@Jjagg @DDReaper - Looks like we broke NuGet....

https://github.com/MonoGame/MonoGame/blob/develop/NuGetPackages/MonoGame.Framework.DX.nuspec

This still references the Windows 8/8.1 stuff.

**Comment by DDReaper** [comment]
If you can get that SharpDX PR merged, I'll get that sorted now

**Comment by DDReaper** [comment]
PR #5951 submitted to fix NuGet's

**Pull request merged**
