### PR TITLE
Performance: Using newer Environment.CurrentManagedThreadId for UI/Main thread check

### PR DESCRIPTION
**Pull request by MegaChuck64**
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1840

According to Microsoft, System.Environment.CurrentManagedThreadId is a 'compact and efficient replacement' to Thread.CurrentThread.ManagedThreadId.

 I've made this change in Platform/Threading.cs where the UI thread is checked.

### CODE REVIEW

**Comment by Mindfulplays** [comment]
Neat! Also, `MonoGameAndroidGameView` has a couple of references...

**Comment by MegaChuck64** [comment]
> Neat! Also, `MonoGameAndroidGameView` has a couple of references...

thanks, updated those!

**Comment by dellis1972** [comment]
@MegaChuck64 have you been able to test this on Android and DesktopGL? 
Also although it looks like this property is available for .NET Framework 4.5 can you confirm it works there? We need to be mindful of changes which might impact the console side of things.

**Comment by mrhelmut** [comment]
I don't see added value in this PR beside modernisation. To me, if it doesn't fix an existing issue, we should leave it be.

**Pull request closed without merging**
