### PR TITLE
Refactored AndroidGameActivity to allow custom Activity classes

### PR DESCRIPTION
**Pull request by vpenades**
Related to #7831 and #7191

AndroidGameActivity is hardcoded, which prevents a number of scenarios.

This PR makes the whole thing a bit more flexible allowing, with some work on the developer's side, to use a custom Activity.

Notice that this is critical to support new features available in modern android devices, because the recomended use case is to make the MainActivity to derive from `AndroidX.Core.App.ComponentActivity` or one of its derived classes.

### CODE REVIEW

**Comment by mrhelmut** [comment]
This is a welcome Android change. I'll review it once 3.8.1 is released.

**Comment by damian-666** [comment]
defintely , i was thinking aobut using android own text handing for input and it cloud translation service trouhg Java then integrating the MG graphicsin this way maybe docking it over or an an underlay.   I dont wanto to deal with Arabic and chinese and allthat on my own or use MG text if i can avoid it.  ill nest the graphics box somehow wiht the text box if thats possible with  this idea.    I was gonna wait out microfoft Maui but theres competing inhouse WPF-like mobile and UI solutions i wont even name because we dont know  longevity on any onf this..   so xamaarin might be around a bit..

**Comment by vpenades** [comment]
> This is a welcome Android change. I'll review it once 3.8.1 is released.

There's still a few things in the PR I don't like too much, like the static Pause/Resume events still being in the old class, but I can't see a way around it without further breaking compatibility with previous versions.

@mrhelmut anyway, I have some stuff I would preffer to discuss at Discord whenever you have some time.

**Comment by mrhelmut** [comment]
> @mrhelmut anyway, I have some stuff I would preffer to discuss at Discord whenever you have some time.

Feel free to send me a friend request (I might have my friend requests blocked, if that is the case, feel free to share your handle or to ping me on the discord, I'll send you a request in return).

**Pull request closed without merging**
