### PR TITLE
Calculate the Client Bounds a bit later.

### PR DESCRIPTION
**Pull request by dellis1972**
Fixes https://github.com/MonoGame/MonoGame/issues/5935

### CODE REVIEW

**Comment by mrhelmut** [comment]
Strangely, ```GameView.Width``` & ```Height``` are both 0 at this moment on my device.

**Comment by dellis1972** [comment]
@mrhelmut hmm. weird :( I wonder why that is. Which device is it? I might try to get a sample running in Test cloud.

**Comment by mrhelmut** [comment]
It's a cheap Qilive tablet running 4.4, but it also happens on Nexus 7 (2013, running 6.0).

```GameView.Width``` is 0 up until here (and it doesn't seem to help knowing why): https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Android/MonoGameAndroidGameView.cs#L321

It probably doesn't point to the real problem and the view initialization is probably hidden by the threads work.

**Comment by dellis1972** [comment]
@mrhelmut well the ClientBounds will get changed again when the SurfaceHolder is created in the SurfaceView. So I guess is will be 0,0 to start with and then gets changed later in the initialisation sequence. It does not seem to cause any problems for me.. but that said it might cause problems else where.

**Comment by mrhelmut** [comment]
I'll try to verify what's going on, right now this PR completely wrecks the rendering.

**Comment by dellis1972** [comment]
@mrhelmut I changed the way we do this.. This should be better now.

**Comment by Ragath** [comment]
fixes #5997

**Comment by mrhelmut** [comment]
Working fine! Thanks @dellis1972

**Comment by KonajuGames** [comment]
Are we supposed to get notifications from the review request that was done 4 days ago?

Merging.  Thanks @dellis1972

**Pull request merged**
