### PR TITLE
[2MGFX] Split ShaderInfo.

### PR DESCRIPTION
**Pull request by nkast**
I missed this one.
Related to #6108

### CODE REVIEW

**Comment by nkast** [comment]
There are still two tree nodes that depend on Monogame.
SamplerStateInfo creates and return a SamplerState.
PassInfo creates and return BlendState,RasterizerState and DepthStencilState.
We'd have to decouple those as well.

**Comment by Jjagg** [comment]
@tomspilman Looks like build bot issues again

**Comment by tomspilman** [comment]
@nkast @Jjagg - No this is something else now.

> /ThirdParty/Lidgren.Network/Lidgren.Network.iOS.csproj: error : /ThirdParty/Lidgren.Network/Lidgren.Network.iOS.csproj: Root element is missing.

@dellis1972 ???

**Comment by nkast** [comment]
@tomspilman , @Jjagg 
Can we get this merged?

**Comment by nkast** [comment]
Thanks!

**Pull request merged**
