### PR TITLE
[android] Fix Android Orientation

### PR DESCRIPTION
**Pull request by dellis1972**
The OrientationChanged Event was occuring too early. It was
happening BEFORE the change had occured as a result the
Viewport property was completely wrong and had the old values.

### CODE REVIEW

**Comment by dellis1972** [comment]
Sigh.. Kindle Fire works differently :( Don't merge yet.

**Comment by tomspilman** [comment]
> Sigh.. Kindle Fire works differently

Of course it does. :/

**Comment by tomspilman** [comment]
@dellis1972 - What is left on this one?

**Comment by KonajuGames** [comment]
@dellis1972, any progress on Kindle?

**Comment by dellis1972** [comment]
Nope, not had time to come back to this.. and I worked around it on the
project by NOT using the Orientation event

**Pull request closed without merging**
