### PR TITLE
Decouple Builder.Task from dotnet-mgcb

### PR DESCRIPTION
**Pull request by jnoyola**
## Summary

I know this change hasn't really been discussed, but I think it should be considered. It decouples `Builder.Task` from the `dotnet-mgcb` global tool and packs a copy of `mgcb` directly into `Builder.Task` (just as `Builder.Editor` already does). Now `dotnet-mgcb`, `Builder.Editor`, and `Builder.Task` each ship with their own copy of `mgcb`.

Now the Task is much simpler, and the dotnet global tool is still there if you want it.

**Cons:**
* `Builder.Task` doesn't automatically install the `dotnet-mgcb` tool for you if you wanted to run it manually
* Two copies of `mgcb` will be saved, taking up twice as much space (~300MB extra) if a user wants to use the Task _and_ the dotnet tool.

**Pros:**
* No version issues like #7150
* No potential issues from parsing `dotnet tool` output
* No .config folders strewn across your project when you don't want them
* Easier to understand and maintain targets file (look at how much was deleted from `MonoGame.Content.Builder.Task.targets`)
* Easier to work from source without needing to first publish the dotnet tool to a local NuGet source (see [sample below](https://github.com/MonoGame/MonoGame/pull/7169#issuecomment-635205749))

## Validation

* Tested building a game with `Builder.Task` and running the output with each of the following
  * WindowsDX
  * WindowsUniversal
  * DesktopGL
  * iOS
* Tested building a .mgcb file with each of the following dotnet local tools
  * `dotnet-mgcb`
  * `dotnet-mgcb-editor`

### CODE REVIEW

**Comment by tomspilman** [comment]
@Jjagg and @harry-cpp can make the call on this.  @mrhelmut may have an opinion too.

I personally never use the task, so don't really care either way.  

But I will say that if you are working from source it would be good that this still work correctly.

**Comment by jnoyola** [comment]
> But I will say that if you are working from source it would be good that this still work correctly.

That's a good point, and I think that's an additional benefit of this approach. If you decide to reference the projects from source, the previous approach would still try to install the dotnet tool from NuGet. With the new approach, you can reference everything locally like usual:

```xml
  <!-- Reference projects -->
  <ItemGroup>
    <ProjectReference Include="C:\path\to\MonoGame\MonoGame.Framework\MonoGame.Framework.DesktopGL.csproj" />
    <ProjectReference Include="C:\path\to\MonoGame\Tools\MonoGame.Content.Builder.Task\MonoGame.Content.Builder.Task.csproj" />
  </ItemGroup>

  <!-- Set properties -->
  <Import Project="C:\path\to\MonoGame\Tools\MonoGame.Content.Builder.Task\MonoGame.Content.Builder.Task.props" />
  <PropertyGroup>
    <MGCBPath>C:\path\to\MonoGame\Artifacts\MonoGame.Content.Builder.Task\$(Configuration)\netcoreapp3.1\mgcb.dll</MGCBPath>
  </PropertyGroup>

  <!-- Import targets -->
  <Import Project="C:\path\to\MonoGame\MonoGame.Framework\MonoGame.Framework.DesktopGL.targets" />
  <Import Project="C:\path\to\MonoGame\Tools\MonoGame.Content.Builder.Task\MonoGame.Content.Builder.Task.targets" />
```

**Comment by Jjagg** [comment]
I think the biggest downside is users will have to have the installation of a single version of mgcb on disk twice. But this is much much much less prone to bugs and easier to maintain, so I think we can make that trade-off.

**Comment by harry-cpp** [comment]
For now this solution might be better.

**Comment by tomspilman** [comment]
> have the installation of a single version of mgcb on disk twice.

MGCB is fat.... it is 95MB nupkg...  260MB unpacked.  Most of that is unused code in ffmpeg...

image

All the circled bits are ffmpeg overhead.

If we customized our ffmpeg build to just have the formats and support we need...  it could be much smaller i think.

That said...  do we care about 300MB when a crazy fast 2TB SSD is $300?

**Comment by jnoyola** [comment]
> users will have to have the installation of a single version of mgcb on disk twice

Absolutely. I actually intentionally left that off this list because I think I made the same argument on another PR or the original design and Tom made a similar argument about how we don’t need to worry so much about storage on dev machines :P But I’ll add it for completeness.

**Comment by Jjagg** [comment]
> I personally don’t see that many people talk about calling mgcb directly.

No, but people use mgcb-editor and that also includes mgcb.

**Comment by jnoyola** [comment]
> No, but people use mgcb-editor and that also includes mgcb.

If we had a good way to get the Task and mgcb-editor to share a copy of mgcb, then it _might_ be worth it, but they already don’t because we saw too many issues with it before.

**Comment by jnoyola** [comment]
[Here](https://community.monogame.net/t/problem-with-fbximporter-in-3-8-0-1375-develop-build/12777/4) is another issue that seems like it could be at least somewhat mitigated by this change.

The entire problem hasn't been identified yet, but part of the issue is that different parts of the command require different working directories.
* `dotnet` needs the working directory to be the project folder so it can find the tool manifest
* The MGCB tool itself needs the working directory to be the tool directory so Assimp can find it's DLLs.

**Comment by harry-cpp** [comment]
That would not get mitigated with this.

**Comment by jnoyola** [comment]
It would need another small change to actually fix the working directory, but I think the point is clear that there is another class of issues caused by differing requirements for working directory.

Are you simple pointing out that this PR doesn't actually change the working directory, or are you actually saying that that issue is unrelated?

**Comment by harry-cpp** [comment]
Changing the working directory is not a proper fix for that.

**Comment by jnoyola** [comment]
> Changing the working directory is not a proper fix for that.

No argument from me there, but that's why I only said mitigated and not really solved. I'm just trying to chisel down the surface area of where things might go wrong. 🙂

**Comment by harry-cpp** [comment]
I'm gonna merge this as there was no opposition. Thanks @jnoyola !

Random question, are you on MG discord server / do you use discord?

**Comment by jnoyola** [comment]
Thanks! Not sure if we want to mention in the 3.8 preview thread that the Task installation is changing and people should delete uninstall the tool and delete those .config folders if they intend to manually use the tool.

I do use discord but I'm not on the MG server yet. I'll check it out today!

**Pull request merged**
