### PR TITLE
Fix crash on game start on Android 8.1(or possiblly other android ver…

### PR DESCRIPTION
**Pull request by ryancheung**
…ions)

### CODE REVIEW

**Comment by tdeeb** [comment]
The MonoGame project doesn't use C# 6 features yet. You'll have to add an explicit null check. Ex:

```
if (OnResumeGameThread != null)
    OnResumeGameThread(this, EventArgs.Empty);
```

**Comment by ryancheung** [comment]
👌Thanks

**Comment by ryancheung** [comment]
It crashes when OpenAL not initialized on app launch,

**Comment by tdeeb** [comment]
Does this PR relate to a specific issue? What's the cause of the crash on Android 8.1?

**Comment by ryancheung** [comment]
> Does this PR relate to a specific issue filed? What's the cause of the crash on Android 8.1?

The callback `OnPauseGameThread` and `OnResumeGameThread` only get filled when OpenAL get initialized.
But in my test app, OpenAL is not initialized. It's a rare case but also possible that a game does not initialize OpenAL.

**Comment by tdeeb** [comment]
Are you on a build with this PR merged? https://github.com/MonoGame/MonoGame/pull/6629

**Comment by ryancheung** [comment]
Yes, I have commit 72919dc8185e70734507b58bd9a8e03bfe9a0d96

**Comment by mrhelmut** [comment]
This PR should work, I don't quite know what's failing here, some tests are getting ignored.

**Comment by ryancheung** [comment]
There’s already commit merged fixing this issue, I’m closing this PR

**Comment by Jjagg** [comment]
Sorry @ryancheung, I missed this PR. Thank you for the effort!

**Comment by ryancheung** [comment]
It’s fine, it’s just a little tiny PR haha

**Pull request closed without merging**
