### PR TITLE
VS 2017 Core Application Template (matching new 2015 version)

### PR DESCRIPTION
**Pull request by DDReaper**
Added a VS 2017 version of the new "Core Application" template for Windows 10.

Renamed and updated existing Win 10 XAML template to match 2015

### CODE REVIEW

**Comment by DDReaper** [comment]
Tested and working, over to you @tomspilman / @KonajuGames

**Comment by DDReaper** [comment]
Any update on this @tomspilman / @KonajuGames ?  This just brings the VS2015 CoreApplication template that was merged forward so we also have a 2017 template.

**Comment by KonajuGames** [comment]
Merging. Thanks @DDReaper

**Comment by DDReaper** [comment]
Thanks @KonajuGames :D

**Pull request merged**
