### PR TITLE
fix Texture.GetSharedHandle()

### LINKED ISSUE #7305: RenderTarget2D.GetSharedHandle();  null reference exception
After upgrading from 3.8.0.1375-develop to 3.8.0.1641, RenderTarget2D.GetSharedHandle(); throws a null reference exception.

It was working fine with the develop version.

#### What version of MonoGame does the bug occur on:
- MonoGame.Framework.WindowsDX 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

### PR DESCRIPTION
**Pull request by nkast**
fixes #7305

### CODE REVIEW

**Comment by tomspilman** [comment]
@nkast - Is there a unit test we could add that could detect this in the future?

**Comment by tomspilman** [comment]
Thanks @nkast !

**Comment by nkast** [comment]
let's see what works.

**Comment by nkast** [comment]
Ready to go.

**Comment by Jjagg** [comment]
Thanks @nkast!

**Pull request merged**
