### PR TITLE
[DX] MSAA RenderTarget GetData and SetData

### LINKED ISSUE #5834: Multisampled Texture2D.GetData() throws Invalid arguments exception
It seems multisampled textures will crash if you try to save a rendertarget as a png, for instance.

```
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments]
   ved SharpDX.Result.CheckError()
   ved SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   ved SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   ved Microsoft.Xna.Framework.Graphics.Texture2D.PlatformGetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:linje 138
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Int32 arraySlice, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 206
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 221
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 247
   ved MonoGame.Utilities.Png.PngWriter.GetColorData(Texture2D texture2D) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Utilities\Png\PngWriter.cs:linje 227
   ved MonoGame.Utilities.Png.PngWriter.Write(Texture2D texture2D, Stream outputStream) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Utilities\Png\PngWriter.cs:linje 36
   ved Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSaveAsPng(Stream stream, Int32 width, Int32 height) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:linje 311
   ved Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsPng(Stream stream, Int32 width, Int32 height) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 294

```

The exception is thrown here:

```
private void PlatformGetData<T>(int level, int arraySlice, Rectangle rect, T[] data, int startIndex, int elementCount) where T : struct
        {
            // Create a temp staging resource for copying the data.
            // 
            // TODO: We should probably be pooling these staging resources
            // and not creating a new one each time.
            //
            var min = _format.IsCompressedFormat() ? 4 : 1;
            var levelWidth = Math.Max(width >> level, min);
            var levelHeight = Math.Max(height >> level, min);

            if (_cachedStagingTexture == null)
            {
                var desc = new Texture2DDescription();
                desc.Width = levelWidth;
                desc.Height = levelHeight;
                desc.MipLevels = 1;
                desc.ArraySize = 1;
                desc.Format = SharpDXHelper.ToFormat(_format);
                desc.BindFlags = BindFlags.None;
                desc.CpuAccessFlags = CpuAccessFlags.Read;
                desc.SampleDescription = CreateSampleDescription();
                desc.Usage = ResourceUsage.Staging;
                desc.OptionFlags = ResourceOptionFlags.None;

                // Save sampling description.
                _sampleDescription = desc.SampleDescription;

                _cachedStagingTexture = new SharpDX.Direct3D11.Texture2D(GraphicsDevice._d3dDevice, desc); <- line that crashes
            }

```

http://community.monogame.net/t/multisampled-texture2d-saveaspng-crashes/9492

### PR DESCRIPTION
**Pull request by Jjagg**
With these changes GetData works on MSAA rendertargets.
Fixes #5834.

I made it so the resolved texture is stored in the `_texture` field and the MSAA texture is stored in the `_msTexture` field. That made more sense, since code interacting with the texture usually requires the resolved texture. Because of that change I could clean up the code some more, to make it easier to understand and more maintainable. I hope that's fine.

I also added a test that calls SetData and GetData. Note that SetData is done on the resolved texture as explained in https://github.com/MonoGame/MonoGame/issues/5834#issuecomment-317408529.

Minor other stuff (mostly related):
- Fixed visibility of protected members (made them internal)
- Improved initialization of `_sampleDescription` (it was all over the place)
- Made it so `MultiSampleCount` is the actual MS count on the texture, not what's passed as the preferred MS count (we should probably also do that for GL)
- Fixed XNA test compilation

### CODE REVIEW

**Comment by Jjagg** [comment]
Piranha crashes when building this. Stack trace:
```
[08:08:59][exec]         RemoveExternalTypesUsageProcessor: Started RemoveExternalTypesUsageProcessor.
[08:08:59][exec]             CollectTypesDependenciesProcessor: Started CollectTypesDependenciesProcessor.
[08:08:59][exec] 
[08:08:59][exec] Unhandled Exception: System.ArgumentNullException: Value cannot be null.
[08:08:59][exec] Parameter name: key
[08:08:59][exec]    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
[08:08:59][exec]    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
[08:08:59][exec]    at Ark.Piranha.CollectTypesDependenciesProcessor.AddDependency(TypeReference dependentTypeRef, TypeDependency dependingMember) in d:\Projects\Piranha2\Ark.Piranha\CollectTypesDependenciesProcessor.cs:line 161
[08:08:59][exec]    at Ark.Piranha.CollectTypesDependenciesProcessor.ProcessMethod(MethodDefinition methodDef) in d:\Projects\Piranha2\Ark.Piranha\CollectTypesDependenciesProcessor.cs:line 222
[08:08:59][exec]    at Ark.Linq.CollectionExtensions.ReversedForEach[TSource](IList`1 list, Action`1 action) in d:\Projects\Piranha2\Ark.Cecil\CollectionExtensions.cs:line 57
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessMethods(TypeDefinition typeDef, IList`1 methodDefs) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 159
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessType(TypeDefinition typeDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 127
[08:08:59][exec]    at Ark.Piranha.CollectTypesDependenciesProcessor.ProcessType(TypeDefinition typeDef) in d:\Projects\Piranha2\Ark.Piranha\CollectTypesDependenciesProcessor.cs:line 187
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessTypeAndNestedTypes(TypeDefinition typeDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 119
[08:08:59][exec]    at Ark.Linq.CollectionExtensions.ReversedForEach[TSource](IList`1 list, Action`1 action) in d:\Projects\Piranha2\Ark.Cecil\CollectionExtensions.cs:line 57
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessModuleTypes(ModuleDefinition moduleDef, IList`1 typeDefs) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 114
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessModule(ModuleDefinition moduleDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 81
[08:08:59][exec]    at Ark.Linq.CollectionExtensions.ReversedForEach[TSource](IList`1 list, Action`1 action) in d:\Projects\Piranha2\Ark.Cecil\CollectionExtensions.cs:line 57
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessModules(AssemblyDefinition assemblyDef, IList`1 moduleDefs) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 77
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 72
[08:08:59][exec]    at Ark.Piranha.CollectTypesDependenciesProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Piranha\CollectTypesDependenciesProcessor.cs:line 55
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 67
[08:08:59][exec]    at Ark.Piranha.RemoveExternalTypesUsageProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Piranha\RemoveExternalTypesUsageProcessor.cs:line 36
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 67
[08:08:59][exec]    at Ark.Piranha.RetargetAssemblyProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Piranha\RetargetAssemblyProcessor.cs:line 29
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 67
[08:08:59][exec]    at Ark.Piranha.MakePortableSkeletonProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Piranha\MakePortableSkeletonProcessor.cs:line 22
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 67
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessAssemblyFromFile(String inputFile, ReaderParameters readerParams, String outputFile, WriterParameters writerParams) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 22
[08:08:59][exec]    at Ark.Cecil.CecilProcessor.ProcessAssemblyFromFile(String inputFile, String outputFile) in d:\Projects\Piranha2\Ark.Cecil\CecilProcessor.cs:line 16
[08:08:59][exec]    at Piranha.MakePortableSkeletonCommand.Execute() in d:\Projects\Piranha2\Piranha\MakePortableSkeletonCommand.cs:line 12
[08:08:59][exec]    at Piranha.Program.<Main>b__0(String v, Object o) in d:\Projects\Piranha2\Piranha\Program.cs:line 21
[08:08:59][exec]    at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
[08:08:59][exec]    at Piranha.Program.Main(String[] args) in d:\Projects\Piranha2\Piranha\Program.cs:line 17
```

I think this is either a bug in Cecil or incorrect usage of Cecil by Piranha. I'll investigate a bit.

**Comment by Jjagg** [comment]
I found were the issue occurs, but I have no idea how to fix it. 

The issue occurs when a [`RenderTarget2D` constructor](https://github.com/Jjagg/MonoGame/blob/593ed64f8beeafb20935b1d7fcf964a0f3e2c9f4/MonoGame.Framework/Graphics/RenderTarget2D.cs#L52) call by a [`SwapChainRenderTarget` constructor](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/SwapChainRenderTarget.cs#L54) is handled in [this Piranha function](https://github.com/Ark-kun/Piranha/blob/master/Ark.Piranha/CollectTypesDependenciesProcessor.cs#L205). `methodDef` in the [Piranha method where things go wrong](https://github.com/Ark-kun/Piranha/blob/master/Ark.Piranha/CollectTypesDependenciesProcessor.cs#L205) is the `SwapChainRenderTarget` constructor and `callMethodRef` is the `RenderTarget2D` constructor. Somehow Cecil does not know the DeclaringType of the RT2D ctor, so `callMethodRef.DeclaringType` is `null`...

I'm off on holiday for a week. I'll get back to this afterwards (if no one else has fixed it by then).

**Comment by zigzag312** [comment]
> I made it so the resolved texture is stored in the _texture field and the MSAA texture is stored in the _msTexture field. That made more sense, since code interacting with the texture usually requires the resolved texture.
Good catch @Jjagg! I'll test this when I'll have some time, to see if I can help in any way

**Comment by Jjagg** [comment]
Thanks @zigzag312! :)
Unfortunately I don't have time to look at the Piranha issue atm, so this will have to wait for a bit unless someone else would like to check it out.

**Comment by zigzag312** [comment]
I can't find what is causing the issue with Piranha. 
You could try removing optional parameters introduced at `internal RenderTarget2D` constructor? It should be a problem, but that is the only major change I can find. 

Otherwise, refactoring you did looks nice :) I did some basic MSAA testing and nothing is broken :P

**Comment by Jjagg** [comment]
Great! Thanks for testing :) I forgot about this PR, I'll see if I can get it working in the next couple days!

**Comment by Jjagg** [comment]
@cra0zy This is ready for review.

**Comment by Jjagg** [comment]
@cra0zy This is good too :)

**Comment by Jjagg** [comment]
Bump @cra0zy

**Pull request merged**
