### PR TITLE
added missing words to platforms.md

### PR DESCRIPTION
**Pull request by MrGrak**
the previous .md omitted words that are required for the sentence on line 111 to make sense. i assume "test and deploy" is the correct description.

### CODE REVIEW

**Comment by MrGrak** [comment]
found another small error in migrate_38.md too.

**Comment by MrGrak** [comment]
found another small issue where 'getting started' sections were missing numbers, which feels inconsistent

**Comment by mrhelmut** [comment]
Thanks! Please let me know if this PR can be merged or if you believe that there is going to be more edits.

**Comment by MrGrak** [comment]
i think that's it for today. i'm working on some articles and a sample game that i'd like to add in a future pr. i'll keep that one separate, sorry for combining commits in this pr.

**Comment by mrhelmut** [comment]
Awesome, thanks!

**Pull request merged**
