### PR TITLE
Use desktop and UWP specific assemblies where necessary

### PR DESCRIPTION
**Pull request by Jjagg**
Depends on MonoGame/MonoGame.Dependencies#115. 

Because we used the .NET Standard assemblies, some conditionally compiled code that we need was not included (see the issue in .Dependencies for details). This makes MG use the assemblies compiled specifically for either UWP or desktop where needed.

This should fix issue #5998

### CODE REVIEW

**Comment by Jjagg** [comment]
Not sure what the error is all about. Things are good locally :/

**Comment by Jjagg** [comment]
Oh, Windows DX still targets .NET 4.0 and I included the SharpDX assemblies that target .NET 4.5. I think that's what causes the error.

**Comment by Jjagg** [comment]
MonoGame/MonoGame.Dependencies#115 and this one are good to go! @tomspilman

**Comment by tomspilman** [comment]
@KonajuGames @dellis1972 @DDReaper - Can you guys review this?  I want to be sure we got things right this time.

**Comment by Jjagg** [comment]
I thought that Windows DX templates still targeted .NET 4.0 (I think that was for Windows XP support), but that's not the case anymore, they target .NET 4.5 as well now. 

.NET Standard 1.1 can only be used in projects targeting .NET Framework 4.5 and up, so it won't be possible to build for 4.0 anymore. We can use all 4.0 assemblies from SharpDX targeting 4.0 for now if that's an issue, but SharpDX is no longer building future versions for .NET 4.0 IIRC so this may be harder to do in the future if we want to keep it up longer.

**Comment by Jjagg** [comment]
@DDReaper @dellis1972 @KonajuGames Can anyone review/test this? Xbox UWP is currently broken and this should fix it.

**Comment by MichaelDePiazzi** [comment]
Just tested this on both Windows 7 and 10 (v1709) and all is working as expected for me. I tested this using my game and confirmed that sound effects, music, and controllers are all working. I can confirm that this fixes the issue I reported (#6083).

**Comment by Jjagg** [comment]
@dellis1972 Could you merge this too. It's good to go since you merged MonoGame/MonoGame.Dependencies#115.

**Pull request merged**
