### PR TITLE
fix Effect Constructor with Index

### LINKED ISSUE #7794: Error on creating Effect with byte array and range
*example code:*
```
protected override void Initialize()
{
    var mgfxo = File.ReadAllBytes(@"test.mgfxo");
    var index = 100000;
    var byteArray = new byte[index+mgfxo.Length];
    Buffer.BlockCopy(mgfxo, 0, byteArray, index, mgfxo.Length);
    var effect = new Effect(this.GraphicsDevice, byteArray, index, mgfxo.Length);
}

```
*result:* 
```
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.MemoryStream..ctor(Byte[] buffer, Int32 index, Int32 count, Boolean writable, Boolean publiclyVisible)
```

*root cause:*
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/Effect.cs#L131
```
header.HeaderSize = index;
```

The `index` here is absolute index of the entire buffer,
and we can't assume that the `index` argument passed in this function to always be 0.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

----

The bug is there for over 8yrs but even no test case covers it:(
image

### PR DESCRIPTION
**Pull request by nkast**
fixes #7794

### CODE REVIEW

**Comment by BlueElectivire** [comment]
Perhaps change the exceptions to a more descriptive type of exception like System.IO.FileFormatException? Would probably make logs more accurate and helpful and it's not a big change.

**Comment by nkast** [comment]
@mrhelmut , in addition to the fix, I moved the file checks outside of the ReadHeader. as I think it's best to have them in the main  method and keep the readHeader method clean and short. This makes it easier to change the code with custom formats, support back versions, etc.  let me know if, it's ok. 

@BlueElectivire that sounds reasonable. Do you think we should change all the exceptions or just the first one that checks for the file signature?

**Comment by nkast** [comment]
@mrhelmut , in addition to the fix, I moved the file checks outside of the ReadHeader. as I think it's best to have them in the main  method and keep the readHeader method clean and short. This makes it easier to change the code with custom formats, support back versions, etc.  let me know if, it's ok. 

@BlueElectivire that sounds reasonable. Do you think we should change all the exceptions or just the first one that checks for the file signature?

**Comment by mrhelmut** [comment]
Thanks! I'll review it soon, it seems straightforward enough.

**Comment by BlueElectivire** [comment]
@nkast I suppose all of them, because they are all to do with the format of the file not being compliant with what the program is looking for and I don't think there is another exception type that describes that more accurately.

**Pull request closed without merging**
