### PR TITLE
[WIP] Documentation update for 3.8.1

### LINKED ISSUE #7662: Dead link to "SpaceWar" in Samples & Demos documentation
MonoGame/Documentation/articles/samples.md has a link to https://github.com/MonoGame/MonoGame.Samples/tree/develop/SpaceWar, which does not exist.

https://github.com/MonoGame/MonoGame/blob/4f2a554fe890000e9a2456c776f658824a3c4858/Documentation/articles/samples.md?plain=1#L11

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

### PR DESCRIPTION
**Pull request by mrhelmut**
This is a work in progress.

Here is a documentation update for the upcoming 3.8.1 release.

I am trying to simplify it where possible, and to make it more readable/straightforward.
So far I have mostly worked on the getting started/onboarding, but I intend to go through all of it to harmonize things up.

Fixes #7662

### CODE REVIEW

**Comment by mrhelmut** [comment]
This is pretty much "3.8.1 ready" and only needs the VS2022 Mac extension to be uploaded somewhere in order to be able to point to it.

**Comment by CartBlanche** [comment]
@mrhelmut I didn't realise you had a PR outstanding and pushed a small grammatical fix to https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GameRunBehavior.cs after it was brought to my attention on Twitter. You may want to pull in the latest from develop to pick it up.

**Comment by mrhelmut** [comment]
Thanks for letting me know! I will!

**Comment by mrhelmut** [comment]
@harry-cpp I've updated this PR to preemptively link toward the mac extension (by linking to the release assets instead of the mpack direct link). This would allow us to merge this PR and then https://github.com/MonoGame/MonoGame/pull/7823 to make the release and move forward.

In addition to the deploy task, what do you think if I do a release task that creates the github release with the VS extensions as assets to the release and the description pointing toward the packages?

**Pull request merged**
