### PR TITLE
Fix #6336

### LINKED ISSUE #6336: Error with BoundingSphere.Intersects(BoundingBox)
Created a Sphere with `BoundingSphere Bound = new BoundingSphere(new Vector3(0, 5, 0), 1);`
and a Box with `BoundingBox BoxBound = new BoundingBox(-Vector3.One, Vector3.One);`.
When I decrease the Y-value of the Bound, `Bound.Intersects(BoxBound)` will never return True when the intersect.

`Bound.Contains(BoxBound) == ContainmentType.Intersects` on the otherhand will return true.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

### PR DESCRIPTION
**Pull request by lithiumtoast**
See #6336. I used C# 7 deconstructor here. If C# 7 features are not yet allowed I can modify the solution.

### CODE REVIEW

**Comment by lithiumtoast** [comment]
@Jjagg There is no test I can find that uses the `Intersects` method. Also why is this build failing?

**Comment by mrhelmut** [comment]
You can check the build/test log on the teamcity details for each checks.

It fails because C# 7 isn't within the MonoGame requirements. You'll have to break down the ```var (x, y, z)``` statement.

**Comment by Jjagg** [comment]
@lithiumtoast Thanks for this!

There is no test for it yet. Related tests are in [Bounding.cs](https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/Bounding.cs).

**Comment by lithiumtoast** [comment]
Should I add test then to Bounding.cs?

**Comment by Jjagg** [comment]
Yes, please do :)

**Comment by Jjagg** [comment]
Gonna merge this. Would still be nice to get a test in though. Thanks @lithiumtoast!

**Pull request merged**
