### PR TITLE
Fix initialization crash on iOS GLES 2.0 devices

### PR DESCRIPTION
**Pull request by dtaylorus**
Fall back to GLES 2.0 after first attempting to initialize GLES 3.0 rather than assuming the GLES version based on the iOS version as per the [Apple developer documentation](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/WorkingwithOpenGLESContexts/WorkingwithOpenGLESContexts.html) (see Listing 2-1).

Tested on an iPad 4 running iOS 9.3.5 (GLES 2.0) and an iPad 6 running iOS 13.3.1 (GLES 3.0).

### CODE REVIEW

**Comment by dtaylorus** [comment]
The issue fixed by this change is described in #7051

**Comment by ryancheung** [comment]
That is weird,. Apple said iOS 7 or above support gles 3, but actually it's not true?

**Comment by dtaylorus** [comment]
If you check out Apple's [Device Compatibility Reference](https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html), you can see that some devices like the iPhone 5 and the iPad 3 don't support GLES 3, however, they support up to iOS 9.

I also have a physical iPad 3 device running iOS 9 that I test on and that's how I found the issue. It definitely doesn't support GLES 3 but works fine with my fix to fall back to GLES 2.

**Comment by harry-cpp** [comment]
This seems fine to me, was gonna suggest avoiding try / catch, but there really does not seem to be a way to detect if the device supports GLES3 from C#, unless we want to manually invoke the create method or hardcode GLES2 devices, which I would rather not do, so merging!

Thanks @dtaylorus!

**Pull request merged**
