### PR TITLE
Repair and restore the Windows 8 templates

### PR DESCRIPTION
**Pull request by DDReaper**
* Fix Windows 8 Templates to target 8.1 natively
* Fix UWP Universal template to correct version
* Enable Windows8 templates for VS2015

### CODE REVIEW

**Comment by DDReaper** [comment]
Not ready for commit. Still working on template errors

**Comment by DDReaper** [comment]
For what it's worth.  All projects updated and added VS2015 support for Win8.1 / Win8 Universal.
Windows 10 Universal project folder renamed for clarity

Passed and working, over to you @tomspilman / @KonajuGames

**Comment by KonajuGames** [comment]
Need to pull the latest and update submodules.  The Dependencies submodule reference was fixed a couple of hours ago.

**Comment by DDReaper** [comment]
Ahh, so I need to include this in the PR @KonajuGames ? , I did see a submodule update but I usually exclude them

**Comment by KonajuGames** [comment]
If you pull latest and update the submodules, the next commit should fix
the submodule references.

**Comment by nkast** [comment]
@DDReaper You can also remove SwapChainBackgroundPanel and replace it with SwapChainPanel. 
Win8.0 was the only reason we still keep it around.

The first line at msdn is '[SwapChainBackgroundPanel may be altered or unavailable for releases after Windows 8.1 Instead, use SwapChainPanel.]'

**Comment by DDReaper** [comment]
I'll check if it works with an update to the template as it world make sense.

**Comment by DDReaper** [comment]
There you go @KonajuGames , that ok now for merge?
If not, I'll rip out the update to a new PR to clean it up.

**Comment by DDReaper** [comment]
So @tomspilman / @KonajuGames is this ready to go, so that the templates are fixed for 3.6?

**Comment by KonajuGames** [comment]
Merging.

**Comment by DDReaper** [comment]
Thanks @KonajuGames

**Pull request merged**
