### PR TITLE
Protobuild Removal

### PR DESCRIPTION
**Pull request by harry-cpp**
For now we will need 4 steps in the build system:

Windows build:
```ps1
./build.ps1 -ScriptArgs '-build-version="1.001.01"', '-build-target="Pack"'
```

Windows test:
```ps1
./build.ps1 -ScriptArgs '-build-version="1.001.01"', '-build-target="Test"'
```

Mac build:
```sh
./build.sh --build-number=1.001.01 --build-target=Pack
```

Mac test:
```sh
./build.sh --build-version=1.001.01 --build-target=Test
```

Extra notes:
- Version can be specified using `BUILD_NUMBER` env variable instead of `build-version`
- We can install `CAKE` dotnet tool on the build server instead of calling the wrapper scripts (dotnet tool install --global Cake.Tool --version 0.37.0)

Post CAKE stuff:
- Artifact publishing
- MGCB Editor dotnet tool
- Installer that just calls few dotnet instal commands?
- VSIX template automatic upload
- VS Mac template automatic upload
- Visual Studio templates using dotnet templates

### CODE REVIEW

**Comment by tomspilman** [comment]
Ok i updated this PR with the current .teamcity build scripts.

Going to start working on editing them to work with the new Cake build.

**Comment by tomspilman** [comment]
@harry-cpp @Jjagg - I'm done with the build server for now.  We need to either fix the Mac unit tests or disable them temporarily so we can merge this.

**Comment by tomspilman** [comment]
Also we could remove the `build.ps1` and `build.sh` scripts since `dotnet cake` can be called directly.  I think providing the instructions on installing Cake is enough.

**Comment by Jjagg** [comment]
I agree, the scripts clutter the root folder and I prefer running dotnet cake.

I think it's fine to temporarily disabled Mac tests.

**Comment by Jjagg** [comment]
> Artifact publishing

You mean publishing development nugets? Or should we set up CI to publish releases as well? AFAIK that was never automated.

> MGCB Editor dotnet tool

Yeah, this needs to happen before we release. What's the status? Do you have your latest work in your fork?

> Installer that just calls few dotnet instal commands?

Eh, I'd rather just see us have good docs that list the commands.

> - VSIX template automatic upload
> - VS Mac template automatic upload
> - Visual Studio templates using dotnet templates

Most important here is that we have a working VS template IMO. Automation is secondary.

**Comment by mrhelmut** [comment]
To me, short term goal would be to have a VSIX with the templates on the MonoGame's website (no incentive to have it on the CI, it will likely get updated very rarely) + documentation to use ```dotnet``` CLI if users prefer that flavor.

Regarding development nugets: since there was a development installer in the CI, it would make sense that unstable nugets are published by the CI (nuget manage this well, and could allow users to opti-in/out of the unstable branch easily).

**Comment by tomspilman** [comment]
> You mean publishing development nugets? Or should we set up CI to publish releases as well? AFAIK that was never automated.

If we're just deploying nugets then artifacts are 100% automated already.

Every build we do appears in our develop nuget feed hosted on our TeamCity server.

If we want to push out a develop build to the nuget.org i just have to trigger the build server and it does it.

As for releases when we merge `develop` to `master` it does a build and automatically pushes it to nuget.org.

So nothing we need to worry about here.

**Comment by Jjagg** [comment]
Then IMO when we can distribute the pipeline tool (I guess we should start saying mgcb editor) we should do a release :)

**Comment by jnoyola** [comment]
> What's the status?

I believe the status of packaging the MGCB Editor in a single dotnet tool is mostly waiting on me after this PR goes in. It'll take some time to merge, but I think all that remains is Linux and Mac registration and unregistration (i.e. file association) and thorough testing.

**Comment by aaronfranke** [comment]
If you are going to make huge, massive, PR-breaking refactoring changes, would it kill you to merge some of the PRs first?

https://github.com/MonoGame/MonoGame/pull/6314 conflicts because of this and I'm not going to update it. I refuse to do any work that could have been avoided if y'all simply didn't wait years and years to review your PRs (and even then I don't even know if you would merge it anyway), someone else will have to rebase it if it's desired.

Please in the future just take the time to review your PRs, people are literally sending you free code and you just have to accept it. If you would just review PRs then MonoGame would be much better off and have many more features. Stop leaving PRs in purgatory for years.

**Comment by mrhelmut** [comment]
Please mind that MonoGame is maintained by industry people, that the project is lead by industry needs and in that regard there are biggest priorities to move the project forward that has been waiting for as much time as your PR, if not longer.

The on-going refactoring work is the current top priority and the maintainers can't afford re-reviewing non-critical PRs during this process so it is very likely that no non-critical PR will be reviewed until the next major release of MonoGame happens.

A project's governance can't please everybody, that's a fact.

**Comment by Jjagg** [comment]
@aaronfranke I'd just like to add that PRs are not free code that just needs to be accepted. Reviewing a PR takes time and effort, and time is a scarce resource for us so we need to set our priorities. This PR in particular is a big step forward for the project and we've been working towards this for years.

Of course we massively appreciate any contributions and I would like us to be more responsive to PRs. But I'll add that I don't think we have a responsibility to accept PRs and contributors such as yourself do not have a responsibility to fix up your PRs when we break them. If your PR is more important for you than our changes that break it, you can maintain your branch (I mean this sincerely, this is not meant to be a jab though I realize it might come across as one).

**Comment by tomspilman** [comment]
@aaronfranke for sure you're right... in an ideal world each PR would get merged quickly.  

But deciding what is a good PR is harder than it seems.  When we get great PRs you'll see it merged very quickly.  The ones that remain open are all questionable additions to MG that none of the maintainers feel strongly about adding.

So how would you feel if we just closed and rejected PRs more quickly?  Because that is the likely outcome if we were forced to decide on PRs within a week or so of submission.

**Comment by aaronfranke** [comment]
> So how would you feel if we just closed and rejected PRs more quickly?

In my opinion, that would be an improvement. Maybe not a week, but a few months perhaps. Also, if there are less open PRs, it should be easier for you to sort through them all.

**Comment by willmotil** [comment]
I see you put a lot of work into that.
So let me first say thank you but ...

Im going to be honest i don't like most of this for the following reasons.

First off SpriteBatch uses rectangles and points so this basically affects everyone by bloating the point class.

2) Second i don't want or need half of those methods or operators added to the point class which is heavily used by everyone. To me this is mostly bloat that will never be either used or needed by most people.

3) All of that can be added with extension methods to your project without affecting mine with extension methods. Then we get the situation were we are both happy.
I don't want it. 
You can still have it.

4) A 3d point class is the lesser of the evils though i don't think its a good idea conceptually either.
A point is needed because actual screen positions relate to real finite physical led pixels or miniaturized lights on monitors other wise would any of us use point at all ? Having a point class in monogame that has a integer z represents in my mind is literally 'pointless'.

**Comment by aaronfranke** [comment]
There is also the fact that the PR adds tests for Point.

**Comment by willmotil** [comment]
Well typically how i approach a change is humbly. i know from experience there is a good chance im simply not aware of something so ill post a formal issue for a change making a case for why. I try to leave room for others to criticize or counter opinion. I have many times been more wrong then i've been right. 

So when i feel too surely about something and its not already there, then my rule of thumb is i must be really wrong now and then im usually right about that.  

Sometimes you have to bump the issue a little to get a response and its better to get opposing  arguments before you commit to writing the code. If the opposing arguments convince you it will teach you something and save you time. Sometimes you gotta bump though.

**Pull request merged**
