### PR TITLE
[Pipeline Tool] OutputParser Optimizations

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
- Reorganizes actions so that more common actions are checked first
- Replaces Regex for Skipping/Cleaning with StartsWith
- Minor coding style changes so that it matches the rest of the project
- Separate thread for filter output

### CODE REVIEW

**Comment by tomspilman** [comment]
Thanks @cra0zy ... this should be a ton faster.  I'll take a look now.

**Comment by cra0zy** [comment]
> Thanks @cra0zy ... this should be a ton faster. I'll take a look now.

Do tell me the results, I have an idea for one extra optimization that I will try tomorrow.

**Comment by tomspilman** [comment]
> Do tell me the results

With a build I see around 4 to 5 seconds slower than the time reported by MGCB.

With a clean the filter output is around 17 seconds slower than the time reported by MGCB.

So still much slower that I would like to see it be.  Is it possible that the invalidate you're doing is forcing a redraw during that call and isn't just marking the window dirty for redraw later?

You might need to run a profiler on this to figure out the real bottlenecks here.

**Comment by tomspilman** [comment]
@cra0zy - Hang on.... I think I tested this wrong.

**Comment by tomspilman** [comment]
@cra0zy - So I did test wrong...  it is better than what I reported before, but still not as good as it should be:

About 2 to 3 seconds slower in a clean build or a rebuild of content.

Around 9 seconds slower cleaning content.

**Comment by cra0zy** [comment]
https://github.com/MonoGame/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L508

We just need to make it not call the function directly but instead add a line to the buffer.

**Comment by cra0zy** [comment]
In case you are awake and want to test out my 2nd idea of optimization I pushed the commit. It's not finished tho, but the end speed result will be that.

**Comment by cra0zy** [comment]
It should be done now.

**Comment by cra0zy** [comment]
Just gonna add that I think I optimized the textview build output as well.

**Comment by tomspilman** [comment]
@cra0zy - This branch is conflicted... if you can fix it I can test it.

**Comment by cra0zy** [comment]
Done.

**Comment by cra0zy** [comment]
@tomspilman Did you get the chance to test these changes?

**Comment by cra0zy** [comment]
I'm gonna temporarily close this PR, I'll resubmit it once few other parts get merged (this is so I don't have to worry about merge conflicts).

**Pull request closed without merging**
