### PR TITLE
Disable Piranha portable build

### PR DESCRIPTION
**Pull request by Jjagg**
This drops the PCL build in favor of the DesktopGL .NET Standard build.
We need to document how to write a lib for all platforms.

### CODE REVIEW

**Comment by Jure-BB** [comment]
So, MG is finally doping Piranha? That means I can close #6021?

**Comment by tomspilman** [comment]
So how does this affect things like the Piranha build of the content pipeline assembly?

That is fantastic when writing custom pipeline extensions and not needing to link against a specific platform's version of MG.  When your extension is loaded in the pipeline tool or MGCB it just works.

Will that still be true?

**Comment by Jjagg** [comment]
There is now a Content.Pipeline project that is cross platform. We don't need bait and switch anymore for the Content.Pipeline assembly. 
The cross platform Content.Pipeline project references DesktopGL, but that can be changed to another runtime if necessary with bait-and-switch.

**Comment by cra0zy** [comment]
And also the MG.Content.Pipeline main nuget can be used as bait and switch.

**Pull request merged**
