### PR TITLE
Fix active state event on startup

### PR DESCRIPTION
**Pull request by mrhelmut**
Need testing.

Fixing #7992

### CODE REVIEW

**Comment by gluser2** [comment]
> Need testing.

I patched this into my custom fork of MonoGame and it works beautifully for DesktopGL! The window comes up behind my active window (taskmgr.exe), and as soon as it grows to the correct size window, it turns red (using [bwiklund](https://github.com/bwiklund)'s !iGame.IsActive code) to show that it recognizes it's inactive.

Could a similar fix be made for WindowsDX, which appears to have the same problem? It looks like MonoGame.Framework\Platform\Windows has a WinFormsGamePlatform.cs, which may function similarly to SDL\SDLGamePlatform.cs.

**Comment by gluser2** [comment]
Your new patch defaults to active state on 3 of 3 tests I did, which is what it was intended to do. Is there no way to help the WinForms event pump detect the right startup state?

**Comment by mrhelmut** [comment]
@gluser2 I've applied the same to WindowsDX. Would you mind testing that too?

**Comment by gluser2** [comment]
On both computers I tested*, your patch still starts an inactive game in an active state, just like MG 3.8.1 and the develop branch do. However, your patch also keeps MonoGame in an active state even when Alt+Tab is pressed or another window is drawn on top of it. I don't know why it's behaving this way, but the game seems to never enter an inactive state now.

* AMD A8-7600 x64 w/ AMD R9 255 graphics, and Qualcomm 7C ARM64 w/ Adreno 618 graphics

**Comment by mrhelmut** [comment]
Is this with DesktopGL or WindowsDX?

**Comment by gluser2** [comment]
The DesktopGL fix worked perfectly, but the one I reported on in my last comment was WindowsDX.

I made a new DX project that referenced the source code of your commit, a second that referenced the source of the develop branch, and a third using the standard 3.8.1.303 release NuGet (no source), all in Visual Studio 2022. They were built on the x64 machine and run on both that and the arm64. The behavior was the same on both.

OSes were Windows 10 and 11. .NET 8.0.1 and WinForms were used to draw the MG windows. The new DX projects were a created template from 3.8.1, since I didn't see one in the source files. I only modified the games to draw Red instead of CornflowerBlue while the window is inactive.

I open the 3.8.1 or develop built game and click another window like Windows Task Manager. When the game launches, it should be inactive (red). But it's still blue under the other window. After clicking on it for the first time, anytime you switch windows it turns red like it should.

The game I built on your commit (with the modified WinFormsGameWindow.cs) launches blue when inactive, like the other ones. But in contrast, no matter how often I click the window and back on Task Manager, it never turns red. It seems like it's stuck in an active (blue) state.

Do you have a different setup? How does the patch perform on your machine?

**Comment by mrhelmut** [comment]
Closing because no traction and no time to check if this is even possible consistently across all implementations. If anyone wishes to takeover, please do feel free.

**Pull request closed without merging**
