### PR TITLE
Fix Pipeline Tool compilation with msbuild

### PR DESCRIPTION
**Pull request by cra0zy**
Turns out that if you have 2 embedded resources that depend on one .cs file, and you compile that, msbuild deletes the 2nd embedded resource and makes the link point to the first one, definitely sounds like a bug to me.

### CODE REVIEW

**Comment by cra0zy** [comment]
@dellis1972 @KonajuGames @tomspilman Ping.

**Comment by dellis1972** [comment]
@cra0zy I've seen something like this before. Its happened  when I use a symlink to link the MonoGame Directory to another location. When building in the normal folder its ok, when in the symlinked folder it removes the EmbeddedResource prefix. Not sure if this is related though.

**Comment by cra0zy** [comment]
@dellis1972 @KonajuGames @tomspilman Re-ping... its just a resource name change.

**Comment by cra0zy** [comment]
@cra0zy sad :(

**Comment by cra0zy** [comment]
Yess, thank you @dellis1972

**Pull request merged**
