### PR TITLE
Fix for #6732 - Exposes the instancing base index

### PR DESCRIPTION
**Pull request by YTN0**
Per #6732 ... This change exposes the option to set the instance base index for instancing. This works perfectly on DirectX, and somewhat works on OpenGL. On OpenGL, this is still impacted by the instancing bug #6293. 

Note: For OpenGL, if not setting the base instance index (which is the default behavior), it will continue using the original OpenGL API. If setting the base, this will use the OpenGL API glDrawElementsInstancedBaseInstance which is only available in OpenGL 4.2 and higher.

FYI @Jjagg

### CODE REVIEW

**Comment by YTN0** [comment]
FYI, protobuild isn't generating the web project, so I missed that in my initial checks. I did update that after the build failed... however it would be good to have the VS project for web also generated by protobuild so it isn't missed in any fixes / updates.

**Comment by YTN0** [comment]
Anyone have any thoughts on this PR? I am hoping this can get into 3.8....

**Comment by YTN0** [comment]
@Jjagg Would love to get some input on this... I am currently using a modified version of the Monogame dll with this patch, but would love to get it into the core platform. It's fully backward compatible.

**Comment by Jjagg** [comment]
Hey @YTN0! Feel free to ping me more often if I don't respond for a while :) 

This is great to have IMO!
However [glDrawElementsInstancedBaseIndex](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawElementsInstancedBaseInstance.xhtml) requires OpenGL 4.2 which is a lot higher than the minimum for MG. If we're gonna add this it needs to be added to GraphicsCapabilities and we need to check if the GPU supports the feature when a base index is passed. We could implement the fallback ourselves when the feature is not supported, but either way we should have it added to GraphicsCapabilities.

**Comment by YTN0** [comment]
@Jjagg Will take a look at GraphicsCapabilities and see if I can figure that stuff out.

Thanks.

**Comment by YTN0** [comment]
@Jjagg Added support and check using GraphicsCapabilities. Let me know if it looks good and is what you had in mind.

**Comment by YTN0** [comment]
@jjag Ugh... I rebased and looks like its now showing all the commits from the rebase. Not sure how to resolve that.

**Comment by YTN0** [comment]
@Jjagg will close this PR and resubmit a new clean one based on the new develop changes.

**Pull request closed without merging**
