### PR TITLE
Fix property content serialization detection when using a property named `Item`.

### PR DESCRIPTION
**Pull request by joncloud**
* Adjusts indexer property detection to check for Index Parameters instead of get/set method's parameters.
* Moves test compliation in order to share between tests.
* Creates new tests to verify changes.

### CODE REVIEW

**Comment by joncloud** [comment]
I did notice that `ReflectionHelpers.GetPropertySetMethod` appeared to be no longer in use. I wasn't sure if I should remove it or not.  Also `ReflectionHelpers.GetPropertyGetMethod` is only being used within the `ReflectionHelpers` type.

**Comment by joncloud** [comment]
I should be able to look into the failing build checks today.  I will need to setup locally to diagnose the failures.

**Comment by joncloud** [comment]
Resolved the build errors by rolling back C# syntax to a more compatible version.

**Comment by tomspilman** [comment]
@joncloud - Thanks...  i'll make sure this gets reviewed and merged here shortly.

**Comment by tomspilman** [comment]
For a future PR it might be better for `ArrayContentCompilerTest.cs` and `XmlContentCompilerTest.cs` to be merged and moved into a new `ContentCompilerTest.cs` as that is what these both are.  

Don't see a huge need to split this all up.

**Comment by joncloud** [comment]
Got it - Do you want me to merge the two together on this PR, or setup another PR to do that?

**Comment by tomspilman** [comment]
@joncloud - If you have the time and could do that in this PR it would be great.  If not it can wait for another PR.

**Comment by joncloud** [comment]
OK I should be able to get the two merged on this PR. I just need to setup my test environment.

**Comment by tomspilman** [comment]
Thanks @joncloud !  Merging!

**Pull request merged**
