### PR TITLE
[Templates] Update shared library template

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by cra0zy** [comment]
@Jjagg Can you take a look at this?

**Comment by Jjagg** [comment]
Will test this later today!

**Comment by Jjagg** [comment]
The Content.mgcb file has Windows set as platform. Shouldn't that use the Platform property?

**Comment by cra0zy** [comment]
> The Content.mgcb file has Windows set as platform. Shouldn't that use the Platform property? Other than that this is good!

No, the platform during compilation gets set from the command line, the platform set in Content.mgcb is irrelevant.

**Comment by cra0zy** [comment]
> Shouldn't that use the Platform property?

Also not sure how you would do that.

**Comment by Jjagg** [comment]
> No, the platform during compilation gets set from the command line, the platform set in Content.mgcb is irrelevant.

Ah, right. Merging!

**Pull request merged**
