### PR TITLE
Tests for Texture2d.FromStream

### PR DESCRIPTION
**Pull request by Tzenchor**
Related to #4820 
This implements the test for Textures with `Alpha=0` and `Alpha=129`, both tests work on XNA, but the second one fails on Monogame.

### CODE REVIEW

**Comment by tomspilman** [comment]
Cool...  this proves the problem.  Now to implement the fix.

**Comment by Tzenchor** [comment]
There's a problem.
Image loading depends on SharpDX, and the decoder is set to `PixelFormat.Format32bppPRGBA`, that I assume it is Premultiplied RGBA. So I tried with `PixelFormat.Format32bppRGBA`, but both tests fail.
With the transparent image it's returning `R: 255, G: 255, B: 255, A: 0` (the color is wrong but I think it is more a problem with the image editor when painting with 0 alpha than a bug on SharpDX).
With the semi transparent the result is: `R: 255, G: 128, B: 64, A: 129` that nearly matches what XNA returned `R: 254, G: 128, B: 63, A: 129`

**Comment by KonajuGames** [comment]
I say we use our own PNG loader like on the other platforms. More control
over the process. This does lose JPG and GIF loading though.

**Comment by tomspilman** [comment]
> I say we use our own PNG loader like on the other platforms.

I agree...  consistency across platforms is critical and we can't get that using platform specific loaders.


> This does lose JPG and GIF loading though.

Minor short term losses IMO.

**Comment by Tzenchor** [comment]
> I say we use our own PNG loader like on the other platforms.

I'm supposing it is `MonoGame.Utilities.Png.PngReader`. I tried it and the results are the same as with the SharpDX loader as said in my previous post

**Comment by Tzenchor** [comment]
I have just made a little test and without premultiplied alpha texture composition does not work as expected. I'm printing a brown opaque texture and a white transparent one above, and the result is nearly white.

Also I have found a bug in `Texture2D.GetData<T>(int, Rectangle?, T[], int, int)` on DirectX, if startIndex (the penultimate parameter) is not zero, nothing is copied to the array (Tested on XNA and it works).

**Comment by KonajuGames** [comment]
> I have just made a little test and without premultiplied alpha texture composition does not work as expected.

You rendered the non-premultiplied texture with `BlendState.NonPremultiplied`?

**Comment by Tzenchor** [comment]
> You rendered the non-premultiplied texture with BlendState.NonPremultiplied?

No, but the code is the same I had from XNA

**Comment by Tzenchor** [comment]
Now that I have fixed the problem I had with the image editor i'm using an image with color:
`R: 136, G: 66, B: 16, A: 24;` SharpDX loader without premultiplied alpha is returning that color, the `PngReader` stated in a previous post returns that color, the "color selector" (or whatever it is called in english) tool in paint.net also returns that color, but in XNA I get `R: 138, G: 63, B: 21, A: 24;`. And the weirdest thing is with `R: 136, G: 66, B: 16, A: 24;`, MonoGame methods keep returning the same color, but XNA now gives an amazing `R: 255, G: 0, B: 0, A: 1;`

Another weird thing is that I have the a XNA 4.0 project where I load some textures with `FromStream` and the resulting image is the same one as with Monogame before begining this work

**Comment by tomspilman** [comment]
I fixed this issue finally in https://github.com/MonoGame/MonoGame/pull/5712 along with unit tests similar to these.

**Pull request closed without merging**
