### PR TITLE
Updated VS 2017 templates so they work

### PR DESCRIPTION
**Pull request by DDReaper**
Updated VS 2017 templates so they work
Inherits old "compatible" templates
Inherits 2017 Universal 10 VB template

Ref Issue #5515

### CODE REVIEW

**Comment by tomspilman** [comment]
@KonajuGames - This look ok to you... didn't you just work on this?

**Comment by KonajuGames** [comment]
I can try these out tonight. Dean had tried the existing templates in
VS2017 and found they worked. I'm not sure why they were failing for
others. Will see what the differences are.

**Comment by DDReaper** [comment]
Sorry, meant to comment but I lost connectivity on the train.
This isn't ready yet and I'm still  testing.
Future reason it didn't do the safe name renaming.
May end up rebuilding the win10 template with vs2017.

The others and the nant/build scripts scripts are working. Just need to finish the reason I started the pr.

**Comment by DDReaper** [comment]
Trashing this PR for now with the 3.6 release.
Need to resubmit a new PR to resolve.

**Pull request closed without merging**
