### PR TITLE
Added 𝜏 field that represents 2π

### PR DESCRIPTION
**Pull request by Lautenschlager-id**

### CODE REVIEW

**Comment by Lautenschlager-id** [comment]
Hmmmm, I never got this message before:
image
Any idea how to fix it?

**Comment by cra0zy** [comment]
https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by Lautenschlager-id** [comment]
But I made this PR using interface, not Git or a local clone...
I can't see any settings on how to disable it :P

**Comment by tomspilman** [comment]
I'm closing this PR.

First yeah the GitHub interface for editing often can make a mess out of line endings making a horrible diff.  We won't accept PRs that mess up the line endings or have lots of unnecessary whitespace changes.  These things make it difficult to see real code differences and make merging differences much more difficult.

If you look thru this link you can see the real change:

https://github.com/MonoGame/MonoGame/pull/6569/files?w=1#diff-8dad363304b75645a1c44ef27461f03bR53

image

I understand there is a push in the math community to move to Tau (aka "Pi * 2").  I always felt MonoGame should be easy to use (hench `TwoPi` which more developers understand) but also teach the developer new and better ways.

So i would be ok with an alias if it were properly documented (and wasn't full of line ending changes).

@cra0zy @Jjagg @dellis1972 - Any thoughts on this?

**Comment by cra0zy** [comment]
> @cra0zy @Jjagg @dellis1972 - Any thoughts on this?

I'm fine with it.

> Edit: also, maybe would be nice to normalize newlines and tabs across the repo

They'll just get broken again by someone eventually.

**Comment by Lautenschlager-id** [comment]
I honestly have no idea how to fix that using Github's interface.

**Comment by KakCAT** [comment]
I've been wondering for lots of years why Pi was written in terms of diameter and not radius, but I had no idea there was a movement to "replace" Pi with Tau :)

**Pull request closed without merging**
