### PR TITLE
Update mgfxc_wine_setup.sh

### PR DESCRIPTION
**Pull request by Kwyrky**
Make sure we don't mess up .profile / .zprofile files which could have text or commands in the last line. In this case the export command would be appended directly to the last command and not end up in its own line.

### CODE REVIEW

**Comment by Kwyrky** [comment]
I added the `-e` flag as the change request suggested.

**Comment by harry-cpp** [comment]
Thanks @Kwyrky, merging!

**Comment by harry-cpp** [comment]
On a random note, did you know that a text file without a new line character at the end is technically invalid on Unix :)

**Comment by Kwyrky** [comment]
Nice, thanks for merging! That is what I assumed and wrote I think in the community forums ^^

**Pull request merged**
