### PR TITLE
Fullscreen can mode switch like it did in XNA

### PR DESCRIPTION
**Pull request by spunky44**
The issue is described here:
https://github.com/MonoGame/MonoGame/issues/5104

### CODE REVIEW

**Comment by spunky44** [comment]
Comments?

**Comment by Jjagg** [comment]
- You shouldn't add comments about what you changed, we can see that in the diff
- it seems weird that you have to pass the mode you fetch from swapchain to a function call on swapchain(ResizeTarget) Isn't there a parameterless overload? 
- I'll try this when I have the time :)

**Comment by spunky44** [comment]
It looks like some other commits appear in this PR which they should not.
It must have happened when I clicked "Sync".

**Comment by spunky44** [comment]
I will remove this PR since I don't really know what's going on.

**Comment by Jjagg** [comment]
It's easiest if you make a branch locally for the stuff you want to do in this PR (people often call this a feature branch). A PR is linked directly to your remote branch that you originated it from, so if you add commits locally and push them to a branch involved in a PR those commits will appear in the PR too. If you have a seperate branch, you can more easily control what goes to the PR branch and what goes to branches that are not in a PR. GitHub has some great articles on all this like [Syncing a fork](https://help.github.com/articles/syncing-a-fork/) and [Using pull requests](https://help.github.com/articles/using-pull-requests/). Feel free to ask if you have any questions :)

**Comment by spunky44** [comment]
Thanks, will remember to create a branch next time.

**Pull request closed without merging**
