### PR TITLE
[Pipeline Tool] New FilterView

### LINKED ISSUE #4458: Add Filters To Filter View
The new filter view in the Pipeline tool should have additional options to allow you to actually filter content.  
- Show/hide skipping.
- Show/hide successful content builds.
- Show/hide warnings.
- ???

Without something like this the filter view is just a more verbose version of the current output window.

### LINKED ISSUE #5233: Pipeline Filter View slows down build process
I have a content project that takes 6 seconds to build in the regular output view.

When i switch to the filter view the same build takes a crazy **2m 17 seconds**.  Nothing else has changed... the slowdown is consistent when the filter view is enabled.

I suspect how the filter view works is very very slow.... and it happens to be blocking the MGCB.exe output stream keeping it from progressing as fast as it could.

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
 - Replaces filterview with a custom drawn one (fixes #5233)
 - Adds filters (fixes #4458)
   - Show skipped items filter
   - Show succeeded items filter
   - Show cleaned items filter

Screenshot:
newnewfilterview

### CODE REVIEW

**Comment by james0x0A** [comment]
I ran a new test on this PR
Content project with 2379 items skipped producing 1 line of output per item.

Actual time spent processing content: 0.3 seconds

Filter view:
Time elapsed 00:00:24.12

Plain output:
Time elapsed 00:00:08.77

**Comment by nkast** [comment]
@cra0zy Looks good. I am waiting for the build server to test it. 
:thumbsup:

**Comment by cra0zy** [comment]
@tomspilman Mac server seems down.

@nkast I think the link is: http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/26825:id/MonoGameSetup.exe?guest=1

**Comment by tomspilman** [comment]
@cra0zy - Tried this PR...  it looks pretty good so far.  

I got a crash toggling the filter view on and off after a build on Windows.

I still want to see us combine the clean items with the build items...  but that came come in a later PR.

In my bigger projects the filter view is around 8x slower than the actual build process.  This can and should be fixed in your next PR.

**Comment by cra0zy** [comment]
> I got a crash toggling the filter view on and off after a build on Windows

Fixed. :)

> I still want to see us combine the clean items with the build items... but that came come in a later PR.

You or @nkast should setup a separate issue to discuss this.

**Comment by cra0zy** [comment]
PS. #5264 optimizes projectview for big projects, I'm guessing everyone in this thread might have some interest in it.

**Comment by nkast** [comment]
> You or @nkast should setup a separate issue to discuss this.

The GUI part of the Pipeline is not in my interests right now. I prefer not to get involved.

**Comment by cra0zy** [comment]
@tomspilman Build server for Windows never reported that the build finished to GitHub :|

**Comment by tomspilman** [comment]
Yeah...  I've seen that happen before.  I'll merge this now...  it is a huge improvement over the 100x slower build times I was getting with the filter view before.

**Comment by tomspilman** [comment]
So testing these changes I see the scroll bar is pretty screwed up.  

It doesn't always scroll to the bottom.  The thumb button size isn't correct to the page size.  When the filter view is empty the scroll bar can still be scrolled.

Just compare how the scroll bar behaves between the plain text output window and the filter view window.  They should behave roughly the same.

**Comment by cra0zy** [comment]
> It doesn't always scroll to the bottom.

Windows scrollview remembers the last scroll position, so this error could only occur when auto scrolling was disabled. I need to reset the scroll position on clear.

> The thumb button size isn't correct to the page size. When the filter view is empty the scroll bar can still be scrolled.

I am not able to replicate these.

**Pull request merged**
