### PR TITLE
Add Buttons.None

### PR DESCRIPTION
**Pull request by TimerbaevRR**
#7634

### CODE REVIEW

**Comment by TimerbaevRR** [comment]
Fixes #7634

**Comment by BaseCrosser** [comment]
About 6 years ago I also tried to add a `Buttons.None`. #4618
Doing this comes with some problems.

As was said back then the `GamePad.GetState().IsButtonDown` implementation is doing a bitwise & comparison between the pressed buttons and the parameter, but `Anything & 0` returns 0, and `0 == 0` is always true
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/GamePadState.cs#L138

With this implementation of adding `Buttons.None` and setting its value to 0 the result of querying `GamePad.GetState().IsButtonDown(Buttons.None)` would always return true.

**Comment by TimerbaevRR** [comment]
@mrhelmut  Maybe should we revert this PR?
I will try to fix problems and create new PR

**Comment by mrhelmut** [comment]
I don't feel like there is a need to revert this PR, it doesn't seem to cause any harm.

We should be fine with a ```if (button == Buttons.None) return false``` in ```IsButtonDown()```.

**Comment by mrhelmut** [comment]
I went ahead because the test were failing because of this and I'm looking into restoring them: #7822

**Pull request merged**
