### PR TITLE
Add API to query graphical system at runtime

### PR DESCRIPTION
**Pull request by rds1983**
Small and useful PlatformInfo enhancement.

### CODE REVIEW

**Comment by Jjagg** [comment]
Please rename `GraphicalSystem` to `GraphicsBackend`

**Comment by rds1983** [comment]
Sure.

**Comment by rds1983** [comment]
I've applied comments from #6846 to this PR.
I hope it's ok.

**Comment by Jjagg** [comment]
It's fine if you include them here if you can rebase to group your commits so it's 1 commit for the edits regarding #6846 and 1 commit for the changes here. Then I can do a merge commit for the PR and it will keep our git history clean
You can use `git rebase -i HEAD~5` and then use squash to group commits together.

**Comment by rds1983** [comment]
Yeah, makes sense.

**Comment by Jjagg** [comment]
Great! This just needs the closed platforms then. @cra0zy

**Comment by cra0zy** [comment]
I'll add the private platforms tomorrow.

**Pull request merged**
