### PR TITLE
Performance improvements to SpriteBatch.DrawString()

### PR DESCRIPTION
**Pull request by nkast**
spritefont_opt

### CODE REVIEW

**Comment by prollin** [comment]
I am surprised that removing ref/out is a perf win here. Just out of curiosity, does this part have a real impact when compared to the original code?
While not pretty, inlining this kind of operation is usually a win since it is not guarantied the compiler will do it for you.

**Comment by nkast** [comment]
@prollin 
>  I am surprised that removing ref/out is a perf win here. Just out of curiosity, does this part have a real impact when compared to the original code?

The first few commits are just to rewrite the code in a more readable form that made it easier to simplify it. I included every step in the process as a commit so you can verify it and I could go back and review it in case the tests failed.

**Comment by nkast** [comment]
@tomspilman I can't find other examples of how we comment a code block as an inlined optimization but I know it's somewhere...
Also I could replace the original code with the cleaner (but unoptimized) intermediate step from `Change mul order`.
https://github.com/nkast/MonoGame/blob/24653c2b3b1791cf5c58bda41dd2b52442f3a1c4/MonoGame.Framework/Graphics/SpriteFont.cs#L303-L311

**Comment by tomspilman** [comment]
> I can't find other examples of how we comment a code block as an inlined optimization 

What you have there looks fine to me.

> Also I can replace the reference code with the cleaner (but unoptimized) intermediate step 

No need...  what you have adequately explains things.


@KonajuGames @dellis1972 @cra0zy - This look good to merge?

**Comment by cra0zy** [comment]
I wouldn't leave in the old code, but that doesn't really matter.

Looks good to me.

**Comment by nkast** [comment]
Somebody tripped on the speakers?

`[MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.SubmitBuffer_ParameterValidation_SimpleOverload] Test(s) failed. System.NullReferenceException : Object reference not set to an instance of an object.
   at SharpDX.XAudio2.SourceVoice.CreateSourceVoice(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callback, EffectDescriptor[] effectDescriptors)
   `

**Comment by tomspilman** [comment]
> Somebody tripped on the speakers?

I think maybe we had power failure in the office.  It seems I need to login remotely once to get the speakers to work.  I'll fix it here in the next few hours.

**Comment by nkast** [comment]
No pressure.

**Comment by tomspilman** [comment]
Great work @nkast ... merging!

**Comment by nkast** [comment]
Thanks!

**Pull request merged**
