### PR TITLE
MGCB Improvements

### PR DESCRIPTION
**Pull request by cra0zy**
All the existing commands still work, these are just some qol changes for us Unix users.

Stuff done:
 - Adds flags
   - do tell me if you want some flags changed / added
 - Fixes Unix param argument to be "--" instead of "-"
 - Makes it so separators for arguments can both be ":" and "="
 - Improves help display (mostly mimicking Unix style here)
   - If the command description is too long there is extra text warping code added
 - Includes help command

Help menu on Windows:
```
MonoGame Content Builder
Builds optimized game content for MonoGame projects.

Usage: MGCB <Options>

Options:
  /@, /@:<responseFile>             Read a text response file with additional command line options and switches.
  /b, /build:<sourceFile>           Build the content source file using the previously set switches and options.
  /c, /clean                        Delete all previously built content and intermediate files.
      /compress                     Compress the XNB files for smaller file sizes.
      /config:<string>              The optional build config string from the build system.
      /copy:<sourceFile>            Copy the content source file verbatim to the output directory.
  /h, /help                         Displays this help.
  /i, /importer:<className>         Defines the class name of the content importer for reading source content.
  /I, /incremental                  Skip cleaning files not included in the current build.
  /n, /intermediateDir:<path>       The directory where all intermediate files are written.
  /d, /launchdebugger               Wait for debugger to attach before building content.
  /o, /outputDir:<path>             The directory where all content is written.
  /t, /platform:<targetPlatform>    Set the target platform for this build.  Defaults to Windows desktop DirectX.
  /p, /processor:<className>        Defines the class name of the content processor for processing imported content.
  /P, /processorParam:<name=value>  Defines a parameter name and value to set on a content processor.
  /g, /profile:<graphicsProfile>    Set the target graphics profile for this build.  Defaults to HiDef.
  /q, /quiet                        Only output content build errors.
  /r, /rebuild                      Forces a full rebuild of all content.
  /f, /reference:<assembly>         Adds an assembly reference for resolving content importers, processors, and writers.
  /w, /workingDir:<directoryPath>   The working directory where all source content is located.
```

Help menu on Unix:
```
MonoGame Content Builder
Builds optimized game content for MonoGame projects.

Usage: MGCB <Options>

Options:
  -@, --@=RESPONSEFILE              Read a text response file with additional command line options and switches.
  -b, --build=SOURCEFILE            Build the content source file using the previously set switches and options.
  -c, --clean                       Delete all previously built content and intermediate files.
      --compress                    Compress the XNB files for smaller file sizes.
      --config=STRING               The optional build config string from the build system.
      --copy=SOURCEFILE             Copy the content source file verbatim to the output directory.
  -h, --help                        Displays this help.
  -i, --importer=CLASSNAME          Defines the class name of the content importer for reading source content.
  -I, --incremental                 Skip cleaning files not included in the current build.
  -n, --intermediateDir=PATH        The directory where all intermediate files are written.
  -d, --launchdebugger              Wait for debugger to attach before building content.
  -o, --outputDir=PATH              The directory where all content is written.
  -t, --platform=TARGETPLATFORM     Set the target platform for this build.  Defaults to Windows desktop DirectX.
  -p, --processor=CLASSNAME         Defines the class name of the content processor for processing imported content.
  -P, --processorParam=NAME:VALUE   Defines a parameter name and value to set on a content processor.
  -g, --profile=GRAPHICSPROFILE     Set the target graphics profile for this build.  Defaults to HiDef.
  -q, --quiet                       Only output content build errors.
  -r, --rebuild                     Forces a full rebuild of all content.
  -f, --reference=ASSEMBLY          Adds an assembly reference for resolving content importers, processors, and writers.
  -w, --workingDir=DIRECTORYPATH    The working directory where all source content is located.
```

CC. @dellis1972 I think you are the only one who will appreciate this work here ༼ ༎ຶ ෴ ༎ຶ༽

### CODE REVIEW

**Comment by dellis1972** [comment]
I'm ok with this. Although I tend to use `msbuild` allot... so `/` arguments is normal for me :P

**Comment by KonajuGames** [comment]
As long as there are no plans to introduce different styles to the output
of the Pipeline Tool. The rule of file formats is to be strict with output
and flexible with input. This PR is the flexible with input side. The
strict with output side is the Pipeline Tool always writing with Windows
style.

**Comment by cra0zy** [comment]
@KonajuGames Yup, agreed.

**Comment by Jjagg** [comment]
I appreciate this work here ;)

**Comment by tomspilman** [comment]
@cra0zy - If you silently support `-` and `--` syntax on Windows too that allows people to write Unix style command lines that are cross platform.

**Comment by cra0zy** [comment]
> @cra0zy - If you silently support - and -- syntax on Windows too that allows people to write Unix style command lines that are cross platform.

The silent support is there, the only per platform that this is doing is the help menu we display.

**Comment by tomspilman** [comment]
Fantastic... thanks @cra0zy !

**Pull request merged**
