### PR TITLE
Added some more unit tests

### PR DESCRIPTION
**Pull request by dellis1972**
This PR adds a bunch of new tests.

1. Testing the processing of .dds CubeMaps.
2. Added Custom Model Processor Unit Tests

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 - What is the status of this?  What were you trying to fix?

**Comment by dellis1972** [comment]
I think it was just more tests.. We split out the scissor rec tests etc. This has Custom Model processing tests etc and some more Effect Tests.

**Comment by dellis1972** [comment]
I'll try to rebase and see if I can fix it up

**Comment by dellis1972** [comment]
@tomspilman looks like I need to fix up my new .dds Cube Map tests.

**Comment by cra0zy** [comment]
That's some big car.

**Comment by dellis1972** [comment]
@tomspilman looks like this is working now :)

**Comment by cra0zy** [comment]
Can we do something about the 86k lines 3D model, like switch it to a different format?

**Comment by dellis1972** [comment]
@cra0zy the point was to test the old format. This is one of the models that did not work from a large XNA demo.

**Pull request closed without merging**
