### PR TITLE
Upgrade Xamarin Studio Addin for Version 6.0

### PR DESCRIPTION
**Pull request by dellis1972**
This is the Update for Xamarin Studio 6.0. It is currently in Alpha so this should NOT be merged until it hits stable. However I will try to keep this branch update to develop so Xamarin Studio 6.0 users can use the build artifacts

### CODE REVIEW

**Comment by dellis1972** [comment]
Note this will fail until we upgrade the build bot with Xamarin Studios 6.. which will be when in goes stable. In the meantime I will keep the add updated over at addins.monodevelop.com so people with XS 6 can still work.

**Comment by dellis1972** [comment]
@tomspilman This is now good to go. But we need to upgrade the Mac Bot to the latest Stable release

**Comment by cra0zy** [comment]
MonoDevelop 6 is not out yet.

**Comment by dellis1972** [comment]
XS 6 Shipped today

**Comment by cra0zy** [comment]
> XS 6 Shipped today

Oh, didn't realize that, mostly because they didn't update the website :/ http://www.monodevelop.com/download/

**Comment by tomspilman** [comment]
@dellis1972 - So it is safe for me to update the build machines?

**Comment by dellis1972** [comment]
@tomspilman well the stuff is all in stable so I think so. 
Watch out there is a new Mono version so Nant might break.

**Comment by tomspilman** [comment]
@dellis1972 - So I updated XS on the Mac build machine, but it still says it is 5.8.3 and not a 6.x of any sort.  It doesn't show any other updates available in the stable channel either.

**Comment by cra0zy** [comment]
@tomspilman Can you try updating the XS on Mac again?

**Comment by dellis1972** [comment]
The Mac needs to be upgraded to El Capitan to install XS6 :(

**Comment by cra0zy** [comment]
> The Mac needs to be upgraded to El Capitan to install XS6 :(

Bummer :(

**Comment by tomspilman** [comment]
> The Mac needs to be upgraded to El Capitan to install XS6 :(

I can do that...  it will just halt the build process for a few hours.

Let's clear a few other PRs first.

**Comment by cra0zy** [comment]
I have some bad news, MonoDevelop 6 has not yet been released for Linux... so even if you do update the server we are still kind of stuck...

**Comment by dellis1972** [comment]
hmmmmm.

**Comment by tomspilman** [comment]
I guess I can still do the "El Capitan" upgrade... old XamStudio should still work right?  Or should I wait?

**Comment by cra0zy** [comment]
I vote for updating now.

**Comment by dellis1972** [comment]
@cra0zy I think we'll need to ship the XS6 Addin with the installer and people using MD 5 can get the old one from the Addin Manager. So we might need to do an update to that to include the SDL stuff somehow (if we've not done that already)

**Comment by cra0zy** [comment]
Yea, I am fine with using the XS6 addin by default with the installer, hopefully they release an update to MD for Linux soon...

On a side note updating build server may help with https://github.com/mono/MonoGame/pull/4904#issuecomment-229206242 since the .app file I build with XS works fine, but the one the build server builds doesn't.

**Comment by tomspilman** [comment]
@cra0zy  @dellis1972 - So the Mac build box is upgraded and now running XS6.  I just rebuilt this PR successfully.  This ok to merge now?

@cra0zy - Is there a Linux update for XS6 now?

**Comment by cra0zy** [comment]
> @cra0zy - Is there a Linux update for XS6 now?

Do not wait for Linux.... the full native packages have been dropped and the new flatpak packages is too buggy to be used.

**Pull request merged**
