### PR TITLE
Reduce chance of losing mouse events due to Mouse.SetPosition()

### PR DESCRIPTION
**Pull request by bartwe**
Reduce chance of losing mouse events or reading stale data due to Mouse.SetPosition's potential async delay.

It does this by waiting to read mouse state till after the Wait for the start of the framelimiter, (avoids some input lag)
Then determining the delta of mouse movement since the previous frame, then applying that delta to the requested SetPosition (this avoids losing some of the mouse movement)
This also ensures the least time is lost between GetCursorPos and SetCursorPos and the most time is between the previous SetCursorPos and the next GetCursorPos

This is not a complete fix as SetCursorPos can have a non-zero delay before having an effect on GetCursorPos which can lose some mouse input or in extreme cases cause the recenter to not happen by the next frame of the game causing phantom input as per https://github.com/MonoGame/MonoGame/issues/6262#issuecomment-417878184

image

### CODE REVIEW

**Comment by mrhelmut** [comment]
Thanks Bart!
My only concern right now is that it breaks non-Windows platforms. I would suggest to find a way to pass the window handle to the mouse code without breaking ```PlatformSetPosition``` in the ```Mouse``` class.

**Comment by bartwe** [comment]
I am wondering about the UWP/WinRT, it is not clear to me what parts they do and don't share with winforms in this context.

**Comment by bartwe** [comment]
Check fail is due to 'nuget ICSharpCode.SharpZipLib' ? i haven't touched anything close to that..

**Comment by mrhelmut** [comment]
Thanks for the update. Fine to me. I'll leave this to other eyes regarding ```TickWait()``` and ```TickRun```.

**Comment by bartwe** [comment]
Hi, would this be more mergable without the TickWait/Run bit, i can remove that i guess, would make it less effective

**Comment by mrhelmut** [comment]
Summoning @Jjagg and @cra0zy to have their thoughts.

**Comment by Jjagg** [comment]
For the input lag, IMO it makes a lot more sense to 

1. Process events
2. Update
3. Wait

in that order rather than waiting after processing events. I would like to change that for ALL platforms, but it might have little side effects that can break behavior that some users rely on. So I don't think we should merge this casually and might want to keep that change for a new major version (4.0).

> Reduce chance of losing mouse events or reading stale data

By stale data you mean getting the cursor position does not immediately reflect the set cursor position? By losing events you mean mouse movement that happens during the wait in the game loop is lost because the cursor has not actually moved yet? 
We could use a message mask with `GetMessage`/`PeekMessage` to process the cursor position message right after calling SetPosition. In combination with reordering wait and update as stated above I think that should fix the issue.

**Comment by bartwe** [comment]
I don't think waiting after the update makes sense seeing as MG doesn't have enough information on when vsync happens, and we want to minimize the time between sampling input and having the resulting gamestate rendered to the screen.

@Jjagg the core problem is that when SetCursorPos goes into effect can have a delay on windows,(as the mouse is a resource owned by the kernel, this delay can be more than 16ms in extreme cases) losing mouse movement that happened between the previous GetCursorPos and the moment the SetCursorPos goes into effect.
Placing them next to eachother minimizes this loss but is no guarantee, that requires switching to rawevents (mrgrak made an implementation of this i believe)

**Comment by bartwe** [comment]
How can i restart this check, the failure is unrelated to the change.

**Comment by tomspilman** [comment]
@bartwe - there have been changes to `develop` branch that the build server requires.  You will need to merge the latest develop into this branch to make it successfully kick off a build.

**Comment by SimonDarksideJ** [comment]
@bartwe can you retest this PR with the latest develop branch and verify if the issue still exists.  Were you able to resolve @Jjagg and @mrhelmut  queries?

**Comment by SimonDarksideJ** [comment]
Any update @bartwe or can this be closed now?

**Comment by bartwe** [comment]
Feel free to close

**Pull request closed without merging**
