### PR TITLE
[DesktopGL] Fix window not getting updated

### PR DESCRIPTION
**Pull request by Jjagg**
Provides a minimal fix for the issue described in #5486. 
Since 3.6 is around the corner I decided to just make minimal changes needed to get this working again. Once this is merged I'll make further improvements for after 3.6. @dellis1972

### CODE REVIEW

**Comment by Jjagg** [comment]
Oh, hold on this might not be ready yet.

**Comment by dellis1972** [comment]
@Jjagg this is working, but on MacOS using Ctrl+Cmd+F or the green maximise (which toggles full screen) does not appear to update the IsFullScreen setting. I'm sure it used to since I needed that to work in the Stardew Valley port.

**Comment by dellis1972** [comment]
@Jjagg ok maybe not. Looks like its an existing bug.

**Comment by polsys** [comment]
On DesktopGL, the `GraphicsDeviceManagerFixtureTest.ClientSizeChangedOnDeviceReset` test is failing. I did not trace it any further, but could it be related to this? If I understand correctly, this PR adds another path that may raise a `ClientSizeChanged` event.

There's also another failing `GraphicsDevice` test, caused by some recent commit.

**Pull request merged**
