### PR TITLE
Begin show keyboard uap xaml

### PR DESCRIPTION
**Pull request by madninjaskillz**
Add support for Guide.BeginShowKeyboard/Guide.EndShowKeyboard to UAP Xaml projects.

Have tried to ensure does not need any changes to existing projects, nor force a requirement for Framework.Net dll when you are not using Guide.

Style wise I have tried to keep the feel of 360 XNA whilst also using native design rules.

Supports standard and Password Boxes.

guide beginshowkeyboard2

### CODE REVIEW

**Comment by madninjaskillz** [comment]
I'm not sure why its not building here now (and I'm not sure if I should have included the csproj to include the extra files needed) and it seems to build here on UAP and android fine, so any guidance on repairing the build would be super appreciated. (and sorry for any inconvenience caused)

**Comment by SimonDarksideJ** [comment]
@madninjaskillz are you able to resolve the merge conflicts on the PR, or do you not wish to take this functionality forward now?

**Comment by mrhelmut** [comment]
We'll be dropping UAP/UWP once the Direct3D12 backend is ready. Likely not worth.

**Comment by SimonDarksideJ** [comment]
That was my thinking, beyond 3.8.2, UWP/UAP will likely be dropped as it doesn't fit a MonoGame deployment approach for desktop/consoles (especially with the dropping of UWP for Xbox)

Closing PR for now

**Pull request closed without merging**
