### PR TITLE
[Pipeline Tool] Native Mac Version

### PR DESCRIPTION
**Pull request by cra0zy**
~~This will fail to build, this is because I didn't add Eto.XamMac/MonoMac dll file.~~

~~@dellis1972 When you get the chance could you please add the correct Eto.Mac dll file, I have no idea what the build server is using, and testing them one by one will take me to long with the VM. Locally I've used https://www.nuget.org/packages/Eto.Platform.XamMac2/ for testing, tho we should use Mac dll compiled from: https://github.com/cra0zy/Eto/tree/monogame Also you may need to change Platform in Program.cs (talking about just an enum value).~~

Screenshot:
macpip

### CODE REVIEW

**Comment by cra0zy** [comment]
I just realized that I didn't need to call a single native function on Mac, wow, well even tho it compiled it still needs Eto.Mac dll file.

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 - So is this good to merge?

**Comment by cra0zy** [comment]
> @cra0zy @dellis1972 - So is this good to merge?

It's still missing Eto.Mac dll file, and I don't know what Xamarin version is installed on the build server. There are MonoMac, XamMac, XamMac2

I guess I could try adding Eto.XamMac2 to dependencies and hope for the best.

**Comment by dellis1972** [comment]
@cra0zy now that XamMac2 is free we should probably upgrade the Pipeline project to use that rather than MonoMac. Then we can just use the Nuget package.. maybe..

**Comment by cra0zy** [comment]
> @cra0zy now that XamMac2 is free we should probably upgrade the Pipeline project to use that rather than MonoMac. Then we can just use the Nuget package.. maybe..

Currently Pipeline project is using Gtk 2.

**Comment by cra0zy** [comment]
Yey, it builds. I used NuGet packages for Mac.

For Mac we will need to use stable packages because of: 
 - https://github.com/picoe/Eto/issues/524

For LInux we will need to keep using develop packages because of:
 - https://github.com/picoe/Eto/issues/478
 - https://github.com/picoe/Eto/issues/430

**Comment by cra0zy** [comment]
Just FYI, I finished the xwt multiselect treeview, once this gets merged I'll submit it since it's gonna have merge conflicts.

**Comment by dellis1972** [comment]
Hmm. Pipeline app from this PR crashes on startup on Mac. No idea why yet.

**Comment by dellis1972** [comment]
Hmm. https://gist.github.com/dellis1972/419cd0a4b5464e895e7792bf856225eb

**Comment by cra0zy** [comment]
Hmm, https://github.com/cra0zy/MonoGame/blob/13531231d9418e2f8f0950c2b0fcfda0c7a996ca/Tools/Pipeline/Program.cs#L20

**Comment by cra0zy** [comment]
So testing out the installer and... it's not creating Pipeline shortcut in the launchpad and it's not adding Pipeline.app to Applications... I am so confused O o

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 - Should we hold this back to 3.7?

**Comment by cra0zy** [comment]
Pipeline Tool for Mac was already broken, so it was either me fixing the Gtk one, or doing this, and this seemed like a better decision.

**Comment by cra0zy** [comment]
Also I couldn't get the Mac installer to work in general, not just for this PR.

**Comment by tomspilman** [comment]
Then for sure we need to fix that before we can ship 3.6.  @dellis1972 ?

I really need to get some form of installer testing to catch this in the future.

**Comment by dellis1972** [comment]
@tomspilman @cra0zy   Pipeline tool not working is a blocker for 3.6. So we either a) Fix this PR so it works or b) Fix the Pipeline as it stands in develop.

**Comment by tomspilman** [comment]
> a) Fix this PR so it works or b) Fix the Pipeline as it stands in develop.

I'm fine with either A or B...  just need to get the issue fixed as soon as possible.

**Comment by dellis1972** [comment]
@cra0zy btw the reason why the installer probably doesn't put the Pipeline tool in Applications on your mac is probably because you're run it at least once from the IDE.. If that case OSX unhelpfully remembers where you ran it from and will install stuff there instead. You need to manually run 

'sudo pkgutil --forget com.monogame.pipeline'

after deleting all the Pipeline.app folders (including those in bin/Debug|Release )

**Comment by cra0zy** [comment]
Wow that is silly, anyway now it installs, yey... time to figure out how it needs to be packaged.

**Comment by cra0zy** [comment]
@cwensley Did you by any chance experience https://gist.github.com/dellis1972/419cd0a4b5464e895e7792bf856225eb with Eto XamMac application?

**Comment by cwensley** [comment]
@cra0zy that'll happen if there's a problem initializing the platform, or that the Eto.XamMac.dll or Eto.XamMac2.dll assemblies aren't included with your app.

It could also be that you're doing something funky with threads, or not running using the .app bundle.

You could try creating an instance of Eto.Mac.Platform specifically to track down the issue:  e.g. `new Application(new Eto.Mac.Platform()).Run(new MainForm())`

**Comment by cra0zy** [comment]
> @cra0zy that'll happen if there's a problem initializing the platform, or that the Eto.XamMac.dll or Eto.XamMac2.dll assemblies aren't included with your app.

 - The app works fine when launched from debugger.
 - Assemblies did get included in the app package.

**Comment by cwensley** [comment]
@cra0zy are you using the linker?  it can (and usually does) strip out pretty much everything useful.

**Comment by cra0zy** [comment]
> @cra0zy are you using the linker? it can (and usually does) strip out pretty much everything useful.

I don't know.. tho I thought only Android and iOS really used it. Will check.

**Comment by cra0zy** [comment]
I think this has something to do with the build server, It seems that launching .app from the Debug folder works fine, so maybe the installer is doing something fishy.

@cwensley Thanks for the help.

**Comment by cra0zy** [comment]
> I think this has something to do with the build server, It seems that launching .app from the Debug folder works fine, so maybe the installer is doing something fishy.

Or maybe an outdated version of Xamarin.Mac may be the problem.

**Comment by tomspilman** [comment]
What is the status of this @cra0zy ?

**Comment by cra0zy** [comment]
There are 2 bugs that I need to resolve that are Mac only, which will be easy now that the other Pipeline Tool fixes have been merged, but It turned out that a small fix to propertygrid I did in #4998 was more important than I thought... Anyway, if you can, do look into merging that PR before this so I don't have to take out that fix for a separate PR.

**Comment by cra0zy** [comment]
The 2 bugs that remain are:
 - add existing file dialog can't select anything because *.* is not a valid filter on Mac
 - left right splitter can't be moved

Right now my Mac VM is dead, it's gonna take me some time to get another one working, so if someone wants to take over this PR that would be awesome.

**Comment by kennethsuda** [comment]
> - add existing file dialog can't select anything because *.* is not a valid filter on Mac
Looking at the eto mac code, the only current way of allowing any file is by not setting a filter for that dialog. Once you set a filter, then it only will find extensions that match. So for dialogs that take just any file, remove setting the filter and current filter. For those that set a particular filter, it could either be remove the filters all together or removing the any filter. Removing just the any filter, would force the extension, i.e. MGCB file would always have to be .mgcb. I did test removing it from Add Existing, and it selected files fine.

> - left right splitter can't be moved
This is beyond my ability to figure out. It is actually resizing and then moving back in the same event. I suspect something has gotten crossed with a difference between what the size of the scrollable's draw region should be and the size of the visual rect. Anything I did seemed to have no effect or if it let me resize, stopped drawing the content.

Another thing that I did notice was that some of the values didn't seem to fit properly in the display. It would scroll horizontally sometimes.

For the purposes of moving forward, having the left/right splitter not working is minor in comparison to the inability to add existing files.

**Comment by dellis1972** [comment]
@cra0zy can you rebase this one?

**Comment by cra0zy** [comment]
> @cra0zy can you rebase this one?

Rebased, tho I can't test it.

**Comment by dellis1972** [comment]
@cra0zy ok I'll see if I can take a look. do I still have push rights to your repo?
Although this looks worrying :/

'XwtUtil.cs(14,42): error CS0246: The type or namespace name `Gtk' could not be found. Are you missing an assembly reference?'

btw I noticed an issue with the Pipeline tool. I have to double click on combo boxes to get it to dropdown. Any chance we can change that? It feels kinda funky.

**Comment by cra0zy** [comment]
> 'XwtUtil.cs(14,42): error CS0246: The type or namespace name `Gtk' could not be found. Are you missing an assembly reference?'

Ups, I forgot to include the file for mac.

**Comment by cra0zy** [comment]
> @cra0zy ok I'll see if I can take a look. do I still have push rights to your repo?
> Although this looks worrying :/

You do. I will notify you if I ever remove your permissions.

> btw I noticed an issue with the Pipeline tool. I have to double click on combo boxes to get it to dropdown. Any chance we can change that? It feels kinda funky.

develop version should have it actiuvate with single click

**Comment by cra0zy** [comment]
@dellis1972 The thing that is missing is in: https://github.com/MonoGame/MonoGame/blob/develop/Tools/Pipeline/XwtUtil.cs#L11

I don't know what is the type of XamMac controls.

**Comment by dellis1972** [comment]
cool :) cool and cool :)

**Comment by cra0zy** [comment]
It's alive ALIVE!!!

**Comment by tomspilman** [comment]
@cra0zy - Rebase with the latest develop branch and it should fully build.

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 - So is this good to merge?

**Comment by cra0zy** [comment]
I have no idea, as stated above me Mac VM is dead :/

**Comment by tomspilman** [comment]
I guess we wait to see what @dellis1972 says.

**Comment by dellis1972** [comment]
@cra0zy I get the following error

'Toolkit could not be loaded ---> System.IO.FileNotFoundException: Could not load file or assembly 'Xwt.XamMac, Version=0.1.0.0' or one of its dependencies'

Looks like we are missing an assembly

**Comment by cra0zy** [comment]
@dellis1972 ups..

https://github.com/cra0zy/MonoGame/blob/61445dffd98ab13b2215bc3668003f73401b5ef3/Build/Projects/PipelineReferences.definition#L49

should point to

https://github.com/MonoGame/MonoGame.Dependencies/blob/a82c40d9e607711d25448bb05b349a7de5631713/xwt/Xwt.XamMac.dll

**Comment by dellis1972** [comment]
@cra0zy I'm testing this branch out now. I'll merge if it works, but you will need to rebase (I had to hack some files locally)

**Comment by dellis1972** [comment]
@cra0zy not looking good :( I get the menu bar with just "Pipeline.MacOS" in it and the icon but no Main window.

**Comment by cra0zy** [comment]
I made this using Eto 2.2 so make sure you are using that version.

Another thing that could be causing the problem would maybe be Xwt? Try to comment out projectview stuff and see what happens.

**Comment by cra0zy** [comment]
@dellis1972 Good news, I'll be able to work on this on Monday :) Just make sure you're around that they so you can test this.

**Comment by cra0zy** [comment]
I had to postpone the work I was planning on doing for 2 days (Xamarin.Mac was not installed on the device).

**Comment by cra0zy** [comment]
Xwt is causing the problem, I will have to remove it completely for this to be possible, which I am willing to do.

**Comment by dellis1972** [comment]
@tomspilman @KonajuGames  @cra0zy as far as I know this PR/issue is blocking a 3.6 release. 
We need to figure out a way to either

a) get this PR fixed
or
b) revert the changes made since 3.5 to the Pipeline tool so that it works on Mac.

having a non functioning Pipeline app on Mac is kinda a big issue especially as we tend to tell people to use the development version allot.

thoughts ? comments?

**Comment by cra0zy** [comment]
I already started working on a fix for this PR. Stuff done:
 - Step 1: #5399 maybe fixes the ProjectView on Mac
   - If not, submit a PR using https://github.com/cra0zy/MonoGame/tree/etotreeview which adds etotreeview only for Mac
 - Step 2: Do some final fixups

For some reason I do feel a bit irritated after reading your comment, can't quite put my finger on what irritates me...

**Comment by dellis1972** [comment]
hey @cra0zy sorry it irritated you, it wasn't meant to :) I probably could have worded it a bit better. I'll try and take a look at the stuff you've been doing over the weekend if I can :)

**Comment by cra0zy** [comment]
It's not your wording, but your idea, you propose 2 options (fix or revert) while you could clearly see that I submitted a PR 2 hours prior to your comment that's attempting to fix some stuff for this (all the changes in #5399 are needed by this PR), plus in the comment above I already said what is causing the problem in this PR.

**Comment by dellis1972** [comment]
@cra0zy I didn't see the PR from 2 hours ago, otherwise I wouldn't have posted the comment, sorry. for some reason I'm not getting GitHub notifications.

**Comment by cra0zy** [comment]
Well.. it compiles now:

pipeline

**Comment by cra0zy** [comment]
Well most of the things now work, feel free to download and test it.
pipeline

Stuff that does not work fully:
 - PropertyGrid and BuildOutput are a bit larger on Width because I can't find how big is the scrollbar width
 - ProjectView does not have multiselect

**Comment by cra0zy** [comment]
This should be ready for merged now. As for the remaining 2 issues from above:
 - PropertyGrid and BuildOutput are a bit larger on Width because I can't find how big is the scrollbar width
   - I will be trying to make Etos ScrollView consistent between platforms, it will take a bit of time but once done it should be much easier to maintain custom drawable controls
 - ProjectView does not have multiselect
   - Probably wait for admin of Eto to be done with the new TreeGridView, I asked him last week what is the progress of it and he said that Gtk and macOS were mostly done

**Comment by dellis1972** [comment]
The Tools from the built package runs up now, but hitting build results in a crash of the entire app. I'll try and get more info if I can.

**Comment by cra0zy** [comment]
For me it builds stuff just fine... (or should I say fails to build just fine :P, screenshot above).

Also think about merging this PR ASAP so that there is enough time for people to test it before 3.6 release.

**Comment by Jjagg** [comment]
> Also think about merging this PR ASAP so that there is enough time for people to test it before 3.6 release.

I think it's the other way around. 3.6 won't be released until this is properly tested :p

**Comment by dellis1972** [comment]
If anyone wants to test the Pipeline tool from this PR you can download the Pipeline.MacOS.pkg file from this location http://teamcity.monogame.net/viewLog.html?buildId=32151&buildTypeId=MonoGame_PackageMacAndLinux&tab=artifacts

Or get the entire MonoGame.pkg

**Comment by cra0zy** [comment]
There are 6 people in this discussion, I don't think we'll find anyone more to test the PR...

**Comment by cra0zy** [comment]
@dellis1972 Did you find out why the Pipeline Tool was crashing for you when you hit build? Did you get any type of error?

**Comment by dellis1972** [comment]
I get a Segfault 11 thats it when I run the 'Pipeline" app manually from
within the package.
When I build locally it doesn't run saying its missing System.Runtime.dll
(which is present).
It might be I'm running Alpha Xamarin.Mac, just updating and trying again.

**Comment by dellis1972** [comment]
@cra0zy which version of Xamarin.Mac are you running? Its not working for me :(

**Comment by cra0zy** [comment]
Newest stable release, you can't compile it?

**Comment by dellis1972** [comment]
I can compile but it won't run in the debugger.

**Comment by dellis1972** [comment]
Upgrading to Framework 4.6.1 fixes the issues in the IDE. Running in the
IDE doesn't produce the crash on build :/

Will build a release package and see if that works

**Comment by dellis1972** [comment]
one thing I did notice is the Add New Item dialog does not list any
templates.

**Comment by cra0zy** [comment]
> one thing I did notice is the Add New Item dialog does not list any
> templates.

I noticed that too, I thought it was due to packaging.

**Comment by cra0zy** [comment]
@dellis1972 The Pipeline Tool from the build server is crashing for me when the build is hit, while if I build the Pipeline Tool in release mode locally, and install it into Applications it works fine. I'm guessing the Mac build bot needs an update.

**Comment by KonajuGames** [comment]
Mac Pipeline tool is currently broken, so merging this to try to make it better.

**Pull request merged**
