### PR TITLE
Fixes Assembly.GetEntryAssembly() can be null when called from nunit

### PR DESCRIPTION
**Pull request by james0x0A**
#5274

### CODE REVIEW

**Comment by tomspilman** [comment]
This seems like a reasonable way to prevent this crash in special cases like the unit tests.

(had to use the `?w=0` whitespace trick to see the diff clearly)

@KonajuGames @dellis1972 ?

**Comment by tomspilman** [comment]
@Jjagg @dellis1972 @cra0zy - Thoughts?

**Comment by Jjagg** [comment]
This is fine. A comment that explains why this is necessary would be nice though.

**Comment by cra0zy** [comment]
This is not fine, add a null check instead of a try catch.

**Comment by tomspilman** [comment]
Yeah I agree with @cra0zy ...  if a `null` check is all we need here then replace the `try` with `if (Assembly.GetEntryAssembly() != null)`.

**Comment by KonajuGames** [comment]
The `catch { }` may hide other legitimate errors.

**Comment by cra0zy** [comment]
Side note, if you upgrade the windows build bot it will be easier to add null checks, ie:
```c#
Assembly.GetEntryAssembly()?.GetManifestResourceStream(Assembly.GetEntryAssembly().EntryPoint.DeclaringType.Namespace + ".Icon.bmp") ??
Assembly.GetEntryAssembly()?.GetManifestResourceStream("Icon.bmp") ??
Assembly.GetExecutingAssembly()?.GetManifestResourceStream("MonoGame.bmp"))
```

C# 6 has nice `var?.method()` null check :)

**Comment by tomspilman** [comment]
>C# 6 has nice var?.method() null check :)

I am aware of that... we're not going to do that yet.

**Comment by tomspilman** [comment]
This was fixed by https://github.com/MonoGame/MonoGame/pull/5764.  Thanks for alerting us to the issue @james0x0A !

**Pull request closed without merging**
