### PR TITLE
Update file, only a few minor changes

### PR DESCRIPTION
**Pull request by Paranoid17**
Basically, I added a brief message, someone may find it interesting to fill it later.

### CODE REVIEW

**Comment by Jjagg** [comment]
@cra0zy We should fix this file. All you need to compile most of MG is msbuild or for the newer projects the dotnet SDK.
For the Pipeline Tool do you still need the listed things installed to build it correctly?

**Comment by cra0zy** [comment]
Well the building instructions are incorrect at this stage.

**Comment by Jjagg** [comment]
So we finish Protobuild removal first?

**Comment by cra0zy** [comment]
Yes.

**Pull request closed without merging**
