### PR TITLE
Fixed DirectX back buffer update when multisampling changes

### PR DESCRIPTION
**Pull request by zigzag312**
Fixes issue of multisampling not working & nothing being drawn when multisampling is changed mid-game. https://github.com/MonoGame/MonoGame/issues/358#issuecomment-288793036 https://github.com/MonoGame/MonoGame/issues/358#issuecomment-288967105

### CODE REVIEW

**Comment by Jjagg** [comment]
Looks like issues on the Mac build bot
```
 Error while applying patch: Failed to chmod: /Applications/buildAgent/work/59a4b66548a5cef5/Installers/MacOS/Scripts/Pipeline/postinstall 
```

**Comment by zigzag312** [comment]
Why does it fail? Issues with build server?

**Comment by Jjagg** [comment]
Yeah, definitely not because of changes in this PR. @tomspilman Any idea what's up?

**Comment by tomspilman** [comment]
Yeah something weird happened on the build server... not sure what.  I re-ran the build and it is working now.

**Comment by Jjagg** [comment]
The changes here cause issues when in full screen mode. Changing ms count in soft full screen doesn't do anything and in mode switched full screen it causes a crash. I should mention I didn't test this branch directly, but applied the changes to my branch from #5585. Maybe things are better in this branch, but this and #5585 should play nice together so I'll see if I can fix my PR so it works correctly in combination with the changes here.

I can confirm that this does work when not in full screen.

**Comment by zigzag312** [comment]
Good catch. Previously _swapChain was never recreated, but I haven't found any method similar to SwapChain.ResizeBuffers(...) that would update multisampling count on swap chain. So old swap chain is disposed and recreated from scratch, but I am not sure it should be done this way. 

It crashes when it tries to create new swap chain.
`_swapChain = new SwapChain(dxgiFactory, dxgiDevice, desc);`

**Comment by zigzag312** [comment]
Issues when in full screen mode should be fixed now.

**Comment by zigzag312** [comment]
Can someone review this:  https://github.com/zigzag312/MonoGame/blob/61c6aca577c7b0d8115fd01214a429cb7e4bdb19/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L747

**Comment by Jjagg** [comment]
Yes, you can use PresentationParameters because the value in there is what we want the full screen state to be. So should be `isWindowed = pp.IsFullScreen && pp.HardwareModeSwitch`. I vaguely recall initializing the swap chain in full screen causing some issues though, so maybe it's better to initialize it windowed and then call `SetHardwareFullscreen`.

**Comment by zigzag312** [comment]
@Jjagg Do you have any suggestion where to put SetHardwareFullscreen?

It seems you remember correctly :) I found following remarks regarding creating full screen swap chain:

- If a Windows Store app calls CreateSwapChain with full screen specified, CreateSwapChain fails.
- Because the target output can't be chosen explicitly when the swap chain is created, we recommend not to create a full-screen swap chain. This can reduce presentation performance if the swap chain size and the output window size do not match. Here are two ways to ensure that the sizes match:
  - Create a windowed swap chain and then set it full-screen using IDXGISwapChain::SetFullscreenState.
  - Save a pointer to the swap chain immediately after creation, and use it to get the output window size during a WM_SIZE event. Then resize the swap chain buffers (with IDXGISwapChain::ResizeBuffers) during the transition from windowed to full-screen.

[IDXGIFactory::CreateSwapChain method (Windows)](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174537(v=vs.85).aspx#NOTES_FOR_WINDOWS_STORE_APPS)

**Comment by Jjagg** [comment]
> Do you have any suggestion where to put SetHardwareFullscreen?

It's already defined here: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L676

**Comment by zigzag312** [comment]
Changed to always create a windowed swap chain and then set it full-screen if needed. 

It only changes new swap chain to full screen, if old swap chain was already full screen. So it doesn't conflict with EnterFullScreen() method that needs to save Form location before entering full screen.

**Comment by Jjagg** [comment]
@KonajuGames Could you take a look at getting this merged? I can confirm this fixes changing MSAA at runtime.

**Comment by tomspilman** [comment]
@zigzag312 @Jjagg - Could you guys look at...

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/SwapChainRenderTarget.cs

... and see if it needs a similar fix?

Also would be nice one day for that to work on OpenGL too.

**Comment by tomspilman** [comment]
Thanks @zigzag312 ... merging!

**Comment by zigzag312** [comment]
@tomspilman SwapChainRenderTarget is missing clamping on preferredMultiSampleCount. But I don't see other issues like here, as that swapchain never changes once created and is always windowed. I can make PR for clamping.

**Pull request merged**
