### PR TITLE
Added microphone support (PR3019)

### PR DESCRIPTION
**Pull request by wmartin129**
Not sure where to post a sample app, so I'll just dump it here and hope it's ok:

``` csharp
using System;
using System.Threading;
using Microsoft.Xna.Framework.Audio;

namespace playground
{
    class MainClass
    {
        private static Microsoft.Xna.Framework.Audio.Microphone mic;
        private static int bufferIndex = 0;
        private static byte[] data;

        public static void Main(string[] args)
        {
            // List out all audio capture devices
            Console.WriteLine("Capture devices:");
            foreach (var device in Microsoft.Xna.Framework.Audio.Microphone.All)
                Console.WriteLine("\t" + device.Name);

            // Use default capture device
            mic = Microsoft.Xna.Framework.Audio.Microphone.Default;
            Console.WriteLine("\nUsing default capture device:\n\t" + mic.Name);

            // Prepare record buffer for 5 seconds use
            TimeSpan recDuration = TimeSpan.FromSeconds(5);
            mic.BufferDuration = TimeSpan.FromSeconds(1);
            data = new byte[mic.GetSampleSizeInBytes(recDuration)];

            // Bind event handler for when audio data becomes available
            mic.BufferReady += DataAvailable;

            // Record audio for 5 seconds
            mic.Start();
            Console.WriteLine("Recording...");
            Thread.Sleep(recDuration);
            mic.Stop();

            // Replay audio
            Console.WriteLine("Playing...");
            using (SoundEffect sound = new SoundEffect(data, 44100, AudioChannels.Mono))
                sound.Play();

            Console.ReadLine();
        }

        private static void DataAvailable(object sender, System.EventArgs e)
        {
            // Prepare buffer for available samples
            byte[] samples = new byte[mic.GetSampleSizeInBytes(TimeSpan.FromSeconds(1))];

            // Read available samples into our buffer
            int sampleSize = mic.GetData(samples);

            // Merge these samples into our overall buffer and don't overrun it
            int cropSize = sampleSize + bufferIndex > data.Length ? data.Length - bufferIndex : sampleSize;
            System.Array.Copy(samples, 0, data, bufferIndex, cropSize);
            bufferIndex += cropSize;
        }
    }
}
```

### CODE REVIEW

**Comment by Shqrdx** [comment]
@tomspilman I spended few hours of testing this PR. Good news - it worked ! Bad news - not in the current implementation of SoundEffect for OpenGL. MonoGame for WinGL cannot writes byte array into it for playing the result. And another issue - openal32.dll - it must be copied to output directory of any WinGL project in order to play or record sounds. How to test ?
1. create Windows XNA Game empty project
2. paste classes from this PR into other namespace(MyMic) and use the followed code for Game class

like this

```C#
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.InteropServices;
using System.Threading;
using OpenTK.Audio;
using OpenTK.Audio.OpenAL;

namespace MyMic
{
    /// <summary>
    /// The exception thrown when no microphone is present, or driver issues are detected.
    /// </summary>
    //[DataContract]
#if WINRT
	public sealed class NoMicrophoneException : Exception
#else
    public sealed class NoMicrophoneException : ExternalException
#endif
    {
        /// <param name="msg">A message describing the error.</param>
        public NoMicrophoneException(string msg)
            : base(msg)
        {
        }

        /// <param name="msg">A message describing the error.</param>
        /// <param name="innerException">The exception that is the underlying cause of the current exception. If not null, the current exception is raised in a try/catch block that handled the innerException.</param>
        public NoMicrophoneException(string msg, Exception innerException)
            : base(msg, innerException)
        {
        }
    }

    /// <summary>Describes the state of a Microphone instance.</summary>
    public enum MicrophoneState
    {
        /// <summary>The Microphone audio capture has started.</summary>
        Started,

        /// <summary>The Microphone audio capture has stopped.</summary>
        Stopped
    }

    /// <summary>
    /// Represents a physical microphone
    /// </summary>
    public sealed class Microphone
    {
        // The fixed sample rate used by the microphone class in Hz
        private const float SAMPLE_RATE = 44100f;

        // Calculate 10ms alignment value for sample rate (i.e. how many bytes of data is required every 10ms at the sample rate speed)
        private int alignOn = Convert.ToInt32(SAMPLE_RATE*2f/100f);

        private TimeSpan _bufferDuration;
        private static ReadOnlyCollection<Microphone> _all;
        private MicrophoneState _microphoneState = MicrophoneState.Stopped;
        private AudioCapture capture;
        private Thread pollBufferThread;

        #region Public Fields

        public string Name { get; private set; }

        #endregion

        #region Public Properties

        /// <summary>
        /// Returns the collection of all currently-available microphones
        /// </summary>
        /// <value>The collection of microphones</value>
        public static ReadOnlyCollection<Microphone> All
        {
            get
            {
                if (_all == null)
                {
                    List<Microphone> _allList = new List<Microphone>();

                    // Fill collection with data found using OpenTK.Audio.AudioCapture.AvailableDevices
                    foreach (string deviceName in OpenTK.Audio.AudioCapture.AvailableDevices)
                    {
                        Microphone newMic = new Microphone();
                        newMic.Name = deviceName;
                        _allList.Add(newMic);
                    }
                    _all = new ReadOnlyCollection<Microphone>(_allList);
                }
                return (_all);
            }
        }

        /// <summary>
        /// Gets or sets audio capture buffer duration of the microphone
        /// </summary>
        /// <value>The duration of the audio capture buffer</value>
        public TimeSpan BufferDuration
        {
            get { return (_bufferDuration); }
            set
            {
                double check = value.TotalMilliseconds;
                if (check < 100f || check > 1000f || check%10f != 0f)
                    throw new ArgumentOutOfRangeException();

                // TODO: Once FrameworkDispatcher stub is complete we must ensure its Update 
                // method has been called at least once, or we should throw InvalidOperationException

                _bufferDuration = value;
            }
        }

        /// <summary>
        /// Returns the default attached microphone
        /// </summary>
        /// <value>The default microphone; returns null if there are no microphones attached</value>
        public static Microphone Default
        {
            get
            {
                if (_all.Count == 0)
                    return (null);

                string defaultDevice = OpenTK.Audio.AudioCapture.DefaultDevice;
                foreach (Microphone mic in All)
                {
                    if (mic.Name == defaultDevice)
                        return (mic);
                }
                return (null);
            }
        }

        /// <summary>
        /// Determines if the microphone is a wired headset or a Bluetooth device
        /// </summary>
        /// <value>If the microphone is a headset, the value is <c>true</c>; otherwise it is <c>false</c></value>
        public bool IsHeadset
        {
            get
            {
                // TODO: Find work around as openal does not provide this information
                return (false);
            }
        }

        /// <summary>
        /// Returns the sample rate at which the microphone is capturing audio data
        /// </summary>
        /// <value>Sample rate of audio data being captured, in Hertz (Hz)</value>
        public int SampleRate
        {
            get { return (Convert.ToInt32(SAMPLE_RATE)); }
        }

        /// <summary>
        /// Returns the recording state of the Microphone object
        /// </summary>
        /// <value>Enumeration that indicates whether the recording state of the Microphone has started or stopped</value>
        public MicrophoneState State
        {
            get { return (_microphoneState); }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Gets the latest recorded data from the microphone based on the audio capture buffer
        /// </summary>
        /// <returns>The buffer size, in bytes, of the audio data</returns>
        /// <param name="buffer">Buffer, in bytes, containing the captured audio data. The audio format must be PCM wave data</param>
        public int GetData(
            byte[] buffer
            )
        {
            // TODO: For Silverlight applications, once FrameworkDispatcher stub is complete we must ensure its Update 
            // method has been called at least once, or we should throw InvalidOperationException

            // Throw an ArgumentException if:
            // buffer is null, has zero length, or does not satisfy alignment requirements (sample alignment, not 10ms alignment)
            if (buffer == null || buffer.Length == 0 || buffer.Length%2 != 0)
                throw new ArgumentOutOfRangeException();

            // Setup pinned buffer handle
            GCHandle handle = GCHandle.Alloc(buffer, GCHandleType.Pinned);
            IntPtr bufferPtr = handle.AddrOfPinnedObject();

            // Read samples into buffer via pinned buffer handle pointer
            int availableSamples = capture.AvailableSamples;
            capture.ReadSamples(bufferPtr, availableSamples);

            // Tidy up
            handle.Free();

            // Return the data length
            return (availableSamples*2);
        }

        /// <summary>
        /// Gets the latest captured audio data from the microphone based on the specified offset and byte count
        /// </summary>
        /// <returns>The buffer size, in bytes, of the audio data</returns>
        /// <param name="buffer">Buffer, in bytes, containing the captured audio data. The audio format must be PCM wave data</param>
        /// <param name="offset">Offset, in bytes, to the starting position of the data</param>
        /// <param name="count">Amount, in bytes, of desired audio data</param>
        public int GetData(
            byte[] buffer,
            int offset,
            int count
            )
        {
            // An ArgumentException should be thrown when the following arguments are invalid:
            // 1. buffer is null, has zero length, or does not satisfy alignment requirements  (sample alignment, not 10ms alignment)
            // 2. offset is less than zero, is greater than or equal to the size of the buffer, or does not satisfy alignment requirements  (sample alignment, not 10ms alignment)
            // 3. The sum of count and offset is greater than the size of the buffer, count is less than or equal to zero, 
            //    or does not satisfy alignment requirements  (sample alignment, not 10ms alignment)
            if (buffer == null || buffer.Length == 0 || buffer.Length%2 != 0)
                throw new ArgumentOutOfRangeException();
            if (offset < 0 || offset > buffer.Length || offset%2 != 0)
                throw new ArgumentOutOfRangeException();
            if (count <= 0 || offset + count > buffer.Length || count%2 != 0)
                throw new ArgumentOutOfRangeException();

            // Create intermediate buffer
            // Note that the buffer is twice the size it needs to be to cater for any new samples that may
            // come in before GetData is called.
            byte[] data = new byte[capture.AvailableSamples*4];

            // Copy specified chunk of intermediate buffer to passed buffer, and ensure we do not go out of bounds
            int dataSize = GetData(data);
            int realCount = count > dataSize ? dataSize : count;
            Array.Copy(data, offset, buffer, 0, realCount - 1);

            // Return the data size
            return (realCount);
        }

        /// <summary>
        /// Returns the duration of audio playback based on the size of the buffer
        /// </summary>
        /// <returns>TimeSpan object that represents the duration of the audio playback.</returns>
        /// <param name="sizeInBytes">Size, in bytes, of the audio data</param>
        public TimeSpan GetSampleDuration(
            int sizeInBytes
            )
        {
            return (TimeSpan.FromMilliseconds((float) sizeInBytes/2f/SAMPLE_RATE/1000f));
        }

        /// <summary>
        /// Returns the size of the byte array required to hold the specified duration of audio for this microphone object
        /// </summary>
        /// <returns>Size (10 ms block aligned), in bytes, of the audio buffer</returns>
        /// <param name="duration">TimeSpan object that contains the duration of the audio sample</param>
        public int GetSampleSizeInBytes(
            TimeSpan duration
            )
        {
            // Calculate actual size required for duration
            int size = Convert.ToInt32((duration.TotalMilliseconds*SAMPLE_RATE/1000f))*2;

            // If needed, add extra bytes to size to bring it up to 10ms alignment boundary
            int spill = size%alignOn;
            if (spill != 0) size += alignOn - spill;

            return (size);
        }

        /// <summary>
        /// Starts microphone audio capture
        /// </summary>
        public void Start()
        {
            // TODO: For Silverlight applications, once FrameworkDispatcher stub is complete we must ensure its Update 
            // method has been called at least once, or we should throw InvalidOperationException

            // Calc internal ring buffer size (in samples not bytes!)
            int bufferSize = Convert.ToInt32(_bufferDuration.TotalMilliseconds*SAMPLE_RATE/1000f);

            // It seems that XNA always uses single chanel 16-bit integer PCM, so we will do the same
            capture = new AudioCapture(Name, Convert.ToInt32(SAMPLE_RATE), ALFormat.Mono16, bufferSize);
            capture.Start();
            _microphoneState = MicrophoneState.Started;

            // Start new thread that monitors capture.AvailableSamples > 0 and raises OnBufferReady event       
            pollBufferThread = new Thread(new ThreadStart(PollBuffer));
            pollBufferThread.Start();
        }

        /// <summary>
        /// Stops microphone audio capture
        /// </summary>
        public void Stop()
        {
            capture.Stop();
            _microphoneState = MicrophoneState.Stopped;
        }

        private void PollBuffer()
        {
            while (_microphoneState == MicrophoneState.Started)
            {
                if (capture.AvailableSamples > 0)
                    OnBufferReady(EventArgs.Empty);

                // 100ms is the minimum latency for this event under XNA
                Thread.Sleep(100);
            }
        }

        #endregion

        #region Public Events

        /// <summary>
        /// Event that occurs when the audio capture buffer is ready to be processed
        /// </summary>
        public event EventHandler<EventArgs> BufferReady;

        #endregion

        #region Private event raising

        private void OnBufferReady(EventArgs e)
        {
            if (BufferReady != null)
            {
                BufferReady(this, e);
            }
        }

        #endregion
    }
}
```
3 Than change Game class

```C#
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace MicTest
{
    /// <summary>
    /// This is the main type for your game
    /// </summary>
    public class Game1 : Microsoft.Xna.Framework.Game
    {
        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;

        private bool started;
        private MyMic.Microphone microphone;
        private TimeSpan timeSpan;
        private byte[] recorded;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }

        /// <summary>
        /// Allows the game to perform any initialization it needs to before starting to run.
        /// This is where it can query for any required services and load any non-graphic
        /// related content.  Calling base.Initialize will enumerate through any components
        /// and initialize them as well.
        /// </summary>
        protected override void Initialize()
        {
            // TODO: Add your initialization logic here


            microphone = MyMic.Microphone.All[0];

            base.Initialize();
        }

        /// <summary>
        /// LoadContent will be called once per game and is the place to load
        /// all of your content.
        /// </summary>
        protected override void LoadContent()
        {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new SpriteBatch(GraphicsDevice);

            // TODO: use this.Content to load your game content here
        }

        /// <summary>
        /// UnloadContent will be called once per game and is the place to unload
        /// all content.
        /// </summary>
        protected override void UnloadContent()
        {
            // TODO: Unload any non ContentManager content here
        }

        private KeyboardState lks;

        /// <summary>
        /// Allows the game to run logic such as updating the world,
        /// checking for collisions, gathering input, and playing audio.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Update(GameTime gameTime)
        {
            var ks = Keyboard.GetState();

            TimeSpan ts = TimeSpan.FromSeconds(1);

            if (started)
            {
                timeSpan += gameTime.ElapsedGameTime;
                if (timeSpan >= ts)
                {
                    microphone.GetData(recorded);

                    SoundEffect se = new SoundEffect(recorded, microphone.SampleRate, AudioChannels.Mono);
                    se.Play();

                    Console.Beep();
                    microphone.Stop();
                    timeSpan = TimeSpan.Zero;
                    started = false;
                }
            }

            if (lks.IsKeyUp(Keys.Enter) && ks.IsKeyDown(Keys.Enter))
            {
                started = true;
                microphone.BufferDuration = ts;
                recorded = new byte[microphone.GetSampleSizeInBytes(ts)];
                microphone.Start();
                
            }

            base.Update(gameTime);
        }

        /// <summary>
        /// This is called when the game should draw itself.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            // TODO: Add your drawing code here

            base.Draw(gameTime);
        }
    }
}
```
After you press Enter you have a second for talk to microphone, after this period SoundEffect(from XNA) reproduces it correctly.

**Comment by Shqrdx** [comment]
@wmartin129     
```C#
 /// <summary>
        /// Gets or sets audio capture buffer duration of the microphone
        /// </summary>
        /// <value>The duration of the audio capture buffer</value>
        public TimeSpan BufferDuration
        {
            get { return (_bufferDuration); }
            set
            {
                double check = value.TotalMilliseconds;
                if (check < 100f || check > 1000f || check%10f != 0f)
                    throw new ArgumentOutOfRangeException();

                // TODO: Once FrameworkDispatcher stub is complete we must ensure its Update 
                // method has been called at least once, or we should throw InvalidOperationException

                _bufferDuration = value;
            }
```
looks like you restrict microphone bufferring. Change or remove this restriction
>check > 1000f

```C#
 /// <summary>
        /// Returns the default attached microphone
        /// </summary>
        /// <value>The default microphone; returns null if there are no microphones attached</value>
        public static Microphone Default
        {
            get
            {
                if (_all.Count == 0)
                    return (null);

                string defaultDevice = OpenTK.Audio.AudioCapture.DefaultDevice;
                foreach (Microphone mic in All)
                {
                    if (mic.Name == defaultDevice)
                        return (mic);
                }
                return (null);
            }
        }
```
This property emit null reference exception - because _all is not initalized. Change it.

The microphone class must have internal default constructor because C# created default one and XNA does not allow to create a instance of Microphone class directly.

**Comment by danzel** [comment]
@Shqrdx In the diff view you can click on the line number and insert a comment directly in there (which also shows up in this discussion), saves copying the code out :)

**Comment by wmartin129** [comment]
@Shqrdx  Thanks - I have corrected the null reference exception you picked up on.

The buffer duration has been implemented in accordance with the MS XNA framework (https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.audio.microphone.bufferduration.aspx).  If you run my sample in the first post you may records sound of any duration.

**Comment by tomspilman** [comment]
Moving forward with https://github.com/MonoGame/MonoGame/pull/5651.

**Pull request closed without merging**
