### PR TITLE
Move MonoGame.Framework.Net to seperate directory

### LINKED ISSUE #4794: Move MonoGame.Framework.Net to its own folder
We want to move the code for the MonoGame.Framework.Net assembly into its own top level folder like we do for ``.  This would give us three top level folders where the core assembly code is found:
- MonoGame.Framework
- MonoGame.Framework.Net
- MonoGame.Framework.Content.Pipeline 

During the moving of this code _NO_ other code changes should occur.

The list of all the code files that need to be moved can be found here:

Note that the `MonoGame.Framework\Properties\AssemblyInfo.cs` should be copied and modified for the new assembly:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Properties/AssemblyInfo.cs

Also the `Path` in the protobuild definition needs to be changed:
  https://github.com/mono/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.Net.definition#L2

The installers for Mac, Linux, and Windows will need to be updated to pull from the new output bin folders.

Finally the configuration of the build server will have to change to pull from the new bin folders as well.

The idea was originally proposed in https://github.com/mono/MonoGame/issues/3055.

This also solves https://github.com/mono/MonoGame/issues/2981 and https://github.com/mono/MonoGame/issues/3480 if they haven't been resolved by fixes in XamarinStudio already.

### PR DESCRIPTION
**Pull request by Jjagg**
Does what it says on the tin. I hope the build passes 🤞 

Fixes #4794.

### CODE REVIEW

**Comment by cra0zy** [comment]
You need to fix file renaming XD

**Comment by Jjagg** [comment]
Well, that didn't work. I think this might have to do with line endings.

**Comment by Jjagg** [comment]
Yeah, I accidentally removed carriage returns. IMO that's not an issue and we would be better off enforcing Unix style line endings in a .gitattributes file.

**Comment by cra0zy** [comment]
We can make a separate PR for converting line encodings, in this PR please don't do that, its gonna make a nightmare of git history.

**Comment by Jjagg** [comment]
Oh, I didn't know it messes up history. Everything showed up as renames locally. But will fix tomorrow.

**Comment by Jjagg** [comment]
Good to go!

**Pull request merged**
