### PR TITLE
[SDL] Disable XInput so more than 4 controllers can be detected

### PR DESCRIPTION
**Pull request by cra0zy**
** NEEDS TESTING **

### CODE REVIEW

**Comment by mrhelmut** [comment]
I'll test this next week on Windows.

**Comment by endimilojkoski** [comment]
I tested this with bunch of gamepads (2x Xbox 360 wireless, 1x Xbox 360 wired, PS4, 2x iBuffalo) and it works with no issues. Pushing this live so the players that have a ton of wireless gamepads can test :)

**Comment by endimilojkoski** [comment]
Tried with 5 gamepads, combination of wired and wireless x360 and xone gamepads and only 4 are recognized so this is still not solved.

**Comment by mrhelmut** [comment]
Hmm, it should support up to 16 gamepads. Wonder if that hint really is working.

**Comment by endimilojkoski** [comment]
@mrhelmut just to be clear, I can use 8 gamepads but I can't use more than 4 XInput controllers like Xbox 360 and Xbox One. Do you see any workaround for this?

**Comment by mrhelmut** [comment]
Well, no, it looks like XInput is still being used and limiting the Xbox gamepads to 4. The SDL hint isn't working as expected.

**Pull request closed without merging**
