### PR TITLE
Added pixels processing function parameter to the Texture2D.FromStream/TextureFromFile

### PR DESCRIPTION
**Pull request by rds1983**
This PR adds parameter of type Action<byte[]> to Texture2D.FromStream/FromFile, which processes data in RGBA format before the data is sent to the video memory.
Also it adds two default color processors: ZeroTransparentPixels(used by default) and PremultiplyAlpha.
With this PR it would be possible to address #7363 by following code:
```c#
  var texture = Texture2D.FromStream(device, stream, null);
```
Or it would be possible to premultiply alpha:
```c#
  var texture = Texture2D.FromStream(device, stream, DefaultColorProcessors.PremultiplyAlpha);
```
Finally it would possible to write custom processor:
```c#
  // Sets every other pixel to red
  var flag = false;
  var texture = Texture2D.FromStream(gd, stream, data =>
            {
                for(var i = 0; i < data.Length; i += 4)
                {
                    if (flag)
                    {
                        data[i + 0] = 255;
                        data[i + 1] = 0;
                        data[i + 2] = 0;
                        data[i + 3] = 255;
                    }

                    flag = !flag;
                }
            });
```

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Bump @tomspilman / @Jjagg , candidate for 3.8.1?

**Comment by bartwe** [comment]
Calling a delegate function per pixel seems like it would be pretty slow compared to passing the buffer as a whole

**Comment by rds1983** [comment]
Makes sense, @bartwe. Fixed.

**Comment by harry-cpp** [comment]
> Bump @tomspilman / @Jjagg , candidate for 3.8.1?

Only fixes should go into 3.8.1, no new features.

**Comment by RUSshy** [comment]
I don't think such code has place on such a library

- it bloats the library
- Action is slow

**Comment by SimonDarksideJ** [comment]
Ok, Can this be merged after the 3.8.1 so it is available in dev.  Maybe now that we have moved to full nuget packages, we could look to publishing "preview" packages from the dev branch.

**Comment by vpenades** [comment]
I was wondering... as far as I know, "FromStream" does not generate mipmaps, right?

If that's the case, I would consider how the arguments would affect having a FromStream(stream stream, bool generateMipmaps) or something like that.

**Comment by mrhelmut** [comment]
This is really interesting, we should make it move forward for 3.8.1.

**Review by harry-cpp — APPROVED** [review]

**Review by Jjagg — APPROVED** [review]

**Pull request merged**
