### PR TITLE
Removes finalizers from multiple classes

### PR DESCRIPTION
**Pull request by quixoticaxis**
Discussed [here](https://github.com/MonoGame/MonoGame/issues/6279).

I removed finalizers which can be proven (or guessed with a high probability) to do little to nothing useful. The ones I left intact are the ones that are linked to some magic logic and global state handling. I hope this PR would make the code of this awesome framework more manageable.

At the time of writing the tests for this PR are passing at least as good as original "develop" branch on my local machine (1 error in `Debug` mode, 1 error + 1 failure in `Release` mode).

### CODE REVIEW

**Comment by nkast** [comment]
The finalizes are needed to implement the dispose pattern.
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by quixoticaxis** [comment]
@nkast From the link you provided: "The dispose pattern is used only for objects that access unmanaged resources". And *all* of these classes do *not* access unmanaged resources.

**Comment by nkast** [comment]
Then you should remove the IDispose first before removing the finalizers.

**Comment by quixoticaxis** [comment]
@nkast you probably may want to read the article to the end or use Visual Studio to auto-implement "Dispose pattern" - you'll see that it would be implemented without the finalizer (and there even would be a comment that explains why)

**Comment by quixoticaxis** [comment]
After re-evaluating the class hierarchies I decided to close this PR in order to re-open it (or another one) later. Removing finalization suppression everywhere was a mistake on my part as some of the changed classes are probably meant to serve as base classes for custom user hierarchies.

**Pull request closed without merging**
