### PR TITLE
#5511 - Enable VertexBuffer/IndexBuffer.GetData() on iOS

### PR DESCRIPTION
**Pull request by RufusMall**
Enable VertexBuffer/IndexBuffer.GetData() on iOS

### CODE REVIEW

**Comment by tomspilman** [comment]
@RufusMall if you fix these conflicts we can try to merge this.

**Comment by SimonDarksideJ** [comment]
Any update @RufusMall or can this be closed?

**Comment by RufusMall** [comment]
Sorry for the lack of response.

This was raised about 7 years ago, I am no longer working with monogame so I am not really setup to test these changes. I am just going to close this.

**Comment by SimonDarksideJ** [comment]
No worries @RufusMall , we wish you well on your GameDev adventures

**Pull request closed without merging**
