### PR TITLE
Fix the previous commit of SharpFont which broke windows

### PR DESCRIPTION
**Pull request by dellis1972**

### CODE REVIEW

**Comment by tomspilman** [comment]
@Jjagg @dellis1972 @KonajuGames @cra0zy - We really should add a unit test which runs the font processor.  Like we have unit tests running the texture and sound processors.  This could have been caught.

**Comment by KonajuGames** [comment]
Dean's PR #5987 introduces a sample content project build that includes a font build.  But we could add a specific test for font processor.

**Comment by tomspilman** [comment]
> sample content project build that includes a font build

That is good, but I think we should have a more specific test against features.

**Comment by vpenades** [comment]
Now it fails here in SharpFontImporter:

```
private Glyph ImportGlyph(char character, Face face)
		{
			uint glyphIndex = face.GetCharIndex(character);
			face.LoadGlyph(glyphIndex, LoadFlags.Default, LoadTarget.Normal);
			face.Glyph.RenderGlyph(RenderMode.Normal); << this method gives an AccessViolationException, attempt to read/write protected memory
```

**Comment by RUSshy** [comment]
pipeline content will be fixed in 50 years, i hope it is removed for monogame 4.0

**Comment by vpenades** [comment]
The problem is not the pipeline itself, in fact, it's better to pick the the content processing issues at compile time than at runtime... the real problem is depending on spooky third party libraries. In many cases it is unavoidable... in some others, maybe we might be able to have more than one choice for a particular inporter... so if one fails, to be able to choose another one.

But yes, I hope these issues are fixed soon (in less than 50 years ;)

**Comment by Jjagg** [comment]
@tomspilman @KonajuGames @dellis1972 Building fonts still fails (testing on Windows using the Pipeline Tool). Here's the stacktrace:
```
System.AccessViolationException occurred
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=SharpFont
  StackTrace:
   at SharpFont.FT.FT_Render_Glyph(IntPtr slot, RenderMode render_mode)
   at SharpFont.GlyphSlot.RenderGlyph(RenderMode mode)
   at Microsoft.Xna.Framework.Content.Pipeline.Graphics.SharpFontImporter.ImportGlyph(Char character, Face face)
   at Microsoft.Xna.Framework.Content.Pipeline.Graphics.SharpFontImporter.Import(FontDescription options, String fontName)
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.ImportFont(FontDescription options, Single& lineSpacing, Int32& yOffsetMin, ContentProcessorContext context, String fontName)
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process(FontDescription input, ContentProcessorContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(PipelineBuildEvent pipelineEvent, PipelineBuildEvent cachedEvent, String eventFilepath)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(String sourceFilepath, String outputFilepath, String importerName, String processorName, OpaqueDataDictionary processorParameters)
   at MGCB.BuildContent.Build(Int32& successCount, Int32& errorCount)
   at MGCB.Program.Main(String[] args)
```

**Pull request merged**
