### PR TITLE
Linux installer update

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
- MonoDevelop now gets properly detected
- Mimetype file now has a correct name
- Mimetype now gets properly uninstalled

### CODE REVIEW

**Comment by cra0zy** [comment]
@tomspilman @dellis1972 What's up with the build server?

**Comment by tomspilman** [comment]
@cra0zy  - It is fixed now.

**Comment by dellis1972** [comment]
@cra0zy good to go?

**Comment by cra0zy** [comment]
good to go.

**Pull request merged**
