### PR TITLE
Update ConsoleCheck to .NET 8.0

### PR DESCRIPTION
**Pull request by Nebulaxin**
Right now shared code in MonoGame.Framework is limited to C# 5, making it impossible to use common features like string interpolation

This limitation, however, can be lifted; instead cheking against specific language version in ConsoleCheck project, it can be done for decompiled framework; decompiler will try to convert C# 6+ features to C# 5 ones (eg. string interpolation to string concatenation)

### CODE REVIEW

**Comment by mrhelmut** [comment]
We can't update ConsoleCheck to newer .net, it's not just about the language version. It's also about the .net compiler _and_ the BCL version. It must be oldschool MSBUILD from older frameworks and limited to net452. This is because newer compilers won't produce IL code and format compatible with the legacy console runtime. This setup is the only way to make sure that the main repo doesn't break the console runtime.

But this will be irrelevant once #8194 is completed. Once the console runtime is entirely moved to NativeAOT, ConsoleCheck will be useless and removed from the repository (as well as the language and target framework limitation).

**Comment by Nebulaxin** [comment]
Right now I am trying to remake commonly used features from newer languages and BCL like Span and interpolated strings

I made this pull request so almost all features from net8.0 can be used while #8194 and #8309 are currently in progress

**Comment by mrhelmut** [comment]
It's really cool but I don't know if it's really worth doing since ConsoleCheck is going to disappear relatively soon and there is no impeding need to use C# 12 features in the framework codebase.

**Comment by Nebulaxin** [comment]
Yes, there is no need to use C#12; this pr exists just so we can already use C#5+ features; I also made another pr with all the changes that can be made: https://github.com/Nebulaxin/MonoGame/pull/4

**Comment by mrhelmut** [comment]
ConsoleCheck and UWP will be removed soon.

Side note if you intend to push your changes from your local fork: not a fan of upgrading code just for the sake of upgrading code (especially when things just work or when syntactic sugars make code harder to read/debug).

**Comment by mrhelmut** [comment]
Closing this because #8194 will make ConsoleCheck irrelevant.

**Pull request closed without merging**
