### PR TITLE
DesktopGL Theora videoplayer

### PR DESCRIPTION
**Pull request by Jjagg**
See #3983.

This is WIP, I think. I haven't tested at least, but best-case scenario it already works.
Also added float buffer submitting support to OpenAL and used it in OggStreamer. Theorafile also has a vorbis implementation (native lib), so now we have two implementations. We should fix that after we get this merged by replacing NVorbis.

Thanks @flibitijibibo ;)

### CODE REVIEW

**Comment by mrhelmut** [comment]
Cool! That was clearly missing.

This depends on the native ```theorafile``` binary as well, right? (it looks to be missing)
We'll have to make sure that it's not a requirement and that games shipping without videos don't need to ship that too (like OpenAL).

It might be interesting to consider using ```Theorafile-CS``` from source like ```NVorbis``` so that there's not another assembly to ship as well.

**Comment by Jjagg** [comment]
I have the libs added locally, will test before submitting a PR to Dependencies. Adding from source is a good idea :) I'll copy over the source file instead of adding as a submodule so people don't clone the whole repo when building from source.

**Comment by Jjagg** [comment]
Notes to self:
- Need to verify number of audio channels in the audio file is 1 or 2
- Need to make sure video format is supported for target platform (or transcode, but I don't think we should do that)

**Comment by Jjagg** [comment]
Gonna close this for now because it needs a lot of work. We could go with a more modern codec for our video player implementation, like AV1.

**Pull request closed without merging**
