### PR TITLE
Remove WIn8 / WP8 from NuGet's & update Sharp DX dependancies to 4.0.1

### PR DESCRIPTION
**Pull request by DDReaper**
Removed Win8 / WP8 from NuGet definitions
Updated NuGet Sharp DX dependencies to 4.0.1

### CODE REVIEW

**Comment by DDReaper** [comment]
Any ideas @tomspilman , getting this error on build now.

> File not found: 'MacOS\AnyCPU\Release\Tao.Sdl.dll'.

All I've done is remove the WP8 / Win 8 sections from the NuGets, so there should not have been any change to the Mac Build

**Comment by DDReaper** [comment]
Looks like this is impacted by #5934 which does remove those elements,  However it's not merged yet.
Thougths @dellis1972

**Comment by DDReaper** [comment]
Woot @tomspilman done and dusted

**Comment by tomspilman** [comment]
Ok... merging this now.

**Pull request merged**
