### PR TITLE
Added docs on setting up MonoGame on Windows

### PR DESCRIPTION
**Pull request by simoneddeland**

### CODE REVIEW

**Comment by cra0zy** [comment]
This is great! Thanks @simoneddeland!

**Comment by simoneddeland** [comment]
@mrhelmut I was not aware, I might make a new PR adding that info then!

**Comment by cra0zy** [comment]
@mrhelmut @simoneddeland I would much rather fix the installer than fix the doc on that one.

**Comment by simoneddeland** [comment]
@cra0zy OK I'll skip it then =)

**Comment by mrhelmut** [comment]
I agree!

**Pull request merged**
